import type { GoodSlug } from "./goods";

/**
 * 貿易系統 — 397 區手動分配的地區特產(2026-10-08,使用者要求「你來手動分配」)。
 *
 * 以「地區名稱」為鍵(與 MAP_CITY_SEED 同慣例;id 在地圖重劃時會變,名稱是穩定識別)。
 * 強度:3 = 主產(量大)、1 = 次產(量小)。糧食不在此表:糧食由肥沃度 × 面積決定,
 * 全地圖每區都產(lib/food.ts),不重複。
 *
 * 這是靜態設計資料,隨程式碼部署,不存資料庫、不需遷移、不會被地區重置洗掉。
 * 分配原則:歷史與地理代表性優先(魯爾煤鋼、巴庫與波斯灣油田、絲茶產地、香料群島);
 * 全圖約 45% 的區有特產,讓特產稀有、貿易有動機;石油主產僅 18 區(戰略焦點);
 * 石油與橡膠稀有金屬在工業時代前產量為 0(見 goods.ts unlockEra)。
 * 姆大陸為虛構地圖,無歷史依據,以「肥沃度低但礦與稀有金屬豐富」作補償設計。
 */
export type SpecialtyStrength = 1 | 3;
export type RegionSpecialty = Partial<Record<Exclude<GoodSlug, "food">, SpecialtyStrength>>;

export const REGION_SPECIALTIES: Readonly<Record<string, RegionSpecialty>> = {
  // ── 非洲(15/32)──
  "埃及尼羅": { spice: 1, cloth: 3 },
  "利比亞岸": { oil: 3 },
  "阿特拉斯": { ore: 3, oil: 1 },
  "幾內亞灣": { wood: 1, oil: 1 },
  "奈及利亞": { oil: 3, spice: 1 },
  "剛果河口": { wood: 3, oil: 1 },
  "剛果盆地": { wood: 3, rare: 1 },
  "加丹加高": { ore: 3, rare: 3 },
  "安哥拉北": { oil: 1 },
  "衣索比亞": { spice: 3 },
  "大湖區北": { spice: 3 },
  "尚比西河": { ore: 3 },
  "西南非洲": { rare: 3 },
  "南非德蘭": { ore: 3, ironcoal: 3, rare: 3 },
  "馬達加斯": { spice: 3 },
  // ── 西歐(15/44)──
  "蘇格蘭高地": { ore: 1 },
  "蘇格蘭低地": { ironcoal: 3, cloth: 1 },
  "南威爾斯": { ironcoal: 3 },
  "西密德蘭": { ironcoal: 3, cloth: 1 },
  "約克郡亨伯": { ironcoal: 3, cloth: 3 },
  "西北英格蘭": { ironcoal: 1, cloth: 3 },
  "東北英格蘭": { ironcoal: 3 },
  "羅訥隆河谷": { cloth: 3 },
  "大東部大區": { ore: 1, ironcoal: 3 },
  "巴登符騰堡": { wood: 3, cloth: 1 },
  "北萊茵西發": { ironcoal: 3 },
  "薩克森圖林": { ore: 3, cloth: 1 },
  "奧地利南部": { ore: 3, ironcoal: 1 },
  "荷蘭": { spice: 3 },
  "比利時": { ironcoal: 3, cloth: 3 },
  // ── 北歐(4/10)──
  "瑞典北部諾爾蘭": { wood: 3, ore: 3, ironcoal: 3 },
  "奧斯陸": { wood: 1 },
  "卑爾根沿海": { ore: 1 },
  "赫爾辛基": { wood: 3 },
  // ── 東歐(15/35)──
  "東烏克蘭": { ironcoal: 3 },
  "拉脫維亞": { wood: 3 },
  "西里西亞": { ironcoal: 3 },
  "莫斯科": { cloth: 3 },
  "列寧格勒": { wood: 3 },
  "韃靼斯坦": { oil: 1 },
  "薩馬拉": { oil: 3 },
  "羅斯托夫": { ironcoal: 3 },
  "高加索俄": { oil: 3 },
  "烏拉爾邊區": { ore: 3, rare: 3 },
  "摩拉維亞": { ironcoal: 3 },
  "捷克西里西": { ironcoal: 3 },
  "斯洛伐克東": { ore: 3 },
  "外西凡尼亞": { wood: 1, ore: 3 },
  "瓦拉幾亞": { oil: 3 },
  // ── 南歐(16/44)──
  "加泰隆尼亞": { cloth: 3 },
  "安達魯西亞": { ore: 3 },
  "瓦倫西亞": { spice: 3 },
  "巴斯克": { ironcoal: 3 },
  "卡斯提亞曼查": { ore: 3 },
  "倫巴底": { ironcoal: 1, cloth: 3 },
  "皮埃蒙特": { ironcoal: 1 },
  "威尼托": { spice: 3 },
  "托斯卡尼": { cloth: 3 },
  "坎帕尼亞": { spice: 1 },
  "西西里": { ore: 1, spice: 1 },
  "薩丁尼亞": { ore: 3 },
  "波士尼亞": { ore: 1 },
  "塞爾維亞南": { ore: 3 },
  "科索沃": { ore: 3, rare: 1 },
  "色雷斯": { spice: 1 },
  // ── 西亞(15/25)──
  "伊斯坦堡": { spice: 3, cloth: 1 },
  "愛琴海沿岸": { cloth: 3 },
  "亞塞拜然": { oil: 3 },
  "巴格達": { oil: 3, cloth: 1 },
  "伊拉克南": { oil: 1 },
  "伊斯法罕": { spice: 1, cloth: 3 },
  "胡齊斯坦": { oil: 3 },
  "利雅德": { oil: 3 },
  "漢志麥加": { spice: 3 },
  "東部省阿拉伯": { oil: 3 },
  "阿曼": { spice: 3 },
  "葉門": { spice: 3 },
  "阿聯酋": { oil: 1 },
  "卡達": { oil: 1 },
  "科威特巴林": { oil: 3 },
  // ── 中亞(7/18)──
  "西哈薩克": { oil: 1 },
  "東哈薩克": { ore: 3, rare: 1 },
  "卡拉干達": { ironcoal: 3 },
  "撒馬爾罕": { spice: 1, cloth: 3 },
  "費爾干納盆地": { cloth: 3 },
  "達沙古茲": { oil: 1 },
  "塔吉克": { rare: 3 },
  // ── 北亞(5/8)──
  "西西伯利亞": { wood: 1, oil: 3 },
  "亞馬爾": { oil: 1 },
  "阿爾泰薩彥": { ore: 3, rare: 1 },
  "克拉斯諾亞爾斯克": { ore: 3, ironcoal: 3 },
  "薩哈雅庫特": { ore: 1, rare: 3 },
  // ── 中國(23/42)──
  "興安漠北": { wood: 3 },
  "河朔": { ironcoal: 3 },
  "河東": { ironcoal: 3 },
  "陰山河套鄂爾多斯": { ironcoal: 3, rare: 1 },
  "遼東": { ironcoal: 3 },
  "松江吉林": { wood: 3 },
  "黑龍江東": { wood: 3, oil: 3 },
  "膠東": { ore: 3 },
  "滬上": { cloth: 3 },
  "太湖": { spice: 3, cloth: 3 },
  "會稽浙東": { spice: 3, cloth: 1 },
  "江漢荊楚": { ironcoal: 3 },
  "洞庭湘江": { ore: 3, spice: 1 },
  "鄱陽贛江": { rare: 3, spice: 3 },
  "閩中沿海": { spice: 3 },
  "武夷閩西": { spice: 3 },
  "珠江嶺南": { spice: 1, cloth: 3 },
  "蜀郡天府": { spice: 1, cloth: 3 },
  "康巴川西": { ore: 1 },
  "牂牁黔中": { ore: 1 },
  "南詔滇東": { ore: 3, spice: 1 },
  "河西隴右": { oil: 1 },
  "青唐西海": { rare: 3 },
  // ── 東亞(8/23)──
  "北海道": { ironcoal: 3 },
  "東海中京圈": { ironcoal: 1, cloth: 3 },
  "近畿": { cloth: 3 },
  "九州島": { ironcoal: 3 },
  "江原道": { ore: 3 },
  "雞籠": { ironcoal: 1 },
  "平壤": { ore: 3, ironcoal: 1 },
  "咸鏡": { ore: 3 },
  // ── 東南亞與大洋洲(12/25)──
  "伊洛瓦底平原": { wood: 3, oil: 1 },
  "泰北山地": { wood: 3 },
  "紅河三角洲": { ironcoal: 3 },
  "湄公河三角洲": { rare: 3, spice: 1 },
  "半島東西海岸": { ore: 3, rare: 3 },
  "蘇門答臘島": { oil: 3, rare: 3 },
  "爪哇島": { rare: 1, spice: 3 },
  "婆羅洲東馬": { wood: 3, oil: 1 },
  "蘇拉威西摩鹿加": { spice: 3 },
  "新幾內亞島": { ore: 3 },
  "澳洲東部沿海": { ore: 1, ironcoal: 3 },
  "澳洲中西部內陸": { ore: 3, rare: 3 },
  // ── 美洲(16/27)──
  "魁北克": { wood: 3, ore: 1 },
  "安大略": { ore: 3, ironcoal: 1 },
  "加西草原": { oil: 3 },
  "卑詩": { wood: 3 },
  "新英格蘭": { cloth: 3 },
  "賓州大西洋中": { ironcoal: 3 },
  "五大湖芝加哥": { ironcoal: 3 },
  "上南方阿帕拉契": { ironcoal: 3 },
  "深南迪克西": { cloth: 3 },
  "大德州": { oil: 3 },
  "西北太平洋": { wood: 3 },
  "西南四角地帶": { ore: 3, rare: 3 },
  "阿拉斯加": { oil: 3 },
  "中央高原": { ore: 3 },
  "中美地峽": { wood: 1, rare: 3 },
  "西印度群島": { spice: 3 },
  // ── 南亞(10/22)──
  "比哈爾": { ironcoal: 3 },
  "古吉拉特": { cloth: 3 },
  "馬哈拉施特拉": { cloth: 3 },
  "果阿": { spice: 3 },
  "西孟加拉": { spice: 1, cloth: 3 },
  "奧里薩": { ore: 3, ironcoal: 3 },
  "阿薩姆": { oil: 1, spice: 3 },
  "坦米爾納杜": { cloth: 3 },
  "喀拉拉": { spice: 3 },
  "斯里蘭卡": { spice: 3 },
  // ── 南美(7/18)──
  "亞馬遜盆地": { wood: 3, rare: 3 },
  "里約聖保羅": { spice: 3 },
  "巴西高地": { ore: 3, ironcoal: 3 },
  "委內瑞拉": { oil: 3 },
  "哥倫比亞": { oil: 1, spice: 3 },
  "玻利維亞": { ore: 3, rare: 1 },
  "智利": { ore: 3, rare: 3 },
  // ── 姆大陸(12/24)──
  "姆西岬": { rare: 3 },
  "晨星岬": { rare: 3 },
  "姆西原": { ore: 3 },
  "姆中央谷地": { spice: 3 },
  "聖樹平原": { spice: 1 },
  "日昇高原": { rare: 3 },
  "紅岩台地": { ore: 3, ironcoal: 3 },
  "王都盆地": { spice: 1, cloth: 3 },
  "月神湖區": { spice: 3 },
  "長尾半島": { oil: 1 },
  "遺跡高地": { ore: 1, rare: 3 },
  "復活節尖端": { rare: 3 },
};

/** 取得某區特產(查無 = 無特產)。 */
export function specialtyOf(regionName: string): RegionSpecialty {
  return REGION_SPECIALTIES[regionName] ?? {};
}
