import { Router, type IRouter } from "express";
import healthRouter from "./health";
import botRouter from "./bot";
import authRouter from "./auth";
import mapRegionsRouter from "./mapRegions";
import playerRouter from "./player";
import regionControlsRouter from "./regionControls";
import territoryHistoryRouter from "./territoryHistory";
import storageRouter from "./storage";
import gameMusicRouter from "./gameMusic";
import militaryRouter from "./military";
import regionBuildingsRouter from "./regionBuildings";
import diplomacyRouter from "./diplomacy";
import alliancesRouter from "./alliances";
import warRouter from "./war";
import npcNationsRouter from "./npcNations";
import politicsRouter from "./politics";
import economyRouter from "./economy";
import techTreeRouter from "./techTree";
import techTreeAdminRouter from "./techTreeAdmin";
import turnRouter from "./turn";
import worldSimRouter from "./worldSim";
import accountBansRouter from "./accountBans";
import cabinetRouter from "./cabinet";
import adminResetRouter from "./adminReset";
import giftsRouter from "./gifts";
import { superEventsRouter } from "./superEvents";
import gameBalanceRouter from "./gameBalance";
import aiUsageRouter from "./aiUsage";
import militaryAdminRouter from "./militaryAdmin";

const router: IRouter = Router();

router.use(healthRouter);
router.use(botRouter);
router.use(authRouter);
router.use(mapRegionsRouter);
router.use(playerRouter);
router.use(regionControlsRouter);
router.use(territoryHistoryRouter);
router.use(storageRouter);
router.use(gameMusicRouter);
router.use(militaryRouter);
router.use(regionBuildingsRouter);
router.use(diplomacyRouter);
router.use(alliancesRouter);
router.use(warRouter);
router.use(npcNationsRouter);
router.use(politicsRouter);
router.use(economyRouter);
router.use(techTreeRouter);
router.use(techTreeAdminRouter);
router.use(turnRouter);
router.use(worldSimRouter);
router.use(accountBansRouter);
router.use(cabinetRouter);
router.use(adminResetRouter);
router.use(giftsRouter);
router.use(superEventsRouter);
router.use(gameBalanceRouter);
router.use(aiUsageRouter);
router.use(militaryAdminRouter);

export default router;
