import { Router, type IRouter } from "express";
import healthRouter from "./health";
import botRouter from "./bot";
import authRouter from "./auth";
import mapRegionsRouter from "./mapRegions";
import playerRouter from "./player";
import regionControlsRouter from "./regionControls";
import missileRouter from "./missile";
import territoryHistoryRouter from "./territoryHistory";
import storageRouter from "./storage";
import gameMusicRouter from "./gameMusic";
import militaryRouter from "./military";
import mercenaryRouter from "./mercenary";
import mobilizationRouter from "./mobilization";
import generalsRouter from "./generals";
import regionBuildingsRouter from "./regionBuildings";
import diplomacyRouter from "./diplomacy";
import alliancesRouter from "./alliances";
import warRouter from "./war";
import npcNationsRouter from "./npcNations";
import politicsRouter from "./politics";
import parliamentRouter from "./parliament";
import focusRouter from "./focus";
import domesticEventsRouter from "./domesticEvents";
import domesticEventsAdminRouter from "./domesticEventsAdmin";
import militaryDemandRouter from "./militaryDemand";
import economyRouter from "./economy";
import techTreeRouter from "./techTree";
import techTreeAdminRouter from "./techTreeAdmin";
import turnRouter from "./turn";
import worldSimRouter from "./worldSim";
import accountBansRouter from "./accountBans";
import oilRigsRouter from "./oilRigs";
import cabinetRouter from "./cabinet";
import autopilotRouter from "./autopilot";
import adminResetRouter from "./adminReset";
import giftsRouter from "./gifts";
import { superEventsRouter } from "./superEvents";
import gameBalanceRouter from "./gameBalance";
import aiUsageRouter from "./aiUsage";
import aiQueueRouter from "./aiQueue";
import militaryAdminRouter from "./militaryAdmin";
import dbMigrateAdminRouter from "./dbMigrateAdmin";

const router: IRouter = Router();

router.use(healthRouter);
router.use(botRouter);
router.use(authRouter);
router.use(mapRegionsRouter);
router.use(playerRouter);
router.use(regionControlsRouter);
router.use(missileRouter);
router.use(territoryHistoryRouter);
router.use(storageRouter);
router.use(gameMusicRouter);
router.use(militaryRouter);
router.use(mercenaryRouter);
router.use(mobilizationRouter);
router.use(generalsRouter);
router.use(regionBuildingsRouter);
router.use(diplomacyRouter);
router.use(alliancesRouter);
router.use(warRouter);
router.use(npcNationsRouter);
router.use(politicsRouter);
router.use(parliamentRouter);
router.use(focusRouter);
router.use(domesticEventsRouter);
router.use(domesticEventsAdminRouter);
router.use(militaryDemandRouter);
router.use(economyRouter);
router.use(techTreeRouter);
router.use(techTreeAdminRouter);
router.use(turnRouter);
router.use(worldSimRouter);
router.use(accountBansRouter);
router.use(oilRigsRouter);
router.use(cabinetRouter);
router.use(autopilotRouter);
router.use(adminResetRouter);
router.use(giftsRouter);
router.use(superEventsRouter);
router.use(gameBalanceRouter);
router.use(aiUsageRouter);
router.use(aiQueueRouter);
router.use(militaryAdminRouter);
router.use(dbMigrateAdminRouter);

export default router;
