import type { DomesticEventDef } from "../types";
import { ev } from "./helper";

/** 經濟(10):通膨、罷工、債務、貿易、銀行、農產、物價、貨幣、失業、稅制 */
export const ECONOMY_EVENTS: readonly DomesticEventDef[] = [
  ev("economy", "econ_hyper_inflation", "惡性通膨危機加劇",
    "國內主要物資價格飛漲，民生用品價格單月翻倍，基層民眾生活陷入困境，各界呼籲政府平抑物價。", 9,
    ["動用國庫發放物資津貼", "國庫大幅失血，但穩定度與政治支持回升", { money: -2500, stability: 6, politicalSupport: 8 }],
    ["實施物價管制並查封囤積", "軍方出動平抑市場，但議會強烈反彈且引發內戰風險", { militarySatisfaction: 8, parliamentSatisfaction: -12, stability: -8, civilWarRisk: true }],
    ["呼籲商家自律觀望市場", "民眾失望，穩定度與政治支持小幅下降", { stability: -4, politicalSupport: -4 }]),
  ev("economy", "econ_dock_worker_strike", "全國港口工人聯合罷工",
    "碼頭工會因薪資談判破裂發動總罷工，海運出口全面停擺，商會警示日損失數十億，要求政府干預。", 9,
    ["撥款補助工會提高待遇", "國庫支出增加，議會與穩定回升，但軍方不安", { money: -1750, parliamentSatisfaction: 6, stability: 5, militarySatisfaction: -3 }],
    ["派兵強制接管港口營運", "軍方滿意，但引發衝突，穩定度與議會滿意度暴跌", { militarySatisfaction: 10, stability: -14, parliamentSatisfaction: -10, civilWarRisk: true }],
    ["組建協調小組持續斡旋", "罷工持續拉鋸，政治支持與穩定略降", { stability: -3, politicalSupport: -3 }]),
  ev("economy", "econ_sovereign_debt_default", "國債到期違約風險",
    "政府發行之短期國債即將到期，國庫現金不足支應償還壓力，國際評級機構威脅降評。", 8,
    ["緊急縮減開支並籌措償債", "政治支持與議會滿意度受損，但避免財政崩饋", { money: -2000, politicalSupport: -6, parliamentSatisfaction: -5, stability: 4 }],
    ["單方面宣布債務延期償付", "軍方支持硬氣作風，但議會大怒與穩定重創", { militarySatisfaction: 6, parliamentSatisfaction: -14, stability: -12, civilWarRisk: true }],
    ["請求債權人展延談判", "市場信心受挫，政治支持下滑", { politicalSupport: -5, stability: -3 }]),
  // 原有事件(id 與數值不變;資料庫裡已存在的事件仍要能解析)
  ev("economy", "economic_crisis", "經濟危機來襲",
    "物價飛漲、工廠停工,銀行門口排起長隊,民怨沸騰。", 8,
    ["動用國庫緊急紓困", "穩定回升,國庫大失血", { money: -2500, stability: 8 }],
    ["推行緊縮,強壓物價", "國庫回血,但穩定與議會下滑", { money: 1500, stability: -8, parliamentSatisfaction: -6 }],
    ["靜觀其變", "穩定下滑", { stability: -10 }]),
  ev("economy", "econ_bank_run_panic", "主要商業銀行擠兌",
    "大型商業銀行爆出呆帳過高傳聞，各地分行湧現提款人潮，金融體系面臨連鎖倒閉危機。", 7,
    ["注入中央銀行資金流動性", "國庫花費巨大，但成功穩定金融秩序", { money: -2500, stability: 8, parliamentSatisfaction: 4 }],
    ["限制每日提款額度並查封金庫", "軍方控管秩序，但引發集體恐慌且穩定大跌", { militarySatisfaction: 8, stability: -16, politicalSupport: -10, civilWarRisk: true }],
    ["發表新聞稿宣稱資金無虞", "無法解決根本恐慌，政治支持下滑", { politicalSupport: -6, stability: -3 }]),
  ev("economy", "econ_crop_failure_crisis", "氣候異變致農作欠收",
    "主糧產區遭受嚴重旱災，糧食產量預估銳減四成，糧商開始惜售囤積，糧價應聲大漲。", 8,
    ["動用外匯籌措採購進口糧食", "國庫支出大，但民心與穩定獲得安撫", { money: -2000, stability: 7, politicalSupport: 5 }],
    ["強制收購各地農倉糧食", "軍方執行徵集，但引發地方強烈反彈與內戰風險", { militarySatisfaction: 8, stability: -14, parliamentSatisfaction: -8, civilWarRisk: true }],
    ["發起節約糧食宣導", "無法撫平缺糧危機，穩定度下滑", { stability: -5, politicalSupport: -2 }]),
  ev("economy", "econ_energy_price_surge", "國際能源價格暴漲",
    "國際原油與電力價格大幅上揚，國內火力發電廠營運成本驟增，各行各業面臨停電與成本壓力。", 8,
    ["政府吸收部分電價與油價差額", "國庫承受財政負擔，穩定度與議會回升", { money: -2250, stability: 5, parliamentSatisfaction: 6 }],
    ["對高耗能產業實施強制限電", "軍方維持設施安全，但企業反彈，穩定度下降", { militarySatisfaction: 8, parliamentSatisfaction: -12, stability: -10, civilWarRisk: true }],
    ["研議長期能源轉型政策", "短期無助紓解物價，政治支持下滑", { politicalSupport: -4, stability: -3 }]),
  ev("economy", "econ_currency_devaluation", "本國貨幣重挫貶值",
    "國際外匯市場出現大量本幣拋售潮，匯率單日重挫近一成，進口物資價格暴漲，市場瀰漫恐慌。", 7,
    ["消耗外匯存底進場干預匯市", "國庫消耗巨大，但穩住匯率與穩定度", { money: -2500, stability: 6, politicalSupport: 5 }],
    ["實施嚴格外匯管制與資本管制", "軍方協助稽查黑市，但議會與穩定大幅下降", { militarySatisfaction: 8, parliamentSatisfaction: -10, stability: -12, civilWarRisk: true }],
    ["發表聲明強調經濟基調穩健", "無法遏止貶值潮，政治支持下滑", { politicalSupport: -5, stability: -3 }]),
  ev("economy", "econ_mass_layoffs_wave", "傳統產業爆發裁員潮",
    "多家大型製造工廠受景氣低迷影響相繼倒閉，數萬名工人一夕失業，失業率創下五年新高。", 8,
    ["擴大公共工程與發放失業救濟", "國庫花費顯著，但獲得議會與民心肯定", { money: -2000, parliamentSatisfaction: 7, politicalSupport: 6 }],
    ["禁止企業裁員並強行徵調勞工", "軍方執法強硬，但企業反彈，穩定度重創", { militarySatisfaction: 8, parliamentSatisfaction: -12, stability: -10, civilWarRisk: true }],
    ["開設就業轉職媒合窗口", "緩不濟急，穩定度與政治支持下滑", { stability: -3, politicalSupport: -4 }]),
  ev("economy", "econ_tax_evasion_scandal", "財團大規模逃漏稅案",
    "調查報導揭發多家富豪企業透過境外避稅天堂規避鉅額稅款，輿論強烈要求政府追討並改革稅制。", 7,
    ["成立專案小組追繳稅款並補貼國庫", "政治支持與議會回升，但財團報復使穩定下滑", { money: 1500, politicalSupport: 8, parliamentSatisfaction: 6, stability: -4 }],
    ["查封逃稅財團資產並收歸國有", "國庫收益大增加上軍方支持，但穩定大跌且有風險", { money: 2500, militarySatisfaction: 10, stability: -14, civilWarRisk: true }],
    ["宣示研議修法但暫不追討", "民眾質疑官商勾結，政治支持與議會下滑", { politicalSupport: -5, parliamentSatisfaction: -4 }]),
];
