import type { DomesticEventDef } from "../types";
import { ev } from "./helper";

/** 政局(10):罷免、醜聞、政黨、選舉、權力鬥爭 */
export const POLITICS_EVENTS: readonly DomesticEventDef[] = [
  // ── 原有事件(id 與數值不變) ──
  ev("politics", "recall_wave", "國內爆發罷免潮",
    "街頭的連署與集會一波接一波,民眾要求罷免現任官員,議會內也有人附和。", 10,
    ["接受罷免,改組內閣", "穩定與議會回升,軍方不滿", { stability: 8, parliamentSatisfaction: 10, militarySatisfaction: -5 }],
    ["宣布戒嚴,取締集會", "軍方支持,但穩定大降且有內戰風險", { stability: -20, militarySatisfaction: 12, civilWarRisk: true }],
    ["拖延,等風頭過去", "穩定與議會都受損", { stability: -6, parliamentSatisfaction: -8 }]),
  {
    kind: "socialist_majority", category: "politics", title: "社會黨人取得議會多數",
    body: "選舉與補選之後,社會黨人成為議會最大勢力,議會要求政府推動他們的政策。",
    weight: 10, defaultChoiceId: "delay",
    choices: [
      { id: "comply", style: "comply", label: "順應議會,推動社會政策", hint: "議會大幅回升,但國庫吃緊、軍方不安", effects: { parliamentSatisfaction: 15, money: -1500, militarySatisfaction: -8, parliamentShift: "socialists_in" } },
      { id: "crackdown", style: "crackdown", label: "宣布戒嚴,將社會黨人逐出議會", hint: "軍方支持,但穩定暴跌且有內戰風險", effects: { stability: -25, militarySatisfaction: 15, parliamentSatisfaction: -15, civilWarRisk: true, parliamentShift: "socialists_out" } },
      { id: "delay", style: "delay", label: "折衷讓步,只採納部分主張", hint: "議會略升,花一點錢", effects: { parliamentSatisfaction: 4, money: -600 } },
    ],
  },
  // ── 新增 ──
  ev("politics", "minister_scandal", "部長爆出貪污醜聞",
    "媒體揭露一位重量級部長長期收受承包商賄賂,反對黨要求徹查,街頭開始出現抗議標語。", 9,
    ["撤換部長並公開調查", "政治支持回升,國庫花費調查費用", { politicalSupport: 10, parliamentSatisfaction: 6, money: -800 }],
    ["封鎖消息並威嚇記者", "軍方滿意,但政治支持與穩定下滑", { politicalSupport: -14, stability: -8, militarySatisfaction: 8, civilWarRisk: true }],
    ["發表聲明稱純屬謠言", "政治支持小降", { politicalSupport: -6, parliamentSatisfaction: -2 }]),
  ev("politics", "party_split", "執政陣營公開分裂",
    "執政聯盟內部為了路線之爭翻臉,一派議員宣布退出並與反對黨聯手杯葛預算。", 8,
    ["讓出內閣職位換取團結", "議會與穩定回升,但要花錢安撫", { parliamentSatisfaction: 12, stability: 5, money: -1200 }],
    ["開除異議議員,強行表決", "軍方認同,但議會大怒且穩定下滑", { parliamentSatisfaction: -14, stability: -10, militarySatisfaction: 6, civilWarRisk: true }],
    ["冷處理,等盟友自己回頭", "議會滿意度下滑", { parliamentSatisfaction: -7, politicalSupport: -3 }]),
  ev("politics", "snap_election_demand", "全國要求提前大選",
    "民調持續低迷,各黨與民間團體串連要求提前改選,聲勢一天比一天大。", 8,
    ["宣布提前改選", "議會與政治支持上升,但軍方憂慮", { parliamentSatisfaction: 10, politicalSupport: 10, militarySatisfaction: -6 }],
    ["以國家安全為由拒絕改選", "軍方支持,但穩定大降", { stability: -16, militarySatisfaction: 10, parliamentSatisfaction: -10, civilWarRisk: true }],
    ["承諾研議,但不給時程", "政治支持下滑", { politicalSupport: -8, stability: -2 }]),
  ev("politics", "coalition_blackmail", "小黨以倒閣要脅",
    "一個關鍵小黨放話,若不給他們三個部長席位與專屬預算,就要在不信任案上倒戈。", 7,
    ["答應條件,組成更大聯盟", "議會穩住,國庫失血", { parliamentSatisfaction: 10, stability: 4, money: -1800 }],
    ["公開揭露其財務黑幕", "政治支持升,但議會反彈且有政治風險", { politicalSupport: 8, parliamentSatisfaction: -14, stability: -6, civilWarRisk: true }],
    ["談判拖著不表態", "議會不滿累積", { parliamentSatisfaction: -6, politicalSupport: -2 }]),
  ev("politics", "leaked_cables", "外洩的機密文件曝光",
    "一批記載內部爭權與密室協議的文件流出,各界譁然,盟友與對手都在質疑政府的誠信。", 7,
    ["公開道歉並改革保密制度", "政治支持與議會回升,花錢整頓", { politicalSupport: 8, parliamentSatisfaction: 6, money: -1000 }],
    ["追捕洩密者並嚴懲", "軍方支持,但輿論反感", { militarySatisfaction: 8, politicalSupport: -12, stability: -6, civilWarRisk: true }],
    ["稱文件是偽造的", "政治支持下滑", { politicalSupport: -7, parliamentSatisfaction: -3 }]),
  ev("politics", "regional_autonomy_push", "邊遠地區要求自治",
    "幾個偏遠地區的地方領袖聯名要求擴大自治權,否則拒絕繳交稅款。", 7,
    ["授予有限自治權", "穩定回升,但中央威信與財政受損", { stability: 8, politicalSupport: -4, money: -1200, parliamentSatisfaction: 4 }],
    ["派兵進駐,接管地方行政", "軍方支持,但穩定暴跌且有內戰風險", { militarySatisfaction: 10, stability: -22, politicalSupport: -6, civilWarRisk: true }],
    ["拖延談判,派特使安撫", "穩定略降", { stability: -6, politicalSupport: -3 }]),
  ev("politics", "veteran_statesman_return", "元老政治家復出",
    "一位聲望極高的退休元老公開批評政府,並宣布將協助反對陣營,民間聲量不小。", 6,
    ["邀請元老入閣,共商國是", "政治支持與議會上升,但要讓出權力", { politicalSupport: 10, parliamentSatisfaction: 8, militarySatisfaction: -4 }],
    ["以莫須有罪名軟禁元老", "軍方支持,但輿論嘩然", { militarySatisfaction: 8, politicalSupport: -14, stability: -10, civilWarRisk: true }],
    ["不予理會", "政治支持小降", { politicalSupport: -6, parliamentSatisfaction: -2 }]),
  ev("politics", "budget_standoff", "預算案陷入僵局",
    "議會遲遲不肯通過新年度預算,部分政府機關已經開始延遲發放薪資。", 8,
    ["讓步並修改預算內容", "議會回升,穩定略升,國庫吃緊", { parliamentSatisfaction: 10, stability: 4, money: -1400 }],
    ["以行政命令凍結預算", "軍方支持,但議會強烈反彈", { militarySatisfaction: 6, parliamentSatisfaction: -16, stability: -8, civilWarRisk: true }],
    ["暫時撙節,等議會鬆口", "穩定與議會都下滑", { stability: -5, parliamentSatisfaction: -5 }]),
];
