// Task #469 — 科技樹預設種子（military 領域，後半）

import type { MilitaryTechBonus } from "@workspace/db";
import type { TechTreeSeedEra } from "./types";

export const MILITARY_ERAS_LATE: TechTreeSeedEra<MilitaryTechBonus>[] = [
  {
    eraSlug: "enlightenment",
    lines: [
      {
        lineKey: "infantry",
        lineLabel: "線列步兵",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "線列戰術",
            description: "步兵排成橫列齊射，火力集中於一線。",
            baseCost: 49,
            effects: [],
          },
          {
            order: 2,
            name: "燧發槍陣",
            description: "全軍換裝燧發槍，發射迅捷不畏風雨。",
            baseCost: 65,
            effects: [],
          },
          {
            order: 3,
            name: "三排齊射",
            description: "三排輪替裝填射擊，火力連綿不絕。",
            baseCost: 82,
            effects: [],
          },
          {
            order: 4,
            name: "刺刀衝鋒",
            description: "齊射後上刺刀突擊，一鼓作氣衝垮敵陣。",
            baseCost: 98,
            effects: [],
          },
          {
            order: 5,
            name: "擲彈兵隊",
            description: "精選壯士組擲彈兵，投彈破敵陣列。",
            baseCost: 114,
            effects: [],
          },
          {
            order: 6,
            name: "輕步兵散",
            description: "輕步兵散開游擊，掩護主力騷擾敵軍。",
            baseCost: 130,
            effects: [],
          },
          {
            order: 7,
            name: "縱隊突擊",
            description: "以密集縱隊猛衝敵線，撕開缺口擴大戰果。",
            baseCost: 147,
            effects: [],
          },
          {
            order: 8,
            name: "方陣抗騎",
            description: "步兵結空心方陣拒騎，步兵防禦提升。",
            baseCost: 163,
            effects: [{ target: "defense", category: "infantry", pct: 5 }],
          },
          {
            order: 9,
            name: "預備軍團",
            description: "編組預備軍團待命，關鍵時刻投入決勝。",
            baseCost: 179,
            effects: [],
          },
          {
            order: 10,
            name: "常備陸軍",
            description: "建立常備陸軍長年操練，戰力隨時可用。",
            baseCost: 195,
            effects: [],
          },
        ],
      },
      {
        lineKey: "artillery",
        lineLabel: "野戰砲兵",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "輕型野砲",
            description: "輕便野砲隨軍推進，野戰即時支援火力。",
            baseCost: 49,
            effects: [],
          },
          {
            order: 2,
            name: "統一砲制",
            description: "統一火砲規格與零件，量產維修皆便。",
            baseCost: 65,
            effects: [],
          },
          {
            order: 3,
            name: "騎砲機動",
            description: "砲兵配馬快速機動，隨騎兵疾馳赴戰。",
            baseCost: 82,
            effects: [],
          },
          {
            order: 4,
            name: "彈藥前車",
            description: "以彈藥前車隨砲運補，射擊持續不斷。",
            baseCost: 98,
            effects: [],
          },
          {
            order: 5,
            name: "榴彈砲擊",
            description: "發射爆裂榴彈，落地開花殺傷成群。",
            baseCost: 114,
            effects: [],
          },
          {
            order: 6,
            name: "霰彈近迫",
            description: "近距發射霰彈，橫掃逼近的敵步兵。",
            baseCost: 130,
            effects: [],
          },
          {
            order: 7,
            name: "砲兵連陣",
            description: "多門火砲編連統一射擊，火力齊發。",
            baseCost: 147,
            effects: [],
          },
          {
            order: 8,
            name: "集中砲火",
            description: "集中火砲轟擊要點，砲兵攻擊力提升。",
            baseCost: 163,
            effects: [{ target: "attack", category: "artillery", pct: 5 }],
          },
          {
            order: 9,
            name: "砲兵測繪",
            description: "測繪地形推算射諸元，砲擊精準有據。",
            baseCost: 179,
            effects: [],
          },
          {
            order: 10,
            name: "砲兵學院",
            description: "設砲兵學院培育砲官，砲術蔚然成家。",
            baseCost: 195,
            effects: [],
          },
        ],
      },
      {
        lineKey: "logistics",
        lineLabel: "軍需補給",
        lineKind: "branch",
        branchFrom: { lineKey: "infantry", order: 3 },
        nodes: [
          {
            order: 1,
            name: "軍需倉庫",
            description: "沿線設軍需倉庫囤積，前線取用便捷。",
            baseCost: 39,
            effects: [],
          },
          {
            order: 2,
            name: "徵兵制度",
            description: "推行徵兵徵集兵員，充實常備軍力。",
            baseCost: 59,
            effects: [],
          },
          {
            order: 3,
            name: "補給縱列",
            description: "組補給縱列隨軍運補，維持成本得以撙節。",
            baseCost: 78,
            effects: [{ target: "upkeep", category: null, pct: -5 }],
          },
          {
            order: 4,
            name: "參謀本部",
            description: "設參謀本部規劃作戰與動員，運籌全局。",
            baseCost: 98,
            effects: [],
          },
        ],
      },
    ],
  },
  {
    eraSlug: "industrial",
    lines: [
      {
        lineKey: "firearms",
        lineLabel: "工業兵器",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "後膛裝填",
            description: "改為後膛裝填，臥姿速射不必起身。",
            baseCost: 76,
            effects: [],
          },
          {
            order: 2,
            name: "定裝彈藥",
            description: "彈頭火藥合成一體，裝填射擊更迅捷。",
            baseCost: 101,
            effects: [],
          },
          {
            order: 3,
            name: "米尼彈",
            description: "尖錐米尼彈契合膛線，射遠而準。",
            baseCost: 126,
            effects: [],
          },
          {
            order: 4,
            name: "膛線步槍",
            description: "膛線步槍普及全軍，射程精度大進。",
            baseCost: 151,
            effects: [],
          },
          {
            order: 5,
            name: "彈匣供彈",
            description: "以彈匣連續供彈，火力持續不斷。",
            baseCost: 176,
            effects: [],
          },
          {
            order: 6,
            name: "加特林機槍",
            description: "多管旋轉機槍傾瀉彈雨，壓制成片敵軍。",
            baseCost: 202,
            effects: [],
          },
          {
            order: 7,
            name: "無煙火藥",
            description: "改用無煙火藥，射擊不生煙障暴露位置。",
            baseCost: 227,
            effects: [],
          },
          {
            order: 8,
            name: "連發步槍",
            description: "連發步槍提升火力密度，步兵攻擊提升。",
            baseCost: 252,
            effects: [{ target: "attack", category: "infantry", pct: 5 }],
          },
          {
            order: 9,
            name: "標準制式",
            description: "武器標準化制式生產，補給訓練皆一致。",
            baseCost: 277,
            effects: [],
          },
          {
            order: 10,
            name: "兵工廠制",
            description: "建立兵工廠量產軍械，軍需自給自足。",
            baseCost: 302,
            effects: [],
          },
        ],
      },
      {
        lineKey: "railway",
        lineLabel: "鐵路後勤",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "蒸汽機車",
            description: "蒸汽機車牽引重載，運兵運糧一日千里。",
            baseCost: 76,
            effects: [],
          },
          {
            order: 2,
            name: "軍用鐵道",
            description: "鋪設軍用鐵道，兵員物資快速前送。",
            baseCost: 101,
            effects: [],
          },
          {
            order: 3,
            name: "電報通訊",
            description: "架設電報線傳令，軍情瞬息可達千里。",
            baseCost: 126,
            effects: [],
          },
          {
            order: 4,
            name: "動員時刻",
            description: "編製動員時刻表，大軍集結分秒不差。",
            baseCost: 151,
            effects: [],
          },
          {
            order: 5,
            name: "鐵路調度",
            description: "統籌鐵路調度運力，兵運補運兩不誤。",
            baseCost: 176,
            effects: [],
          },
          {
            order: 6,
            name: "補給樞紐",
            description: "設鐵路補給樞紐轉運，前線源源不絕。",
            baseCost: 202,
            effects: [],
          },
          {
            order: 7,
            name: "裝甲列車",
            description: "披甲裝砲的列車巡弋鐵道，守護運輸線。",
            baseCost: 227,
            effects: [],
          },
          {
            order: 8,
            name: "快速動員",
            description: "鐵路快速動員部隊，全軍機動速度提升。",
            baseCost: 252,
            effects: [{ target: "speed", category: null, pct: 5 }],
          },
          {
            order: 9,
            name: "後勤網絡",
            description: "鐵路公路交織成網，補給觸及各戰線。",
            baseCost: 277,
            effects: [],
          },
          {
            order: 10,
            name: "總動員制",
            description: "建立總動員體制，舉國之力投入戰爭。",
            baseCost: 302,
            effects: [],
          },
        ],
      },
      {
        lineKey: "navy",
        lineLabel: "鐵甲艦隊",
        lineKind: "branch",
        branchFrom: { lineKey: "firearms", order: 3 },
        nodes: [
          {
            order: 1,
            name: "蒸汽鐵甲",
            description: "蒸汽為動力披鐵甲，戰艦不畏舷砲。",
            baseCost: 60,
            effects: [],
          },
          {
            order: 2,
            name: "旋轉砲塔",
            description: "艦上裝旋轉砲塔，火砲可轉向四方。",
            baseCost: 91,
            effects: [],
          },
          {
            order: 3,
            name: "裝甲艦體",
            description: "加厚裝甲護體，戰船耐久顯著提升。",
            baseCost: 121,
            effects: [{ target: "hp", category: "ship", pct: 5 }],
          },
          {
            order: 4,
            name: "無畏艦",
            description: "全裝重砲的無畏艦問世，主宰海上會戰。",
            baseCost: 151,
            effects: [],
          },
        ],
      },
    ],
  },
  {
    eraSlug: "ww1",
    lines: [
      {
        lineKey: "aviation",
        lineLabel: "軍用航空",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "偵察氣球",
            description: "升空氣球俯瞰戰場，觀測敵情校正砲擊。",
            baseCost: 78,
            effects: [],
          },
          {
            order: 2,
            name: "木製雙翼機",
            description: "木骨蒙布的雙翼機升空，開啟航空時代。",
            baseCost: 104,
            effects: [],
          },
          {
            order: 3,
            name: "空中偵察",
            description: "飛機翱翔敵後偵照，情報一覽無遺。",
            baseCost: 130,
            effects: [],
          },
          {
            order: 4,
            name: "機槍同步",
            description: "機槍與螺旋槳同步射擊，穿槳射敵無礙。",
            baseCost: 156,
            effects: [],
          },
          {
            order: 5,
            name: "空戰纏鬥",
            description: "戰機空中纏鬥格鬥，爭奪一方制空權。",
            baseCost: 182,
            effects: [],
          },
          {
            order: 6,
            name: "飛行器",
            description: "軍用飛行器成軍作戰，空中兵種攻擊提升。",
            baseCost: 260,
            effects: [{ target: "attack", category: "air", pct: 10 }],
            keySlug: "aviation",
          },
          {
            order: 7,
            name: "轟炸機隊",
            description: "編組轟炸機隊臨空投彈，打擊敵後縱深。",
            baseCost: 234,
            effects: [],
          },
          {
            order: 8,
            name: "戰鬥機群",
            description: "戰鬥機群協同空戰，空中兵種攻擊提升。",
            baseCost: 260,
            effects: [{ target: "attack", category: "air", pct: 5 }],
          },
          {
            order: 9,
            name: "空防警戒",
            description: "設對空觀哨與火砲，攔阻來襲的敵機。",
            baseCost: 286,
            effects: [],
          },
          {
            order: 10,
            name: "航空聯隊",
            description: "統合各型戰機成聯隊，掌控戰場天空。",
            baseCost: 312,
            effects: [],
          },
        ],
      },
      {
        lineKey: "trench",
        lineLabel: "塹壕戰術",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "塹壕挖掘",
            description: "掘壕溝掩蔽，抵禦砲火與機槍掃射。",
            baseCost: 78,
            effects: [],
          },
          {
            order: 2,
            name: "鐵絲網障",
            description: "布設鐵絲網障礙，遲滯敵軍衝鋒暴露火線。",
            baseCost: 104,
            effects: [],
          },
          {
            order: 3,
            name: "機槍火力點",
            description: "構築機槍火力點交叉封鎖，橫掃衝鋒之敵。",
            baseCost: 130,
            effects: [],
          },
          {
            order: 4,
            name: "毒氣攻擊",
            description: "施放毒氣瀰漫塹壕，逼敵棄守陣地。",
            baseCost: 156,
            effects: [],
          },
          {
            order: 5,
            name: "彈幕徐進",
            description: "砲火彈幕逐步前推，掩護步兵隨後突進。",
            baseCost: 182,
            effects: [],
          },
          {
            order: 6,
            name: "滲透突擊",
            description: "精銳突擊隊滲透薄弱點，繞後瓦解防線。",
            baseCost: 208,
            effects: [],
          },
          {
            order: 7,
            name: "坑道爆破",
            description: "挖坑道至敵陣下埋藥爆破，撼動堅固工事。",
            baseCost: 234,
            effects: [],
          },
          {
            order: 8,
            name: "縱深防禦",
            description: "多線縱深配置陣地，步兵防禦顯著提升。",
            baseCost: 260,
            effects: [{ target: "defense", category: "infantry", pct: 5 }],
          },
          {
            order: 9,
            name: "突擊工兵",
            description: "工兵攜爆破與火焰器材，破障清點突擊。",
            baseCost: 286,
            effects: [],
          },
          {
            order: 10,
            name: "陣地戰體系",
            description: "整合塹壕火力與縱深，成完整陣地防禦。",
            baseCost: 312,
            effects: [],
          },
        ],
      },
      {
        lineKey: "artillery",
        lineLabel: "重砲火力",
        lineKind: "branch",
        branchFrom: { lineKey: "trench", order: 3 },
        nodes: [
          {
            order: 1,
            name: "重型榴彈砲",
            description: "重型榴彈砲遠轟敵陣，摧毀堅固工事。",
            baseCost: 62,
            effects: [],
          },
          {
            order: 2,
            name: "列車巨砲",
            description: "巨砲架於列車機動，射程遠達敵後方。",
            baseCost: 94,
            effects: [],
          },
          {
            order: 3,
            name: "彈幕射擊",
            description: "以密集彈幕覆蓋目標區，砲兵攻擊提升。",
            baseCost: 125,
            effects: [{ target: "attack", category: "artillery", pct: 5 }],
          },
          {
            order: 4,
            name: "反砲兵戰",
            description: "測位敵砲予以壓制，奪取砲兵優勢。",
            baseCost: 156,
            effects: [],
          },
        ],
      },
    ],
  },
  {
    eraSlug: "ww2",
    lines: [
      {
        lineKey: "armor",
        lineLabel: "裝甲兵團",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "輕型戰車",
            description: "輕型戰車靈活突進，伴隨步兵衝鋒破陣。",
            baseCost: 95,
            effects: [],
          },
          {
            order: 2,
            name: "中型坦克",
            description: "中型坦克攻防兼備，成裝甲部隊的主力。",
            baseCost: 126,
            effects: [],
          },
          {
            order: 3,
            name: "履帶懸吊",
            description: "改良履帶懸吊，越野機動更為順暢。",
            baseCost: 158,
            effects: [],
          },
          {
            order: 4,
            name: "裝甲師編制",
            description: "編組裝甲師集中運用，鋼鐵洪流碾壓敵線。",
            baseCost: 189,
            effects: [],
          },
          {
            order: 5,
            name: "閃電戰術",
            description: "裝甲空軍協同奇襲，速戰速決穿透縱深。",
            baseCost: 221,
            effects: [],
          },
          {
            order: 6,
            name: "重型坦克",
            description: "重裝厚甲的重型坦克，正面難以擊穿。",
            baseCost: 252,
            effects: [],
          },
          {
            order: 7,
            name: "反坦克砲",
            description: "布設反坦克砲，穿甲彈擊毀來犯裝甲。",
            baseCost: 284,
            effects: [],
          },
          {
            order: 8,
            name: "傾斜裝甲",
            description: "採傾斜裝甲增彈跳，裝甲兵種防禦提升。",
            baseCost: 315,
            effects: [{ target: "defense", category: "armor", pct: 5 }],
          },
          {
            order: 9,
            name: "坦克殲擊車",
            description: "低矮殲擊車伏擊敵坦克，火力兇猛。",
            baseCost: 347,
            effects: [],
          },
          {
            order: 10,
            name: "裝甲兵團",
            description: "集結大批裝甲成兵團，主宰現代陸戰。",
            baseCost: 378,
            effects: [],
          },
        ],
      },
      {
        lineKey: "airforce",
        lineLabel: "空軍力量",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "全金屬機",
            description: "全金屬單翼戰機問世，飛速與載重俱增。",
            baseCost: 95,
            effects: [],
          },
          {
            order: 2,
            name: "俯衝轟炸機",
            description: "俯衝投彈精準命中，摧毀點狀目標。",
            baseCost: 126,
            effects: [],
          },
          {
            order: 3,
            name: "戰略轟炸",
            description: "遠程轟炸敵工業城市，削弱其戰爭潛力。",
            baseCost: 158,
            effects: [],
          },
          {
            order: 4,
            name: "雷達預警",
            description: "以雷達偵測來襲機群，及早升空攔截。",
            baseCost: 189,
            effects: [],
          },
          {
            order: 5,
            name: "空降傘兵",
            description: "傘兵空降敵後奇襲，奪取要點癱瘓防線。",
            baseCost: 221,
            effects: [],
          },
          {
            order: 6,
            name: "護航戰鬥機",
            description: "戰鬥機護航轟炸機群，掩護深入敵境。",
            baseCost: 252,
            effects: [],
          },
          {
            order: 7,
            name: "噴射引擎",
            description: "噴射引擎推進戰機，速度躍升領先群倫。",
            baseCost: 284,
            effects: [],
          },
          {
            order: 8,
            name: "地毯轟炸",
            description: "機群密集投彈覆蓋，空中兵種攻擊提升。",
            baseCost: 315,
            effects: [{ target: "attack", category: "air", pct: 5 }],
          },
          {
            order: 9,
            name: "制空爭奪",
            description: "集結戰機爭奪制空，掌握天空主動權。",
            baseCost: 347,
            effects: [],
          },
          {
            order: 10,
            name: "空軍司令部",
            description: "設空軍司令部統籌，統一調度全域空戰。",
            baseCost: 378,
            effects: [],
          },
        ],
      },
      {
        lineKey: "navy",
        lineLabel: "航母艦隊",
        lineKind: "branch",
        branchFrom: { lineKey: "armor", order: 3 },
        nodes: [
          {
            order: 1,
            name: "航空母艦",
            description: "航母搭載艦載機，將機場移至大洋之上。",
            baseCost: 76,
            effects: [],
          },
          {
            order: 2,
            name: "艦載機隊",
            description: "艦載機隊出擊，遠程打擊海空目標。",
            baseCost: 113,
            effects: [],
          },
          {
            order: 3,
            name: "聲納反潛",
            description: "以聲納偵測潛艇護航，戰船耐久提升。",
            baseCost: 151,
            effects: [{ target: "hp", category: "ship", pct: 5 }],
          },
          {
            order: 4,
            name: "特混艦隊",
            description: "編成特混艦隊多艦協同，投射龐大戰力。",
            baseCost: 189,
            effects: [],
          },
        ],
      },
    ],
  },
  {
    eraSlug: "cold_war",
    lines: [
      {
        lineKey: "missile",
        lineLabel: "飛彈武力",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "彈道飛彈",
            description: "以火箭推進彈道飛彈，遠程投射彈頭。",
            baseCost: 168,
            effects: [],
          },
          {
            order: 2,
            name: "地對空飛彈",
            description: "地對空飛彈升空攔截，擊落高空敵機。",
            baseCost: 224,
            effects: [],
          },
          {
            order: 3,
            name: "巡弋飛彈",
            description: "巡弋飛彈低空掠地飛行，精準命中目標。",
            baseCost: 280,
            effects: [],
          },
          {
            order: 4,
            name: "洲際飛彈",
            description: "洲際飛彈跨越大洋，威懾遠方敵國。",
            baseCost: 336,
            effects: [],
          },
          {
            order: 5,
            name: "核子彈頭",
            description: "飛彈裝載核彈頭，一擊毀滅整座城市。",
            baseCost: 392,
            effects: [],
          },
          {
            order: 6,
            name: "反艦飛彈",
            description: "反艦飛彈掠海突襲，擊沉大型戰艦。",
            baseCost: 448,
            effects: [],
          },
          {
            order: 7,
            name: "多彈頭",
            description: "一枚飛彈分導多彈頭，同時襲擊多目標。",
            baseCost: 504,
            effects: [],
          },
          {
            order: 8,
            name: "精確制導",
            description: "以慣導與雷達制導，全軍命中率提升。",
            baseCost: 560,
            effects: [{ target: "accuracy", category: null, pct: 5 }],
          },
          {
            order: 9,
            name: "飛彈預警",
            description: "設飛彈預警系統，及早察覺來襲攔截。",
            baseCost: 616,
            effects: [],
          },
          {
            order: 10,
            name: "戰略核武",
            description: "建立戰略核武庫，以相互威懾維持恐怖平衡。",
            baseCost: 672,
            effects: [],
          },
        ],
      },
      {
        lineKey: "electronics",
        lineLabel: "電子情報",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "電晶體無線電",
            description: "電晶體無線電輕巧可靠，通訊普及各級。",
            baseCost: 168,
            effects: [],
          },
          {
            order: 2,
            name: "雷達網",
            description: "布建雷達網監視空域，來襲目標無所遁形。",
            baseCost: 224,
            effects: [],
          },
          {
            order: 3,
            name: "電子偵察",
            description: "截收分析敵方電波，掌握其部署動向。",
            baseCost: 280,
            effects: [],
          },
          {
            order: 4,
            name: "訊號截收",
            description: "攔截並破譯敵通訊訊號，先知敵謀。",
            baseCost: 336,
            effects: [],
          },
          {
            order: 5,
            name: "電子干擾",
            description: "施放電子干擾癱瘓敵雷達與通訊。",
            baseCost: 392,
            effects: [],
          },
          {
            order: 6,
            name: "早期預警機",
            description: "空中預警機遠探目標，指揮攔截作戰。",
            baseCost: 448,
            effects: [],
          },
          {
            order: 7,
            name: "衛星偵照",
            description: "以偵察衛星俯瞰全球，情蒐無遠弗屆。",
            baseCost: 504,
            effects: [],
          },
          {
            order: 8,
            name: "資料鏈路",
            description: "以資料鏈共享戰場情資，空中兵種命中提升。",
            baseCost: 560,
            effects: [{ target: "accuracy", category: "air", pct: 5 }],
          },
          {
            order: 9,
            name: "指揮管制",
            description: "建立指揮管制中心，統合感測與火力。",
            baseCost: 616,
            effects: [],
          },
          {
            order: 10,
            name: "電子作戰",
            description: "以電子作戰奪取電磁優勢，制電磁權致勝。",
            baseCost: 672,
            effects: [],
          },
        ],
      },
      {
        lineKey: "navy",
        lineLabel: "核動力艦隊",
        lineKind: "branch",
        branchFrom: { lineKey: "missile", order: 3 },
        nodes: [
          {
            order: 1,
            name: "核動力潛艇",
            description: "核動力潛艇長潛不浮，續航無所限制。",
            baseCost: 134,
            effects: [],
          },
          {
            order: 2,
            name: "潛射飛彈",
            description: "潛艇水下發射飛彈，隱蔽威懾難以偵知。",
            baseCost: 202,
            effects: [],
          },
          {
            order: 3,
            name: "神盾系統",
            description: "神盾系統統合防空，戰艦防禦顯著提升。",
            baseCost: 269,
            effects: [{ target: "defense", category: "ship", pct: 5 }],
          },
          {
            order: 4,
            name: "航母戰鬥群",
            description: "以航母為核心編成戰鬥群，投射遠洋戰力。",
            baseCost: 336,
            effects: [],
          },
        ],
      },
    ],
  },
  {
    eraSlug: "modern",
    lines: [
      {
        lineKey: "precision",
        lineLabel: "精準打擊",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "衛星定位導引",
            description: "以衛星定位導引彈藥，落點誤差以公尺計。",
            baseCost: 375,
            effects: [],
          },
          {
            order: 2,
            name: "精靈炸彈",
            description: "雷射導引精靈炸彈，指哪打哪一擊即中。",
            baseCost: 500,
            effects: [],
          },
          {
            order: 3,
            name: "匿蹤戰機",
            description: "匿蹤戰機規避雷達，神出鬼沒突穿防空。",
            baseCost: 625,
            effects: [],
          },
          {
            order: 4,
            name: "巡弋打擊",
            description: "以巡弋飛彈遠程外科打擊，精拔敵要害。",
            baseCost: 750,
            effects: [],
          },
          {
            order: 5,
            name: "夜視作戰",
            description: "配備夜視裝備，暗夜之中仍能精準交戰。",
            baseCost: 875,
            effects: [],
          },
          {
            order: 6,
            name: "主力戰車",
            description: "現代主力戰車攻防機動兼優，稱雄陸戰。",
            baseCost: 1000,
            effects: [],
          },
          {
            order: 7,
            name: "攻擊直升機",
            description: "攻擊直升機掠地獵殺，反裝甲火力兇猛。",
            baseCost: 1125,
            effects: [],
          },
          {
            order: 8,
            name: "複合裝甲",
            description: "採複合裝甲抗穿抵爆，裝甲兵種防禦提升。",
            baseCost: 1250,
            effects: [{ target: "defense", category: "armor", pct: 5 }],
          },
          {
            order: 9,
            name: "聯合火力",
            description: "陸海空聯合火力協同，多維打擊敵目標。",
            baseCost: 1375,
            effects: [],
          },
          {
            order: 10,
            name: "精準戰爭",
            description: "以精準武器主導戰爭，最小代價達成目標。",
            baseCost: 1500,
            effects: [],
          },
        ],
      },
      {
        lineKey: "cyber",
        lineLabel: "資訊戰",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "數位通訊",
            description: "數位加密通訊快捷保密，指揮暢通無阻。",
            baseCost: 375,
            effects: [],
          },
          {
            order: 2,
            name: "戰場網路",
            description: "建構戰場資訊網路，各單位即時聯通共享。",
            baseCost: 500,
            effects: [],
          },
          {
            order: 3,
            name: "網路攻防",
            description: "以網路攻防滲透敵系統，癱瘓其指揮。",
            baseCost: 625,
            effects: [],
          },
          {
            order: 4,
            name: "電磁頻譜",
            description: "掌控電磁頻譜，壓制干擾敵之感測通訊。",
            baseCost: 750,
            effects: [],
          },
          {
            order: 5,
            name: "資訊融合",
            description: "融合多源情資成態勢圖，決策一目了然。",
            baseCost: 875,
            effects: [],
          },
          {
            order: 6,
            name: "無人偵察",
            description: "無人機長時滯空偵察，持續監視戰場。",
            baseCost: 1000,
            effects: [],
          },
          {
            order: 7,
            name: "衛星導航",
            description: "以衛星導航定位授時，全軍協同精準。",
            baseCost: 1125,
            effects: [],
          },
          {
            order: 8,
            name: "即時情資",
            description: "即時傳遞戰場情資，全軍命中率提升。",
            baseCost: 1250,
            effects: [{ target: "accuracy", category: null, pct: 5 }],
          },
          {
            order: 9,
            name: "指管通情",
            description: "整合指管通情監偵，構成完整作戰體系。",
            baseCost: 1375,
            effects: [],
          },
          {
            order: 10,
            name: "資訊優勢",
            description: "以資訊優勢主導戰局，先敵決策先敵行動。",
            baseCost: 1500,
            effects: [],
          },
        ],
      },
      {
        lineKey: "drone",
        lineLabel: "無人系統",
        lineKind: "branch",
        branchFrom: { lineKey: "precision", order: 3 },
        nodes: [
          {
            order: 1,
            name: "察打無人機",
            description: "察打一體無人機偵察即打擊，滯空獵殺。",
            baseCost: 300,
            effects: [],
          },
          {
            order: 2,
            name: "無人地面車",
            description: "無人地面載具代人涉險，偵蒐排爆運補。",
            baseCost: 450,
            effects: [],
          },
          {
            order: 3,
            name: "蜂群協同",
            description: "無人機蜂群協同飽和攻擊，空中兵種攻擊提升。",
            baseCost: 600,
            effects: [{ target: "attack", category: "air", pct: 5 }],
          },
          {
            order: 4,
            name: "自主導引",
            description: "彈藥具自主導引尋標，發射後不理自尋目標。",
            baseCost: 750,
            effects: [],
          },
        ],
      },
    ],
  },
  {
    eraSlug: "future",
    lines: [
      {
        lineKey: "energy",
        lineLabel: "能量武器",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "雷射砲",
            description: "高能雷射光束灼穿目標，光速命中無從閃避。",
            baseCost: 986,
            effects: [],
          },
          {
            order: 2,
            name: "電磁軌道砲",
            description: "電磁軌道砲加速彈丸，超高速動能穿甲。",
            baseCost: 1314,
            effects: [],
          },
          {
            order: 3,
            name: "粒子束武器",
            description: "發射高能粒子束，貫穿裝甲毀壞電子。",
            baseCost: 1643,
            effects: [],
          },
          {
            order: 4,
            name: "電漿護盾",
            description: "以電漿場護盾偏折來襲能量，護體無虞。",
            baseCost: 1971,
            effects: [],
          },
          {
            order: 5,
            name: "定向能防禦",
            description: "定向能武器攔截來襲飛彈，光速反擊。",
            baseCost: 2300,
            effects: [],
          },
          {
            order: 6,
            name: "高能微波",
            description: "以高能微波癱瘓敵電子與人員，無形制敵。",
            baseCost: 2628,
            effects: [],
          },
          {
            order: 7,
            name: "動能攔截",
            description: "以動能撞擊摧毀來襲彈頭，直擊即毀。",
            baseCost: 2957,
            effects: [],
          },
          {
            order: 8,
            name: "能量裝甲",
            description: "披覆能量護場裝甲，全軍防禦顯著提升。",
            baseCost: 3285,
            effects: [{ target: "defense", category: null, pct: 5 }],
          },
          {
            order: 9,
            name: "反物質彈頭",
            description: "反物質湮滅釋出巨能，威力遠超核武。",
            baseCost: 3614,
            effects: [],
          },
          {
            order: 10,
            name: "能量戰爭",
            description: "以能量武器主宰戰場，物理疆界近乎消弭。",
            baseCost: 3942,
            effects: [],
          },
        ],
      },
      {
        lineKey: "autonomous",
        lineLabel: "自主戰爭",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "戰鬥機器人",
            description: "自主戰鬥機器人代人赴戰，不知疲懼傷亡。",
            baseCost: 986,
            effects: [],
          },
          {
            order: 2,
            name: "智械指揮官",
            description: "人工智慧輔助指揮，瞬息運算最優戰法。",
            baseCost: 1314,
            effects: [],
          },
          {
            order: 3,
            name: "自主載具",
            description: "無人載具自主機動作戰，遍佈陸海空各域。",
            baseCost: 1643,
            effects: [],
          },
          {
            order: 4,
            name: "神經介面",
            description: "以神經介面直連指揮，念動之間號令三軍。",
            baseCost: 1971,
            effects: [],
          },
          {
            order: 5,
            name: "量子通訊",
            description: "量子通訊即時保密無法竊聽，指揮絕對安全。",
            baseCost: 2300,
            effects: [],
          },
          {
            order: 6,
            name: "奈米修復",
            description: "奈米機群自動修復裝備與傷患，戰力速還。",
            baseCost: 2628,
            effects: [],
          },
          {
            order: 7,
            name: "外骨骼裝甲",
            description: "動力外骨骼倍增士兵力量與防護，如超人臨陣。",
            baseCost: 2957,
            effects: [],
          },
          {
            order: 8,
            name: "群體智能",
            description: "無人單位群體智能協同，全軍機動速度提升。",
            baseCost: 3285,
            effects: [{ target: "speed", category: null, pct: 5 }],
          },
          {
            order: 9,
            name: "全域監控",
            description: "布建全域感測監控，戰場態勢無所不知。",
            baseCost: 3614,
            effects: [],
          },
          {
            order: 10,
            name: "智能戰場",
            description: "感測火力自主聯動的智能戰場，決勝於瞬息。",
            baseCost: 3942,
            effects: [],
          },
        ],
      },
      {
        lineKey: "space",
        lineLabel: "太空戰力",
        lineKind: "branch",
        branchFrom: { lineKey: "energy", order: 3 },
        nodes: [
          {
            order: 1,
            name: "軌道衛星",
            description: "部署軍用軌道衛星，偵照通訊授時一體。",
            baseCost: 788,
            effects: [],
          },
          {
            order: 2,
            name: "太空戰機",
            description: "太空戰機遊弋軌道，爭奪外太空制天權。",
            baseCost: 1183,
            effects: [],
          },
          {
            order: 3,
            name: "軌道打擊",
            description: "自軌道投射動能棒襲地，全軍攻擊力提升。",
            baseCost: 1577,
            effects: [{ target: "attack", category: null, pct: 5 }],
          },
          {
            order: 4,
            name: "太空艦隊",
            description: "組建太空艦隊掌控軌道，將戰場擴及星海。",
            baseCost: 1971,
            effects: [],
          },
        ],
      },
    ],
  },
];
