// Task #469 — 科技樹預設種子（military 領域，前半）

import type { MilitaryTechBonus } from "@workspace/db";
import type { TechTreeSeedEra } from "./types";

export const MILITARY_ERAS_EARLY: TechTreeSeedEra<MilitaryTechBonus>[] = [
  {
    eraSlug: "classical",
    lines: [
      {
        lineKey: "weapons",
        lineLabel: "兵器與火力",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "青銅兵刃",
            description: "以青銅澆鑄鋒利刀劍，開啟金屬兵器的時代。",
            baseCost: 6,
            effects: [{ target: "attack", category: "infantry", pct: 4 }],
          },
          {
            order: 2,
            name: "複合弓",
            description: "以筋角木層疊而成的強弓，射程與穿透力大增。",
            baseCost: 8,
            effects: [{ target: "attack", category: "ranged", pct: 4 }],
          },
          {
            order: 3,
            name: "投石索",
            description: "牧人以皮索甩石為兵，遠距投射廉價而致命。",
            baseCost: 10,
            effects: [{ target: "attack", category: "ranged", pct: 4 }],
          },
          {
            order: 4,
            name: "標槍術",
            description: "訓練士卒投擲短矛，衝鋒前先破敵陣盾牆。",
            baseCost: 12,
            effects: [{ target: "attack", category: "infantry", pct: 4 }],
          },
          {
            order: 5,
            name: "弩機初製",
            description: "以機括蓄力發矢，尋常兵卒亦能穿透重甲。",
            baseCost: 14,
            effects: [{ target: "attack", category: "ranged", pct: 4 }],
          },
          {
            order: 6,
            name: "射擊",
            description: "弓弩齊射之術漸成體系，命中大增並解鎖射手。",
            baseCost: 20,
            effects: [{ target: "accuracy", category: "ranged", pct: 20 }],
            keySlug: "marksmanship",
          },
          {
            order: 7,
            name: "連弩",
            description: "改良弩機可連續發矢，齊射如驟雨壓制敵陣。",
            baseCost: 18,
            effects: [{ target: "attack", category: "ranged", pct: 4 }],
          },
          {
            order: 8,
            name: "攻城弩砲",
            description: "巨型弩砲射出粗矢石彈，遠射兵種威力提升。",
            baseCost: 20,
            effects: [{ target: "attack", category: "ranged", pct: 5 }],
          },
          {
            order: 9,
            name: "火攻箭",
            description: "箭頭裹油點燃射出，焚敵營帳與攻城器械。",
            baseCost: 22,
            effects: [{ target: "attack", category: "siege", pct: 4 }],
          },
          {
            order: 10,
            name: "重裝弓陣",
            description: "披甲弓手列陣輪射，成為戰場的遠程支柱。",
            baseCost: 24,
            effects: [{ target: "defense", category: "ranged", pct: 4 }],
          },
        ],
      },
      {
        lineKey: "formation",
        lineLabel: "戰術與編制",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "方陣戰術",
            description: "長矛手密集列陣，以整齊隊形抵禦衝擊。",
            baseCost: 6,
            effects: [{ target: "defense", category: "infantry", pct: 4 }],
          },
          {
            order: 2,
            name: "重步兵陣",
            description: "披甲重兵持大盾成牆，正面難以撼動。",
            baseCost: 8,
            effects: [{ target: "defense", category: "infantry", pct: 4 }],
          },
          {
            order: 3,
            name: "散兵掩護",
            description: "輕裝散兵游走陣前，騷擾遲滯敵軍推進。",
            baseCost: 10,
            effects: [{ target: "speed", category: "infantry", pct: 4 }],
          },
          {
            order: 4,
            name: "側翼包抄",
            description: "以機動部隊繞擊敵側，瓦解其戰線。",
            baseCost: 12,
            effects: [{ target: "attack", category: "infantry", pct: 4 }],
          },
          {
            order: 5,
            name: "軍號指揮",
            description: "以號角鼓聲傳令，戰陣得以協調進退。",
            baseCost: 14,
            effects: [{ target: "speed", category: null, pct: 3 }],
          },
          {
            order: 6,
            name: "預備隊制",
            description: "保留生力軍待機投入，扭轉戰局關鍵時刻。",
            baseCost: 16,
            effects: [{ target: "recoveryRate", category: null, pct: 3 }],
          },
          {
            order: 7,
            name: "楔形突擊",
            description: "以尖銳楔陣集中衝擊，撕裂敵軍中央。",
            baseCost: 18,
            effects: [{ target: "attack", category: "infantry", pct: 4 }],
          },
          {
            order: 8,
            name: "龜甲陣",
            description: "士卒以盾牌覆蓋四方，步兵防禦大幅提升。",
            baseCost: 20,
            effects: [{ target: "defense", category: "infantry", pct: 5 }],
          },
          {
            order: 9,
            name: "梯隊縱深",
            description: "多線梯次配置兵力，前線潰散仍能續戰。",
            baseCost: 22,
            effects: [{ target: "defense", category: null, pct: 3 }],
          },
          {
            order: 10,
            name: "統帥韜略",
            description: "名將運籌帷幄，以謀略統御大軍決勝。",
            baseCost: 24,
            effects: [{ target: "attack", category: null, pct: 3 }],
          },
        ],
      },
      {
        lineKey: "fortification",
        lineLabel: "防禦工事",
        lineKind: "branch",
        branchFrom: { lineKey: "weapons", order: 3 },
        nodes: [
          {
            order: 1,
            name: "木柵營壘",
            description: "行軍紮營以木柵環護，防範夜襲騷擾。",
            baseCost: 5,
            effects: [{ target: "defense", category: "infantry", pct: 3 }],
          },
          {
            order: 2,
            name: "壕溝拒馬",
            description: "掘溝設拒馬阻敵，遲滯騎兵與步兵衝鋒。",
            baseCost: 7,
            effects: [{ target: "defense", category: "infantry", pct: 3 }],
          },
          {
            order: 3,
            name: "石砌城垣",
            description: "以石塊砌築堅厚城牆，全軍防禦顯著增強。",
            baseCost: 10,
            effects: [{ target: "defense", category: null, pct: 5 }],
          },
          {
            order: 4,
            name: "箭樓哨塔",
            description: "城角築高塔設弓手，居高瞭望與射擊。",
            baseCost: 12,
            effects: [{ target: "accuracy", category: "ranged", pct: 3 }],
          },
        ],
      },
    ],
  },
  {
    eraSlug: "roman",
    lines: [
      {
        lineKey: "navy",
        lineLabel: "海軍艦隊",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "槳帆戰船",
            description: "以人力划槳輔以風帆，戰船得以縱橫近海。",
            baseCost: 10,
            effects: [{ target: "hp", category: "ship", pct: 4 }],
          },
          {
            order: 2,
            name: "撞角戰術",
            description: "船首裝銅撞角，全速衝擊撞沉敵艦。",
            baseCost: 13,
            effects: [{ target: "attack", category: "ship", pct: 4 }],
          },
          {
            order: 3,
            name: "艨艟樓船",
            description: "多層甲板的大型戰船，可載更多兵員作戰。",
            baseCost: 17,
            effects: [{ target: "hp", category: "ship", pct: 4 }],
          },
          {
            order: 4,
            name: "接舷跳幫",
            description: "以吊橋搭接敵艦，海戰化為甲板肉搏。",
            baseCost: 20,
            effects: [{ target: "attack", category: "ship", pct: 4 }],
          },
          {
            order: 5,
            name: "港灣船塢",
            description: "興建船塢維修艦隊，確保海上戰力持久。",
            baseCost: 24,
            effects: [{ target: "recoverySpeed", category: "ship", pct: 4 }],
          },
          {
            order: 6,
            name: "海戰",
            description: "艦隊會戰之術漸成體系，戰船耐久大幅提升。",
            baseCost: 34,
            effects: [{ target: "hp", category: "ship", pct: 10 }],
            keySlug: "naval_warfare",
          },
          {
            order: 7,
            name: "三列槳座",
            description: "三層槳手同划，戰船航速與衝力倍增。",
            baseCost: 30,
            effects: [{ target: "speed", category: "ship", pct: 4 }],
          },
          {
            order: 8,
            name: "艦載弩砲",
            description: "戰船甲板架設弩砲，海上遠程火力大增。",
            baseCost: 34,
            effects: [{ target: "attack", category: "ship", pct: 5 }],
          },
          {
            order: 9,
            name: "火油噴射",
            description: "艦首噴射燃油縱火，焚毀逼近的敵船。",
            baseCost: 37,
            effects: [{ target: "attack", category: "ship", pct: 4 }],
          },
          {
            order: 10,
            name: "艦隊會戰",
            description: "統合大批戰船列陣，於海上決一勝負。",
            baseCost: 40,
            effects: [{ target: "attack", category: "ship", pct: 5 }],
          },
        ],
      },
      {
        lineKey: "legion",
        lineLabel: "軍團編制",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "軍團百人隊",
            description: "以百人隊為基幹編組軍團，指揮井然有序。",
            baseCost: 10,
            effects: [{ target: "attack", category: "infantry", pct: 4 }],
          },
          {
            order: 2,
            name: "標槍重投",
            description: "衝鋒前齊擲重標槍，破敵盾陣再拔劍相搏。",
            baseCost: 13,
            effects: [{ target: "attack", category: "infantry", pct: 4 }],
          },
          {
            order: 3,
            name: "短劍格鬥",
            description: "以短劍近身刺擊，密集陣中揮灑自如。",
            baseCost: 17,
            effects: [{ target: "attack", category: "infantry", pct: 4 }],
          },
          {
            order: 4,
            name: "鷹旗軍徽",
            description: "軍團奉鷹旗為榮譽，凝聚士氣誓死護旗。",
            baseCost: 20,
            effects: [{ target: "defense", category: "infantry", pct: 4 }],
          },
          {
            order: 5,
            name: "築營行軍",
            description: "每日行軍後築設營寨，安營如移動要塞。",
            baseCost: 24,
            effects: [{ target: "defense", category: null, pct: 3 }],
          },
          {
            order: 6,
            name: "輪替陣線",
            description: "前排疲則後排替換，戰線持久不衰。",
            baseCost: 27,
            effects: [{ target: "recoveryRate", category: "infantry", pct: 4 }],
          },
          {
            order: 7,
            name: "工兵築橋",
            description: "軍團工兵架橋開路，大軍暢行無阻。",
            baseCost: 30,
            effects: [{ target: "speed", category: null, pct: 4 }],
          },
          {
            order: 8,
            name: "龜甲盾陣",
            description: "全隊盾牌上覆結陣，步兵防禦顯著提升。",
            baseCost: 34,
            effects: [{ target: "defense", category: "infantry", pct: 5 }],
          },
          {
            order: 9,
            name: "邊境軍團",
            description: "常駐邊塞的軍團，戍衛疆界抵禦外患。",
            baseCost: 37,
            effects: [{ target: "defense", category: "infantry", pct: 4 }],
          },
          {
            order: 10,
            name: "軍團統帥",
            description: "軍團統帥號令三軍，指揮大兵團作戰。",
            baseCost: 40,
            effects: [{ target: "attack", category: null, pct: 4 }],
          },
        ],
      },
      {
        lineKey: "logistics",
        lineLabel: "後勤軍制",
        lineKind: "branch",
        branchFrom: { lineKey: "legion", order: 3 },
        nodes: [
          {
            order: 1,
            name: "軍糧倉廩",
            description: "沿途設倉囤糧，確保大軍餉食無虞。",
            baseCost: 8,
            effects: [{ target: "foodConsumption", category: null, pct: -3 }],
          },
          {
            order: 2,
            name: "驛道補給",
            description: "修築軍用大道傳遞糧秣，補給迅捷。",
            baseCost: 12,
            effects: [{ target: "speed", category: null, pct: 3 }],
          },
          {
            order: 3,
            name: "軍餉制度",
            description: "以固定軍餉養兵，維持成本得以撙節。",
            baseCost: 16,
            effects: [{ target: "upkeep", category: null, pct: -5 }],
          },
          {
            order: 4,
            name: "退伍田授",
            description: "老兵退役授予田產，激勵從軍報國之志。",
            baseCost: 20,
            effects: [{ target: "upkeep", category: null, pct: -3 }],
          },
        ],
      },
    ],
  },
  {
    eraSlug: "early_medieval",
    lines: [
      {
        lineKey: "cavalry",
        lineLabel: "騎兵戰術",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "馬鐙革新",
            description: "馬鐙令騎士穩坐鞍上，衝鋒揮擊更為有力。",
            baseCost: 14,
            effects: [{ target: "attack", category: "armor", pct: 4 }],
          },
          {
            order: 2,
            name: "重騎衝鋒",
            description: "披甲重騎集結衝陣，如鐵潮碾碎敵行。",
            baseCost: 18,
            effects: [{ target: "attack", category: "armor", pct: 5 }],
          },
          {
            order: 3,
            name: "輕騎游擊",
            description: "輕騎往來襲擾，斷敵糧道擾其後方。",
            baseCost: 23,
            effects: [{ target: "speed", category: "armor", pct: 4 }],
          },
          {
            order: 4,
            name: "騎槍突刺",
            description: "夾持長槍全速衝刺，一擊洞穿敵甲。",
            baseCost: 27,
            effects: [{ target: "attack", category: "armor", pct: 4 }],
          },
          {
            order: 5,
            name: "鎖子甲騎",
            description: "騎士披鎖環甲，兼顧防護與機動。",
            baseCost: 32,
            effects: [{ target: "defense", category: "armor", pct: 4 }],
          },
          {
            order: 6,
            name: "弓騎射術",
            description: "馬上開弓騎射，游走間箭無虛發。",
            baseCost: 36,
            effects: [{ target: "accuracy", category: "armor", pct: 4 }],
          },
          {
            order: 7,
            name: "楔形騎陣",
            description: "騎兵結楔形陣衝擊，集中撕開敵陣缺口。",
            baseCost: 41,
            effects: [{ target: "attack", category: "armor", pct: 4 }],
          },
          {
            order: 8,
            name: "側翼騎襲",
            description: "騎兵繞擊敵側背，裝甲兵種攻擊提升。",
            baseCost: 45,
            effects: [{ target: "attack", category: "armor", pct: 5 }],
          },
          {
            order: 9,
            name: "具裝馬鎧",
            description: "戰馬披掛重鎧，人馬俱甲難以撼動。",
            baseCost: 50,
            effects: [{ target: "hp", category: "armor", pct: 5 }],
          },
          {
            order: 10,
            name: "騎士團制",
            description: "組建騎士團為精銳核心，稱雄於戰場。",
            baseCost: 54,
            effects: [{ target: "attack", category: "armor", pct: 5 }],
          },
        ],
      },
      {
        lineKey: "fortification",
        lineLabel: "城防工事",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "土壘城寨",
            description: "堆築土壘環寨，於險要處據守一方。",
            baseCost: 14,
            effects: [{ target: "defense", category: "infantry", pct: 4 }],
          },
          {
            order: 2,
            name: "木造塔樓",
            description: "以木料搭建高塔，瞭望警戒扼守要道。",
            baseCost: 18,
            effects: [{ target: "accuracy", category: "ranged", pct: 4 }],
          },
          {
            order: 3,
            name: "護城河渠",
            description: "環城掘渠引水，阻隔攻城器械逼近。",
            baseCost: 23,
            effects: [{ target: "defense", category: null, pct: 3 }],
          },
          {
            order: 4,
            name: "石造主堡",
            description: "以石構築堅固主堡，成為據點的核心。",
            baseCost: 27,
            effects: [{ target: "defense", category: "infantry", pct: 4 }],
          },
          {
            order: 5,
            name: "吊橋閘門",
            description: "設吊橋鐵閘控制出入，堵絕敵軍強闖。",
            baseCost: 32,
            effects: [{ target: "defense", category: "infantry", pct: 4 }],
          },
          {
            order: 6,
            name: "城垛箭孔",
            description: "牆頭築城垛開箭孔，守軍得以掩體放箭。",
            baseCost: 36,
            effects: [{ target: "accuracy", category: "ranged", pct: 4 }],
          },
          {
            order: 7,
            name: "甕城結構",
            description: "城門外築甕城，誘敵入內甕中捉鱉。",
            baseCost: 41,
            effects: [{ target: "defense", category: null, pct: 3 }],
          },
          {
            order: 8,
            name: "環形城牆",
            description: "多重環牆層層設防，全軍防禦顯著增強。",
            baseCost: 45,
            effects: [{ target: "defense", category: null, pct: 5 }],
          },
          {
            order: 9,
            name: "角樓稜台",
            description: "城角築稜台交叉射擊，消弭防守死角。",
            baseCost: 50,
            effects: [{ target: "accuracy", category: "ranged", pct: 4 }],
          },
          {
            order: 10,
            name: "山城要塞",
            description: "依山勢築成堅城要塞，易守而難攻。",
            baseCost: 54,
            effects: [{ target: "defense", category: null, pct: 4 }],
          },
        ],
      },
      {
        lineKey: "weapons",
        lineLabel: "兵器鍛造",
        lineKind: "branch",
        branchFrom: { lineKey: "cavalry", order: 3 },
        nodes: [
          {
            order: 1,
            name: "淬火鋼刃",
            description: "以淬火法鍛鋼，刀劍更堅韌鋒利。",
            baseCost: 11,
            effects: [{ target: "attack", category: "infantry", pct: 3 }],
          },
          {
            order: 2,
            name: "板甲鍛造",
            description: "鍛打整片鋼板護身，防護遠勝鎖環。",
            baseCost: 16,
            effects: [{ target: "defense", category: "infantry", pct: 3 }],
          },
          {
            order: 3,
            name: "長柄斧鉞",
            description: "揮舞長柄重斧破甲，步兵攻擊力提升。",
            baseCost: 22,
            effects: [{ target: "attack", category: "infantry", pct: 5 }],
          },
          {
            order: 4,
            name: "十字弓弩",
            description: "改良十字弩張力更強，穿甲致命。",
            baseCost: 27,
            effects: [{ target: "attack", category: "ranged", pct: 3 }],
          },
        ],
      },
    ],
  },
  {
    eraSlug: "high_medieval",
    lines: [
      {
        lineKey: "artillery",
        lineLabel: "攻城火器",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "投石機",
            description: "以扭力拋擲石彈，破壞敵城牆與器械。",
            baseCost: 19,
            effects: [{ target: "attack", category: "artillery", pct: 4 }],
          },
          {
            order: 2,
            name: "配重拋石機",
            description: "以巨大配重擲出重石，攻城威力驚人。",
            baseCost: 26,
            effects: [{ target: "attack", category: "artillery", pct: 5 }],
          },
          {
            order: 3,
            name: "攻城塔",
            description: "推移木製高塔逼近城牆，兵員登城強攻。",
            baseCost: 32,
            effects: [{ target: "hp", category: "siege", pct: 5 }],
          },
          {
            order: 4,
            name: "破城槌",
            description: "以巨木包鐵撞擊城門，強行破關而入。",
            baseCost: 38,
            effects: [{ target: "attack", category: "siege", pct: 5 }],
          },
          {
            order: 5,
            name: "希臘火筒",
            description: "以噴筒射出黏稠烈火，遇水難滅。",
            baseCost: 45,
            effects: [{ target: "attack", category: "artillery", pct: 5 }],
          },
          {
            order: 6,
            name: "火藥",
            description: "黑火藥用於戰陣，攻城兵器攻擊大幅提升。",
            baseCost: 64,
            effects: [{ target: "attack", category: "artillery", pct: 20 }],
            keySlug: "gunpowder",
          },
          {
            order: 7,
            name: "原始火砲",
            description: "以鐵筒填火藥發石彈，火器登上戰場。",
            baseCost: 58,
            effects: [{ target: "attack", category: "artillery", pct: 5 }],
          },
          {
            order: 8,
            name: "鑄鐵砲管",
            description: "鑄鐵砲管耐壓耐熱，攻城火砲威力提升。",
            baseCost: 64,
            effects: [{ target: "attack", category: "artillery", pct: 5 }],
          },
          {
            order: 9,
            name: "石彈砲擊",
            description: "以火砲拋射石彈，遠距轟塌城垣。",
            baseCost: 70,
            effects: [{ target: "accuracy", category: "artillery", pct: 5 }],
          },
          {
            order: 10,
            name: "攻城砲隊",
            description: "編組專責攻城的砲隊，集火摧毀堅城。",
            baseCost: 77,
            effects: [{ target: "attack", category: "artillery", pct: 5 }],
          },
        ],
      },
      {
        lineKey: "infantry",
        lineLabel: "步兵陣列",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "長矛方陣",
            description: "長矛手密集列陣，矛尖如林拒退騎兵。",
            baseCost: 19,
            effects: [{ target: "defense", category: "infantry", pct: 5 }],
          },
          {
            order: 2,
            name: "持盾重兵",
            description: "重步兵持大盾結牆，正面堅不可摧。",
            baseCost: 26,
            effects: [{ target: "defense", category: "infantry", pct: 5 }],
          },
          {
            order: 3,
            name: "長弓兵團",
            description: "長弓手齊射如雨，遠距壓制敵騎與步卒。",
            baseCost: 32,
            effects: [{ target: "attack", category: "ranged", pct: 5 }],
          },
          {
            order: 4,
            name: "十字弩隊",
            description: "弩手輪番裝填齊發，穿透重甲敵陣。",
            baseCost: 38,
            effects: [{ target: "accuracy", category: "ranged", pct: 5 }],
          },
          {
            order: 5,
            name: "戟兵編組",
            description: "以長戟兼具鉤刺，拉墜騎士破其衝鋒。",
            baseCost: 45,
            effects: [{ target: "attack", category: "infantry", pct: 5 }],
          },
          {
            order: 6,
            name: "城市民兵",
            description: "徵召市民組成民兵，守衛家園補充兵源。",
            baseCost: 51,
            effects: [{ target: "upkeep", category: "infantry", pct: -5 }],
          },
          {
            order: 7,
            name: "傭兵長矛",
            description: "雇用職業長矛傭兵，戰技嫻熟令行禁止。",
            baseCost: 58,
            effects: [{ target: "attack", category: "infantry", pct: 5 }],
          },
          {
            order: 8,
            name: "空心方陣",
            description: "步兵結空心方陣四面防禦，抵禦環攻。",
            baseCost: 64,
            effects: [{ target: "defense", category: "infantry", pct: 5 }],
          },
          {
            order: 9,
            name: "混編步陣",
            description: "長矛弓弩混編列陣，攻守相濟互為掩護。",
            baseCost: 70,
            effects: [{ target: "defense", category: null, pct: 4 }],
          },
          {
            order: 10,
            name: "步兵統率",
            description: "以嚴明軍紀統率步軍，臨陣進退如一。",
            baseCost: 77,
            effects: [{ target: "attack", category: "infantry", pct: 5 }],
          },
        ],
      },
      {
        lineKey: "navy",
        lineLabel: "海軍艦隊",
        lineKind: "branch",
        branchFrom: { lineKey: "infantry", order: 3 },
        nodes: [
          {
            order: 1,
            name: "柯克帆船",
            description: "單桅圓身的柯克船，載運兵貨往來近海。",
            baseCost: 15,
            effects: [{ target: "hp", category: "ship", pct: 3 }],
          },
          {
            order: 2,
            name: "艉舵操控",
            description: "船尾裝設固定舵，操船轉向更為靈敏。",
            baseCost: 23,
            effects: [{ target: "speed", category: "ship", pct: 3 }],
          },
          {
            order: 3,
            name: "艦樓弩台",
            description: "船首尾築樓架弩，戰船耐久與火力提升。",
            baseCost: 31,
            effects: [{ target: "hp", category: "ship", pct: 5 }],
          },
          {
            order: 4,
            name: "商船護航",
            description: "編隊護送商船，保障海貿與運補安全。",
            baseCost: 38,
            effects: [{ target: "upkeep", category: "ship", pct: -3 }],
          },
        ],
      },
    ],
  },
  {
    eraSlug: "renaissance",
    lines: [
      {
        lineKey: "firearms",
        lineLabel: "火器革新",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "火繩槍",
            description: "以火繩點燃引藥擊發，槍手登上戰場。",
            baseCost: 23,
            effects: [{ target: "attack", category: "ranged", pct: 5 }],
          },
          {
            order: 2,
            name: "手銃",
            description: "短小手持火銃，近距轟擊破甲驚敵。",
            baseCost: 30,
            effects: [{ target: "attack", category: "ranged", pct: 5 }],
          },
          {
            order: 3,
            name: "火門槍",
            description: "以火門點火的長管火槍，威力漸增。",
            baseCost: 38,
            effects: [{ target: "attack", category: "ranged", pct: 5 }],
          },
          {
            order: 4,
            name: "齊射操典",
            description: "槍手分排輪番齊射，火力連綿不絕。",
            baseCost: 45,
            effects: [{ target: "accuracy", category: "ranged", pct: 5 }],
          },
          {
            order: 5,
            name: "鑄砲工坊",
            description: "設立工坊量產火砲，軍中火力充實。",
            baseCost: 53,
            effects: [{ target: "prodCost", category: "artillery", pct: -5 }],
          },
          {
            order: 6,
            name: "火槍兵",
            description: "火槍兵成軍，步兵攻擊與命中大幅躍升。",
            baseCost: 75,
            effects: [
              { target: "attack", category: "infantry", pct: 30 },
              { target: "accuracy", category: "infantry", pct: 20 },
            ],
            keySlug: "musketeer",
          },
          {
            order: 7,
            name: "輪轉燧發",
            description: "以燧石打火擊發，免除火繩點火之累。",
            baseCost: 68,
            effects: [{ target: "accuracy", category: "ranged", pct: 5 }],
          },
          {
            order: 8,
            name: "刺刀突擊",
            description: "槍口加裝刺刀衝鋒，步兵攻擊力提升。",
            baseCost: 75,
            effects: [{ target: "attack", category: "infantry", pct: 5 }],
          },
          {
            order: 9,
            name: "野戰砲車",
            description: "火砲加裝輪架隨軍機動，野戰皆可支援。",
            baseCost: 83,
            effects: [{ target: "speed", category: "artillery", pct: 5 }],
          },
          {
            order: 10,
            name: "火器軍團",
            description: "以火槍火砲為主力編成軍團，火力制敵。",
            baseCost: 90,
            effects: [{ target: "attack", category: null, pct: 5 }],
          },
        ],
      },
      {
        lineKey: "fortification",
        lineLabel: "稜堡工事",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "稜堡雛形",
            description: "築尖角稜堡消弭死角，抵禦火砲轟擊。",
            baseCost: 23,
            effects: [{ target: "defense", category: null, pct: 4 }],
          },
          {
            order: 2,
            name: "星形城郭",
            description: "城郭築成星芒之形，火力交叉無所遁形。",
            baseCost: 30,
            effects: [{ target: "defense", category: null, pct: 4 }],
          },
          {
            order: 3,
            name: "低矮土牆",
            description: "改築低厚土牆吸收砲彈，減損攻城火力。",
            baseCost: 38,
            effects: [{ target: "hp", category: null, pct: 4 }],
          },
          {
            order: 4,
            name: "交叉火網",
            description: "稜角配置火砲交叉射擊，封鎖進攻路徑。",
            baseCost: 45,
            effects: [{ target: "accuracy", category: "artillery", pct: 5 }],
          },
          {
            order: 5,
            name: "半月堡",
            description: "城前築半月外堡，遲滯掩護延伸防線。",
            baseCost: 53,
            effects: [{ target: "defense", category: "infantry", pct: 5 }],
          },
          {
            order: 6,
            name: "護城斜堤",
            description: "斜堤引導砲彈滑飛，減緩城牆受損。",
            baseCost: 60,
            effects: [{ target: "defense", category: null, pct: 4 }],
          },
          {
            order: 7,
            name: "砲台陣地",
            description: "牆頭設砲台陣地，居高反擊圍城之敵。",
            baseCost: 68,
            effects: [{ target: "attack", category: "artillery", pct: 5 }],
          },
          {
            order: 8,
            name: "縱深稜線",
            description: "多重稜線層層設防，全軍防禦顯著增強。",
            baseCost: 75,
            effects: [{ target: "defense", category: null, pct: 5 }],
          },
          {
            order: 9,
            name: "要塞環帶",
            description: "環城布設稜堡環帶，構成完整防禦體系。",
            baseCost: 83,
            effects: [{ target: "defense", category: "infantry", pct: 5 }],
          },
          {
            order: 10,
            name: "稜堡體系",
            description: "整合稜堡工事成體系，堅城傲視火砲時代。",
            baseCost: 90,
            effects: [{ target: "defense", category: null, pct: 5 }],
          },
        ],
      },
      {
        lineKey: "drill",
        lineLabel: "操典訓練",
        lineKind: "branch",
        branchFrom: { lineKey: "firearms", order: 3 },
        nodes: [
          {
            order: 1,
            name: "隊列步操",
            description: "反覆操練隊列進退，臨陣行止整齊劃一。",
            baseCost: 18,
            effects: [{ target: "speed", category: "infantry", pct: 3 }],
          },
          {
            order: 2,
            name: "裝填口令",
            description: "以口令統一裝填動作，射速穩定不亂。",
            baseCost: 27,
            effects: [{ target: "accuracy", category: "ranged", pct: 3 }],
          },
          {
            order: 3,
            name: "輪番射擊",
            description: "分排輪替裝填射擊，步兵命中率提升。",
            baseCost: 36,
            effects: [{ target: "accuracy", category: "infantry", pct: 5 }],
          },
          {
            order: 4,
            name: "軍官學校",
            description: "設校培訓軍官，指揮素養蔚然成風。",
            baseCost: 45,
            effects: [{ target: "recoveryRate", category: null, pct: 3 }],
          },
        ],
      },
    ],
  },
  {
    eraSlug: "discovery",
    lines: [
      {
        lineKey: "navy",
        lineLabel: "遠洋艦隊",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "卡拉維爾帆船",
            description: "輕巧靈活的卡拉維爾船，適於遠洋探索。",
            baseCost: 32,
            effects: [],
          },
          {
            order: 2,
            name: "三桅帆裝",
            description: "三桅多帆順逆風皆行，遠航更為自如。",
            baseCost: 42,
            effects: [],
          },
          {
            order: 3,
            name: "星盤導航",
            description: "以星盤測緯定位，越洋航行不致迷途。",
            baseCost: 53,
            effects: [],
          },
          {
            order: 4,
            name: "舷側砲列",
            description: "船舷排列火砲齊射，海戰火力成排傾瀉。",
            baseCost: 63,
            effects: [],
          },
          {
            order: 5,
            name: "蓋倫帆船",
            description: "高舷多砲的蓋倫巨艦，遠洋與海戰兼擅。",
            baseCost: 74,
            effects: [],
          },
          {
            order: 6,
            name: "指南針",
            description: "磁針恆指南北，戰船航速與遠航力大增。",
            baseCost: 105,
            effects: [{ target: "speed", category: "ship", pct: 20 }],
            keySlug: "compass",
          },
          {
            order: 7,
            name: "越洋補給",
            description: "沿途設補給站，支援艦隊橫渡大洋。",
            baseCost: 95,
            effects: [],
          },
          {
            order: 8,
            name: "艦砲齊射",
            description: "統一號令舷砲齊放，戰船攻擊力提升。",
            baseCost: 105,
            effects: [{ target: "attack", category: "ship", pct: 5 }],
          },
          {
            order: 9,
            name: "護衛艦隊",
            description: "編組護衛艦隊護送船團，掃蕩海盜私掠。",
            baseCost: 116,
            effects: [],
          },
          {
            order: 10,
            name: "無敵艦隊",
            description: "集結龐大艦隊縱橫海疆，宣示海上霸權。",
            baseCost: 126,
            effects: [],
          },
        ],
      },
      {
        lineKey: "gunnery",
        lineLabel: "火砲鑄造",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "青銅鑄砲",
            description: "以青銅鑄砲耐用不裂，火砲品質提升。",
            baseCost: 32,
            effects: [],
          },
          {
            order: 2,
            name: "鐵彈實心",
            description: "改用實心鐵彈，射遠而破壞力更強。",
            baseCost: 42,
            effects: [],
          },
          {
            order: 3,
            name: "砲車機動",
            description: "火砲架於堅固砲車，隨軍轉移快捷。",
            baseCost: 53,
            effects: [],
          },
          {
            order: 4,
            name: "臼砲曲射",
            description: "以臼砲高角曲射，越牆轟擊城內目標。",
            baseCost: 63,
            effects: [],
          },
          {
            order: 5,
            name: "攻城重砲",
            description: "巨型重砲專攻堅城，一擊崩裂厚牆。",
            baseCost: 74,
            effects: [],
          },
          {
            order: 6,
            name: "散彈霰射",
            description: "近距發射散彈，如霰橫掃密集敵陣。",
            baseCost: 84,
            effects: [],
          },
          {
            order: 7,
            name: "砲兵測距",
            description: "以量具估距校準，砲擊漸趨精準。",
            baseCost: 95,
            effects: [],
          },
          {
            order: 8,
            name: "標準口徑",
            description: "統一砲彈口徑便於補給，火砲攻擊提升。",
            baseCost: 105,
            effects: [{ target: "attack", category: "artillery", pct: 5 }],
          },
          {
            order: 9,
            name: "要塞砲群",
            description: "要塞集結砲群交叉轟擊，火力綿密。",
            baseCost: 116,
            effects: [],
          },
          {
            order: 10,
            name: "砲兵操典",
            description: "頒行砲兵操典規範操砲，射擊井然有序。",
            baseCost: 126,
            effects: [],
          },
        ],
      },
      {
        lineKey: "logistics",
        lineLabel: "遠征後勤",
        lineKind: "branch",
        branchFrom: { lineKey: "navy", order: 3 },
        nodes: [
          {
            order: 1,
            name: "遠航口糧",
            description: "備製耐存口糧，供艦隊長途遠航食用。",
            baseCost: 25,
            effects: [],
          },
          {
            order: 2,
            name: "補給船隊",
            description: "隨艦編組補給船，海上運補水糧彈藥。",
            baseCost: 38,
            effects: [],
          },
          {
            order: 3,
            name: "殖民港站",
            description: "海外設港站補給，登陸投送能力提升。",
            baseCost: 50,
            effects: [{ target: "seaLandingCapacity", category: null, pct: 5 }],
          },
          {
            order: 4,
            name: "檢疫防病",
            description: "船上檢疫防治疫病，保全遠征兵員。",
            baseCost: 63,
            effects: [],
          },
        ],
      },
    ],
  },
  {
    eraSlug: "scientific",
    lines: [
      {
        lineKey: "medical",
        lineLabel: "軍醫體系",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "戰地包紮",
            description: "教習包紮止血之法，減少陣亡與潰爛。",
            baseCost: 38,
            effects: [],
          },
          {
            order: 2,
            name: "外科截肢",
            description: "以外科截去壞肢，挽救傷兵性命。",
            baseCost: 50,
            effects: [],
          },
          {
            order: 3,
            name: "軍醫營帳",
            description: "設軍醫營帳收治傷患，就近醫療照護。",
            baseCost: 63,
            effects: [],
          },
          {
            order: 4,
            name: "止血縫合",
            description: "以縫合結紮止血，傷口癒合更速。",
            baseCost: 75,
            effects: [],
          },
          {
            order: 5,
            name: "傷兵後送",
            description: "設制度後送傷員，救治不誤延性命。",
            baseCost: 88,
            effects: [],
          },
          {
            order: 6,
            name: "醫學",
            description: "軍醫科學漸成體系，全軍恢復速率大增。",
            baseCost: 125,
            effects: [{ target: "recoveryRate", category: null, pct: 50 }],
            keySlug: "medicine",
          },
          {
            order: 7,
            name: "消毒清創",
            description: "以清創消毒防感染，術後存活大增。",
            baseCost: 113,
            effects: [],
          },
          {
            order: 8,
            name: "疫病隔離",
            description: "隔離患者防疫病蔓延，兵員恢復加速。",
            baseCost: 125,
            effects: [{ target: "recoverySpeed", category: null, pct: 5 }],
          },
          {
            order: 9,
            name: "軍醫學堂",
            description: "設學堂培育軍醫，醫術人才代代相承。",
            baseCost: 138,
            effects: [],
          },
          {
            order: 10,
            name: "野戰醫院",
            description: "隨軍設野戰醫院，成規模救治傷病員。",
            baseCost: 150,
            effects: [],
          },
        ],
      },
      {
        lineKey: "ballistics",
        lineLabel: "彈道科學",
        lineKind: "main",
        nodes: [
          {
            order: 1,
            name: "拋物軌跡",
            description: "研明砲彈拋物軌跡，射擊有理可循。",
            baseCost: 38,
            effects: [],
          },
          {
            order: 2,
            name: "火藥配比",
            description: "調配火藥成分，燃燒穩定推力增強。",
            baseCost: 50,
            effects: [],
          },
          {
            order: 3,
            name: "膛線初探",
            description: "槍管刻旋轉膛線，彈丸旋進更為準直。",
            baseCost: 63,
            effects: [],
          },
          {
            order: 4,
            name: "砲表計算",
            description: "編製射表推算射角，砲擊有據可依。",
            baseCost: 75,
            effects: [],
          },
          {
            order: 5,
            name: "引信定時",
            description: "以定時引信控制爆點，空炸殺傷成群。",
            baseCost: 88,
            effects: [],
          },
          {
            order: 6,
            name: "顆粒火藥",
            description: "製成顆粒火藥燃燒均勻，威力更為穩定。",
            baseCost: 100,
            effects: [],
          },
          {
            order: 7,
            name: "標準彈丸",
            description: "統一彈丸規格便於量產，補給無虞。",
            baseCost: 113,
            effects: [],
          },
          {
            order: 8,
            name: "精密瞄具",
            description: "加裝精密瞄具校準，全軍命中率提升。",
            baseCost: 125,
            effects: [{ target: "accuracy", category: null, pct: 5 }],
          },
          {
            order: 9,
            name: "後座緩衝",
            description: "設緩衝機構吸收後座，射擊穩定連發。",
            baseCost: 138,
            effects: [],
          },
          {
            order: 10,
            name: "彈道學說",
            description: "彈道之學蔚然成說，火器射擊臻於科學。",
            baseCost: 150,
            effects: [],
          },
        ],
      },
      {
        lineKey: "fortification",
        lineLabel: "要塞工程",
        lineKind: "branch",
        branchFrom: { lineKey: "ballistics", order: 3 },
        nodes: [
          {
            order: 1,
            name: "幾何築城",
            description: "以幾何原理規劃城防，火力涵蓋周全。",
            baseCost: 30,
            effects: [],
          },
          {
            order: 2,
            name: "稜角砲台",
            description: "稜角處築砲台，交叉封鎖進攻要道。",
            baseCost: 45,
            effects: [],
          },
          {
            order: 3,
            name: "地下坑道",
            description: "挖掘地下坑道機動與掩蔽，全軍防禦提升。",
            baseCost: 60,
            effects: [{ target: "defense", category: null, pct: 5 }],
          },
          {
            order: 4,
            name: "要塞守則",
            description: "頒行要塞守則規範守備，防務章法井然。",
            baseCost: 75,
            effects: [],
          },
        ],
      },
    ],
  },
];
