// Task #469 — 科技樹預設種子（production 領域，前半）
import type { ProductionTechEffect } from "@workspace/db";
import type { TechTreeSeedEra } from "./types";

export const PRODUCTION_ERAS_EARLY: TechTreeSeedEra<ProductionTechEffect>[] = [
  {
    eraSlug: "classical",
    lines: [
      {
        lineKey: "agriculture",
        lineLabel: "農耕基礎",
        lineKind: "main",
        nodes: [
          { order: 1, name: "刀耕火種", description: "焚林闢地，以粗放耕作擴充糧產。", baseCost: 6, effects: [{ target: "productivity", value: 2 }] },
          { order: 2, name: "石犁耕作", description: "以石製犁具翻土，提升耕地效率。", baseCost: 8, effects: [{ target: "productivity", value: 2 }] },
          { order: 3, name: "選種育苗", description: "挑選良種培育壯苗，穩定收成。", baseCost: 10, effects: [{ target: "populationGrowth", value: 1 }] },
          { order: 4, name: "溝渠引水", description: "開挖溝渠導引河水潤田。", baseCost: 12, effects: [{ target: "productivity", value: 2 }] },
          { order: 5, name: "輪耕休地", description: "輪換耕地與休耕以養地力。", baseCost: 14, effects: [{ target: "populationGrowth", value: 1 }] },
          {
            order: 6,
            name: "灌溉農業",
            description: "修築渠圳大規模引水灌田，糧產與人口激增。",
            baseCost: 20,
            keySlug: "irrigation",
            effects: [
              { target: "productivity", value: 5 },
              { target: "tempPopulationGrowth", value: 50 },
            ],
          },
          { order: 7, name: "穀倉儲糧", description: "建倉囤糧以備荒年不虞。", baseCost: 18, effects: [{ target: "populationGrowth", value: 1 }] },
          { order: 8, name: "牛耕犁田", description: "役使耕牛拉犁，深耕沃土。", baseCost: 20, effects: [{ target: "productivity", value: 3 }] },
          { order: 9, name: "堆肥施田", description: "積肥還田補充地力。", baseCost: 22, effects: [{ target: "productivity", value: 2 }] },
          { order: 10, name: "農時曆法", description: "依節氣制定農事曆，統籌播收。", baseCost: 24, effects: [{ target: "productivity", value: 3 }] },
        ],
      },
      {
        lineKey: "crafts",
        lineLabel: "工匠技藝",
        lineKind: "main",
        nodes: [
          { order: 1, name: "燧石打製", description: "敲打燧石成器，最古老的工具製作。", baseCost: 6, effects: [{ target: "productivity", value: 2 }] },
          { order: 2, name: "製陶成器", description: "塑泥燒陶製作各式容器。", baseCost: 8, effects: [{ target: "productivity", value: 2 }] },
          { order: 3, name: "紡線織麻", description: "搓線織布縫製衣物。", baseCost: 10, effects: [{ target: "productivity", value: 2 }] },
          { order: 4, name: "木作榫接", description: "以榫卯接合木料製器。", baseCost: 12, effects: [{ target: "productivity", value: 2 }] },
          { order: 5, name: "皮革鞣製", description: "鞣治獸皮製成耐用皮件。", baseCost: 14, effects: [{ target: "productivity", value: 2 }] },
          { order: 6, name: "冶銅鑄器", description: "熔銅鑄造工具與禮器。", baseCost: 16, effects: [{ target: "productivity", value: 3 }] },
          { order: 7, name: "陶輪拉坯", description: "以轉輪拉製規整陶坯。", baseCost: 18, effects: [{ target: "productivity", value: 2 }] },
          { order: 8, name: "磨石琢玉", description: "研磨琢製石玉飾器。", baseCost: 20, effects: [{ target: "techPoints", value: 1 }] },
          { order: 9, name: "編籃盛物", description: "編織藤條製作盛具。", baseCost: 22, effects: [{ target: "productivity", value: 2 }] },
          { order: 10, name: "匠坊分工", description: "工匠依技分工協作成坊。", baseCost: 24, effects: [{ target: "productivity", value: 3 }] },
        ],
      },
      {
        lineKey: "construction",
        lineLabel: "土木營造",
        lineKind: "branch",
        branchFrom: { lineKey: "crafts", order: 4 },
        nodes: [
          { order: 1, name: "夯土築牆", description: "夯實泥土砌築牆垣。", baseCost: 5, effects: [{ target: "productivity", value: 1 }] },
          { order: 2, name: "石砌基座", description: "疊石為基穩固屋宇。", baseCost: 7, effects: [{ target: "productivity", value: 2 }] },
          { order: 3, name: "木構樑架", description: "架設木樑撐起屋頂。", baseCost: 10, effects: [{ target: "productivity", value: 1 }] },
          { order: 4, name: "瓦當覆頂", description: "燒瓦覆頂遮風擋雨。", baseCost: 12, effects: [{ target: "techPoints", value: 1 }] },
        ],
      },
    ],
  },
  {
    eraSlug: "roman",
    lines: [
      {
        lineKey: "manufacturing",
        lineLabel: "帝國工藝",
        lineKind: "main",
        nodes: [
          { order: 1, name: "熔爐鍛鐵", description: "建爐鍛打鐵器，兵農皆利。", baseCost: 10, effects: [{ target: "productivity", value: 3 }] },
          { order: 2, name: "玻璃吹製", description: "吹製玻璃器皿供日用。", baseCost: 13, effects: [{ target: "productivity", value: 2 }] },
          { order: 3, name: "混凝土漿", description: "調配火山灰混凝土砌築。", baseCost: 17, effects: [{ target: "productivity", value: 3 }] },
          { order: 4, name: "模具翻鑄", description: "以模具批量翻鑄器件。", baseCost: 20, effects: [{ target: "productivity", value: 3 }] },
          { order: 5, name: "車床旋木", description: "以簡易車床旋製木器。", baseCost: 24, effects: [{ target: "productivity", value: 2 }] },
          {
            order: 6,
            name: "手工工藝",
            description: "工匠精研百工技藝，製造效率大增。",
            baseCost: 34,
            keySlug: "handicraft",
            effects: [{ target: "productivity", value: 6 }],
          },
          { order: 7, name: "榨油壓製", description: "以壓榨機取油供炊照。", baseCost: 30, effects: [{ target: "productivity", value: 2 }] },
          { order: 8, name: "鑲嵌鍍飾", description: "鑲嵌貴金屬裝飾器物。", baseCost: 34, effects: [{ target: "productivity", value: 2 }] },
          { order: 9, name: "焊接接合", description: "以焊料接合金屬件。", baseCost: 37, effects: [{ target: "productivity", value: 3 }] },
          { order: 10, name: "工場規制", description: "訂立工場規制統一品質。", baseCost: 40, effects: [{ target: "productivity", value: 3 }] },
        ],
      },
      {
        lineKey: "records",
        lineLabel: "文書載記",
        lineKind: "main",
        nodes: [
          { order: 1, name: "蠟板刻寫", description: "於蠟板上刻寫記事。", baseCost: 10, effects: [{ target: "techPoints", value: 1 }] },
          { order: 2, name: "莎草紙卷", description: "以莎草製紙書寫成卷。", baseCost: 13, effects: [{ target: "techPoints", value: 1 }] },
          { order: 3, name: "竹簡編冊", description: "以竹簡串編成冊。", baseCost: 17, effects: [{ target: "techPoints", value: 1 }] },
          { order: 4, name: "墨料調製", description: "調製墨料書寫記錄。", baseCost: 20, effects: [{ target: "techPoints", value: 1 }] },
          { order: 5, name: "抄寫謄錄", description: "抄寫文書謄錄典籍。", baseCost: 24, effects: [{ target: "techPoints", value: 2 }] },
          {
            order: 6,
            name: "造紙術",
            description: "以纖維抄造紙張，書寫傳播大興。",
            baseCost: 34,
            keySlug: "papermaking",
            effects: [
              { target: "techPoints", value: 5 },
              { target: "enableCulture", value: 1 },
            ],
          },
          { order: 7, name: "檔案庫藏", description: "設庫典藏公文檔案。", baseCost: 30, effects: [{ target: "techPoints", value: 2 }] },
          { order: 8, name: "帳簿記數", description: "以帳簿記錄財貨收支。", baseCost: 34, effects: [{ target: "productivity", value: 2 }] },
          { order: 9, name: "印章封緘", description: "以印章封緘公私文件。", baseCost: 37, effects: [{ target: "techPoints", value: 1 }] },
          { order: 10, name: "郵驛傳遞", description: "設驛站接力傳遞文書。", baseCost: 40, effects: [{ target: "techPoints", value: 2 }] },
        ],
      },
      {
        lineKey: "roads",
        lineLabel: "道路橋樑",
        lineKind: "branch",
        branchFrom: { lineKey: "manufacturing", order: 4 },
        nodes: [
          { order: 1, name: "石板大道", description: "鋪設石板大道通行四方。", baseCost: 8, effects: [{ target: "productivity", value: 2 }] },
          { order: 2, name: "拱橋跨河", description: "築拱橋橫跨河川。", baseCost: 12, effects: [{ target: "productivity", value: 2 }] },
          { order: 3, name: "里程碑柱", description: "立里程碑標示路距。", baseCost: 16, effects: [{ target: "productivity", value: 1 }] },
          { order: 4, name: "港埠碼頭", description: "修築碼頭停泊船隻。", baseCost: 20, effects: [{ target: "techPoints", value: 1 }] },
        ],
      },
    ],
  },
  {
    eraSlug: "early_medieval",
    lines: [
      {
        lineKey: "waterpower",
        lineLabel: "水力動力",
        lineKind: "main",
        nodes: [
          { order: 1, name: "水輪汲水", description: "以水輪汲水灌田。", baseCost: 14, effects: [{ target: "productivity", value: 3 }] },
          { order: 2, name: "溪流導槽", description: "開槽引溪流驅動器械。", baseCost: 18, effects: [{ target: "productivity", value: 3 }] },
          { order: 3, name: "立式水車", description: "架設立式水車轉磨。", baseCost: 23, effects: [{ target: "productivity", value: 3 }] },
          { order: 4, name: "水錘鍛冶", description: "以水力錘鍛打鐵料。", baseCost: 27, effects: [{ target: "productivity", value: 4 }] },
          { order: 5, name: "堰壩蓄水", description: "築堰蓄水穩定水勢。", baseCost: 32, effects: [{ target: "productivity", value: 3 }] },
          {
            order: 6,
            name: "水力技術",
            description: "廣用水力驅動磨坊與鍛爐，生產大進。",
            baseCost: 45,
            keySlug: "water_power",
            effects: [{ target: "productivity", value: 8 }],
          },
          { order: 7, name: "水磨碾穀", description: "以水磨碾製穀物。", baseCost: 41, effects: [{ target: "productivity", value: 3 }] },
          { order: 8, name: "水力鼓風", description: "以水力鼓風助冶煉。", baseCost: 45, effects: [{ target: "productivity", value: 4 }] },
          { order: 9, name: "渠圳網絡", description: "廣布渠圳輸配水力。", baseCost: 50, effects: [{ target: "productivity", value: 3 }] },
          { order: 10, name: "水閘調節", description: "設水閘調節水流量。", baseCost: 54, effects: [{ target: "productivity", value: 4 }] },
        ],
      },
      {
        lineKey: "scriptorium",
        lineLabel: "繕寫典籍",
        lineKind: "main",
        nodes: [
          { order: 1, name: "修院繕寫", description: "修院僧侶繕寫典籍。", baseCost: 14, effects: [{ target: "techPoints", value: 1 }] },
          { order: 2, name: "羊皮裝幀", description: "以羊皮裝幀書冊。", baseCost: 18, effects: [{ target: "techPoints", value: 1 }] },
          { order: 3, name: "泥金插畫", description: "泥金彩繪裝飾書頁。", baseCost: 23, effects: [{ target: "techPoints", value: 2 }] },
          { order: 4, name: "花體字書", description: "以花體字謄錄經文。", baseCost: 27, effects: [{ target: "techPoints", value: 1 }] },
          { order: 5, name: "目錄編次", description: "編排目錄便於檢索。", baseCost: 32, effects: [{ target: "techPoints", value: 2 }] },
          {
            order: 6,
            name: "抄本圖書",
            description: "大量繕製抄本典籍，學識廣為留傳。",
            baseCost: 45,
            keySlug: "manuscript",
            effects: [{ target: "techPoints", value: 8 }],
          },
          { order: 7, name: "圖書館藏", description: "設館典藏抄本圖書。", baseCost: 41, effects: [{ target: "techPoints", value: 2 }] },
          { order: 8, name: "校勘訂正", description: "校勘文本訂正訛誤。", baseCost: 45, effects: [{ target: "techPoints", value: 2 }] },
          { order: 9, name: "經卷裝訂", description: "裝訂經卷成冊保存。", baseCost: 50, effects: [{ target: "techPoints", value: 2 }] },
          { order: 10, name: "學塾講讀", description: "設塾講讀傳授學問。", baseCost: 54, effects: [{ target: "techPoints", value: 3 }] },
        ],
      },
      {
        lineKey: "masonry",
        lineLabel: "石造工事",
        lineKind: "branch",
        branchFrom: { lineKey: "waterpower", order: 4 },
        nodes: [
          { order: 1, name: "拱頂石造", description: "砌築拱頂承重跨距。", baseCost: 11, effects: [{ target: "productivity", value: 2 }] },
          { order: 2, name: "城堡壘石", description: "壘石築堡以資防護。", baseCost: 16, effects: [{ target: "productivity", value: 2 }] },
          { order: 3, name: "尖塔飛扶", description: "以飛扶壁支撐尖塔。", baseCost: 22, effects: [{ target: "productivity", value: 2 }] },
          { order: 4, name: "石橋墩基", description: "打造橋墩承載石橋。", baseCost: 27, effects: [{ target: "techPoints", value: 1 }] },
        ],
      },
    ],
  },
  {
    eraSlug: "high_medieval",
    lines: [
      {
        lineKey: "windpower",
        lineLabel: "風力機械",
        lineKind: "main",
        nodes: [
          { order: 1, name: "帆布受風", description: "以帆布受風轉軸。", baseCost: 19, effects: [{ target: "productivity", value: 3 }] },
          { order: 2, name: "立式風磨", description: "架立式風磨碾穀。", baseCost: 26, effects: [{ target: "productivity", value: 3 }] },
          { order: 3, name: "齒輪傳動", description: "以齒輪傳遞動力。", baseCost: 32, effects: [{ target: "productivity", value: 4 }] },
          { order: 4, name: "塔式風車", description: "建塔式風車增效。", baseCost: 38, effects: [{ target: "productivity", value: 4 }] },
          { order: 5, name: "風向調帆", description: "依風向調整帆葉。", baseCost: 45, effects: [{ target: "productivity", value: 3 }] },
          {
            order: 6,
            name: "風車技術",
            description: "廣建風車驅動磨坊，兼利營造與防務。",
            baseCost: 64,
            keySlug: "windmill",
            effects: [
              { target: "productivity", value: 5 },
              { target: "buildingUpkeepReduction", value: 50 },
              { target: "enableCityWall", value: 1 },
            ],
          },
          { order: 7, name: "風磨群落", description: "成群風磨連片運作。", baseCost: 58, effects: [{ target: "productivity", value: 4 }] },
          { order: 8, name: "曲柄連桿", description: "以曲柄連桿轉換往復。", baseCost: 64, effects: [{ target: "productivity", value: 4 }] },
          { order: 9, name: "木製凸輪", description: "以凸輪驅動錘械。", baseCost: 70, effects: [{ target: "productivity", value: 3 }] },
          { order: 10, name: "動力分配", description: "分配風水動力至諸坊。", baseCost: 77, effects: [{ target: "productivity", value: 4 }] },
        ],
      },
      {
        lineKey: "guildcraft",
        lineLabel: "行會工坊",
        lineKind: "main",
        nodes: [
          { order: 1, name: "鐵匠爐鍛", description: "鐵匠爐火鍛打器械。", baseCost: 19, effects: [{ target: "productivity", value: 3 }] },
          { order: 2, name: "織機提綜", description: "以提綜織機織花布。", baseCost: 26, effects: [{ target: "productivity", value: 3 }] },
          { order: 3, name: "制革工坊", description: "設坊鞣製皮革製品。", baseCost: 32, effects: [{ target: "productivity", value: 3 }] },
          { order: 4, name: "玻璃彩窗", description: "燒製彩色玻璃窗。", baseCost: 38, effects: [{ target: "techPoints", value: 2 }] },
          { order: 5, name: "鐘錶擒縱", description: "以擒縱機構製鐘。", baseCost: 45, effects: [{ target: "techPoints", value: 2 }] },
          { order: 6, name: "銅版鏤刻", description: "於銅版鏤刻圖文。", baseCost: 51, effects: [{ target: "techPoints", value: 2 }] },
          { order: 7, name: "陶窯釉燒", description: "施釉入窯燒製瓷陶。", baseCost: 58, effects: [{ target: "productivity", value: 3 }] },
          { order: 8, name: "金銀細工", description: "精製金銀細巧飾件。", baseCost: 64, effects: [{ target: "productivity", value: 3 }] },
          { order: 9, name: "造船龍骨", description: "鋪設龍骨建造船身。", baseCost: 70, effects: [{ target: "productivity", value: 4 }] },
          { order: 10, name: "行會規約", description: "訂立行會規約統管百工。", baseCost: 77, effects: [{ target: "productivity", value: 4 }] },
        ],
      },
      {
        lineKey: "manor",
        lineLabel: "莊園農作",
        lineKind: "branch",
        branchFrom: { lineKey: "windpower", order: 5 },
        nodes: [
          { order: 1, name: "敞田耕作", description: "敞田共耕分配地畝。", baseCost: 15, effects: [{ target: "productivity", value: 2 }] },
          { order: 2, name: "重犁深耕", description: "以重犁深耕黏重土壤。", baseCost: 23, effects: [{ target: "productivity", value: 2 }] },
          { order: 3, name: "馬軛挽力", description: "以馬軛提升挽曳之力。", baseCost: 31, effects: [{ target: "productivity", value: 2 }] },
          { order: 4, name: "三田輪作", description: "三田輪替耕種與休耕。", baseCost: 38, effects: [{ target: "populationGrowth", value: 1 }] },
        ],
      },
    ],
  },
  {
    eraSlug: "renaissance",
    lines: [
      {
        lineKey: "agronomy",
        lineLabel: "農學新知",
        lineKind: "main",
        nodes: [
          { order: 1, name: "新作引種", description: "引進新作物拓展食源。", baseCost: 23, effects: [{ target: "populationGrowth", value: 1 }] },
          { order: 2, name: "苗圃培育", description: "設苗圃培育良種。", baseCost: 30, effects: [{ target: "productivity", value: 3 }] },
          { order: 3, name: "排水造田", description: "排乾沼澤墾闢農田。", baseCost: 38, effects: [{ target: "productivity", value: 4 }] },
          { order: 4, name: "施肥輪替", description: "輪替施肥維護地力。", baseCost: 45, effects: [{ target: "productivity", value: 4 }] },
          { order: 5, name: "圈地牧養", description: "圈地牧養牲畜增產。", baseCost: 53, effects: [{ target: "productivity", value: 4 }] },
          {
            order: 6,
            name: "三圃輪作",
            description: "分田三圃輪耕休養，糧產與人口大增。",
            baseCost: 75,
            keySlug: "crop_rotation",
            effects: [
              { target: "populationGrowth", value: 3 },
              { target: "tempPopulationGrowth", value: 50 },
            ],
          },
          { order: 7, name: "牧草栽植", description: "栽植牧草兼養地力。", baseCost: 68, effects: [{ target: "populationGrowth", value: 1 }] },
          { order: 8, name: "果園嫁接", description: "嫁接果木改良品種。", baseCost: 75, effects: [{ target: "productivity", value: 3 }] },
          { order: 9, name: "農書纂輯", description: "纂輯農書傳授耕法。", baseCost: 83, effects: [{ target: "techPoints", value: 2 }] },
          { order: 10, name: "市集糧運", description: "以市集集散糧貨。", baseCost: 90, effects: [{ target: "productivity", value: 4 }] },
        ],
      },
      {
        lineKey: "printing",
        lineLabel: "印刷傳藝",
        lineKind: "main",
        nodes: [
          { order: 1, name: "木刻雕版", description: "雕刻木版印製圖文。", baseCost: 23, effects: [{ target: "techPoints", value: 1 }] },
          { order: 2, name: "活字排版", description: "以活字排版印書。", baseCost: 30, effects: [{ target: "techPoints", value: 2 }] },
          { order: 3, name: "油墨調配", description: "調配油墨印刷清晰。", baseCost: 38, effects: [{ target: "techPoints", value: 1 }] },
          { order: 4, name: "螺旋壓印", description: "以螺旋壓機印製書頁。", baseCost: 45, effects: [{ target: "techPoints", value: 2 }] },
          { order: 5, name: "版式對開", description: "訂立對開版式規格。", baseCost: 53, effects: [{ target: "techPoints", value: 2 }] },
          { order: 6, name: "銅版腐蝕", description: "以酸腐蝕銅版製圖。", baseCost: 60, effects: [{ target: "techPoints", value: 2 }] },
          { order: 7, name: "裝訂成冊", description: "裝訂印張裝成書冊。", baseCost: 68, effects: [{ target: "techPoints", value: 2 }] },
          { order: 8, name: "書坊刊行", description: "設書坊刊行書籍。", baseCost: 75, effects: [{ target: "techPoints", value: 3 }] },
          { order: 9, name: "紙廠抄造", description: "建廠大量抄造紙張。", baseCost: 83, effects: [{ target: "productivity", value: 4 }] },
          { order: 10, name: "出版行銷", description: "以行銷推廣書刊。", baseCost: 90, effects: [{ target: "techPoints", value: 3 }] },
        ],
      },
      {
        lineKey: "architecture",
        lineLabel: "文藝建築",
        lineKind: "branch",
        branchFrom: { lineKey: "printing", order: 5 },
        nodes: [
          { order: 1, name: "圓頂穹窿", description: "建圓頂穹窿覆廣廳。", baseCost: 18, effects: [{ target: "productivity", value: 2 }] },
          { order: 2, name: "透視構圖", description: "以透視法規劃建物。", baseCost: 27, effects: [{ target: "productivity", value: 2 }] },
          { order: 3, name: "對稱立面", description: "講求對稱的建築立面。", baseCost: 36, effects: [{ target: "productivity", value: 2 }] },
          { order: 4, name: "石材切磨", description: "精切磨製石材構件。", baseCost: 45, effects: [{ target: "techPoints", value: 2 }] },
        ],
      },
    ],
  },
  {
    eraSlug: "discovery",
    lines: [
      {
        lineKey: "shipbuilding",
        lineLabel: "遠洋航海",
        lineKind: "main",
        nodes: [
          { order: 1, name: "卡拉維爾", description: "建卡拉維爾帆船遠航。", baseCost: 32, effects: [] },
          { order: 2, name: "三角帆索", description: "以三角帆逆風航行。", baseCost: 42, effects: [] },
          { order: 3, name: "羅盤導航", description: "以羅盤定向導航。", baseCost: 53, effects: [] },
          { order: 4, name: "海圖繪測", description: "測繪海圖標註航路。", baseCost: 63, effects: [] },
          { order: 5, name: "船塢建造", description: "建船塢批量造船。", baseCost: 74, effects: [] },
          {
            order: 6,
            name: "遠洋造船",
            description: "打造遠洋巨艦，開拓殖民與海權。",
            baseCost: 105,
            keySlug: "oceanic_shipbuilding",
            effects: [
              { target: "productivity", value: 8 },
              { target: "enableColonization", value: 1 },
              { target: "enableNaval", value: 1 },
            ],
          },
          { order: 7, name: "蓋倫巨艦", description: "建蓋倫巨艦載貨遠航。", baseCost: 95, effects: [] },
          { order: 8, name: "六分儀測", description: "以六分儀測緯定位。", baseCost: 105, effects: [] },
          { order: 9, name: "補給航線", description: "規劃補給航線續航。", baseCost: 116, effects: [] },
          { order: 10, name: "商船船隊", description: "組織商船船隊通商。", baseCost: 126, effects: [] },
        ],
      },
      {
        lineKey: "metallurgy",
        lineLabel: "冶金精煉",
        lineKind: "main",
        nodes: [
          { order: 1, name: "高爐煉鐵", description: "建高爐煉鑄生鐵。", baseCost: 32, effects: [] },
          { order: 2, name: "坩堝鑄鋼", description: "以坩堝熔鑄鋼料。", baseCost: 42, effects: [] },
          { order: 3, name: "錘鍛延壓", description: "錘鍛延壓成型金屬。", baseCost: 53, effects: [] },
          { order: 4, name: "汞齊提銀", description: "以汞齊法提煉白銀。", baseCost: 63, effects: [] },
          { order: 5, name: "硝石製取", description: "提取硝石以製火藥。", baseCost: 74, effects: [] },
          { order: 6, name: "火藥配製", description: "配製火藥供爆破採礦。", baseCost: 84, effects: [] },
          { order: 7, name: "銅錫合金", description: "熔配銅錫成青銅。", baseCost: 95, effects: [] },
          { order: 8, name: "玻璃鏡面", description: "鍍製玻璃鏡面。", baseCost: 105, effects: [] },
          { order: 9, name: "鑄幣壓印", description: "壓印鑄造流通貨幣。", baseCost: 116, effects: [] },
          { order: 10, name: "礦冶規程", description: "訂立礦冶規程增效。", baseCost: 126, effects: [] },
        ],
      },
      {
        lineKey: "plantation",
        lineLabel: "殖民作物",
        lineKind: "branch",
        branchFrom: { lineKey: "shipbuilding", order: 6 },
        nodes: [
          { order: 1, name: "甘蔗種植", description: "廣植甘蔗製糖外銷。", baseCost: 25, effects: [{ target: "productivity", value: 2 }] },
          { order: 2, name: "香料栽培", description: "栽培香料獲利豐厚。", baseCost: 38, effects: [] },
          { order: 3, name: "新陸作物", description: "引入新陸作物如馬鈴薯。", baseCost: 50, effects: [{ target: "tempPopulationGrowth", value: 30 }] },
          { order: 4, name: "種植園制", description: "建立種植園規模生產。", baseCost: 63, effects: [{ target: "productivity", value: 1 }] },
        ],
      },
    ],
  },
  {
    eraSlug: "scientific",
    lines: [
      {
        lineKey: "chemistry",
        lineLabel: "化學初創",
        lineKind: "main",
        nodes: [
          { order: 1, name: "元素辨識", description: "辨識基本化學元素。", baseCost: 38, effects: [] },
          { order: 2, name: "燃素試驗", description: "以燃素說解釋燃燒。", baseCost: 50, effects: [] },
          { order: 3, name: "酸鹼中和", description: "研究酸鹼中和反應。", baseCost: 63, effects: [] },
          { order: 4, name: "蒸餾提純", description: "以蒸餾法提純物質。", baseCost: 75, effects: [] },
          { order: 5, name: "氣體收集", description: "收集分離各種氣體。", baseCost: 88, effects: [] },
          { order: 6, name: "定量分析", description: "以天平定量分析物質。", baseCost: 100, effects: [] },
          { order: 7, name: "結晶提取", description: "以結晶法提取純物。", baseCost: 113, effects: [] },
          { order: 8, name: "玻璃儀器", description: "製作精密玻璃儀器。", baseCost: 125, effects: [] },
          { order: 9, name: "反應記錄", description: "系統記錄化學反應。", baseCost: 138, effects: [] },
          { order: 10, name: "實驗規範", description: "訂立實驗操作規範。", baseCost: 150, effects: [] },
        ],
      },
      {
        lineKey: "instruments",
        lineLabel: "精密儀器",
        lineKind: "main",
        nodes: [
          { order: 1, name: "望遠鏡片", description: "磨製鏡片組裝望遠鏡。", baseCost: 38, effects: [] },
          { order: 2, name: "顯微觀察", description: "以顯微鏡觀察微物。", baseCost: 50, effects: [] },
          { order: 3, name: "擺鐘計時", description: "以擺鐘精確計時。", baseCost: 63, effects: [] },
          { order: 4, name: "氣壓量測", description: "以氣壓計量測大氣。", baseCost: 75, effects: [] },
          { order: 5, name: "溫度標度", description: "訂立溫度量標。", baseCost: 88, effects: [] },
          { order: 6, name: "遊標卡尺", description: "以遊標卡尺精量尺寸。", baseCost: 100, effects: [] },
          { order: 7, name: "天平衡量", description: "以精密天平衡量重量。", baseCost: 113, effects: [] },
          { order: 8, name: "對數計算", description: "以對數簡化繁複計算。", baseCost: 125, effects: [] },
          { order: 9, name: "齒輪計數", description: "以齒輪機構計數。", baseCost: 138, effects: [] },
          { order: 10, name: "儀器工坊", description: "設工坊製造精密儀器。", baseCost: 150, effects: [] },
        ],
      },
      {
        lineKey: "steam_early",
        lineLabel: "蒸汽先聲",
        lineKind: "branch",
        branchFrom: { lineKey: "chemistry", order: 5 },
        nodes: [
          { order: 1, name: "真空試驗", description: "以真空試驗探究氣壓。", baseCost: 30, effects: [{ target: "productivity", value: 2 }] },
          { order: 2, name: "汽壓抽水", description: "以汽壓機抽排礦水。", baseCost: 45, effects: [] },
          { order: 3, name: "活塞往復", description: "以活塞往復轉換動力。", baseCost: 60, effects: [{ target: "techPoints", value: 2 }] },
          { order: 4, name: "鍋爐生汽", description: "以鍋爐加熱生汽。", baseCost: 75, effects: [] },
        ],
      },
    ],
  },
];
