// Task #469 — 科技樹預設種子（production 領域，後半）
import type { ProductionTechEffect } from "@workspace/db";
import type { TechTreeSeedEra } from "./types";

export const PRODUCTION_ERAS_LATE: TechTreeSeedEra<ProductionTechEffect>[] = [
  {
    eraSlug: "enlightenment",
    lines: [
      {
        lineKey: "steam_power",
        lineLabel: "蒸汽動力",
        lineKind: "main",
        nodes: [
          { order: 1, name: "分離冷凝", description: "以分離冷凝提升汽機效率。", baseCost: 49, effects: [] },
          { order: 2, name: "復動汽缸", description: "以復動汽缸雙向出力。", baseCost: 65, effects: [] },
          { order: 3, name: "飛輪調速", description: "以飛輪穩定轉速。", baseCost: 82, effects: [] },
          { order: 4, name: "離心調速", description: "以離心調速器控轉。", baseCost: 98, effects: [] },
          { order: 5, name: "高壓蒸汽", description: "運用高壓蒸汽增力。", baseCost: 114, effects: [] },
          { order: 6, name: "汽機傳動", description: "以汽機驅動廠房機械。", baseCost: 130, effects: [] },
          { order: 7, name: "曲軸旋轉", description: "以曲軸轉換為旋轉動力。", baseCost: 147, effects: [] },
          { order: 8, name: "汽鎚鍛壓", description: "以汽鎚鍛壓大件。", baseCost: 163, effects: [] },
          { order: 9, name: "冷凝節煤", description: "改良冷凝節省燃煤。", baseCost: 179, effects: [] },
          { order: 10, name: "動力工廠", description: "建汽力工廠集中生產。", baseCost: 195, effects: [] },
        ],
      },
      {
        lineKey: "manufactory",
        lineLabel: "工場製造",
        lineKind: "main",
        nodes: [
          { order: 1, name: "分工流程", description: "以分工細化製造流程。", baseCost: 49, effects: [] },
          { order: 2, name: "標準零件", description: "製作可互換標準零件。", baseCost: 65, effects: [] },
          { order: 3, name: "機械紡紗", description: "以機械紡紗大量出線。", baseCost: 82, effects: [] },
          { order: 4, name: "飛梭織布", description: "以飛梭加速織布。", baseCost: 98, effects: [] },
          { order: 5, name: "車床切削", description: "以車床精密切削金屬。", baseCost: 114, effects: [] },
          { order: 6, name: "鑽床鏜孔", description: "以鑽床鏜製精孔。", baseCost: 130, effects: [] },
          { order: 7, name: "模鍛成型", description: "以模鍛批量成型。", baseCost: 147, effects: [] },
          { order: 8, name: "量規檢驗", description: "以量規檢驗品質。", baseCost: 163, effects: [] },
          { order: 9, name: "工廠佈局", description: "規劃工廠動線佈局。", baseCost: 179, effects: [] },
          { order: 10, name: "產線編排", description: "編排連續生產線。", baseCost: 195, effects: [] },
        ],
      },
      {
        lineKey: "canals",
        lineLabel: "運河漕運",
        lineKind: "branch",
        branchFrom: { lineKey: "steam_power", order: 5 },
        nodes: [
          { order: 1, name: "船閘升降", description: "以船閘升降通航。", baseCost: 39, effects: [{ target: "productivity", value: 2 }] },
          { order: 2, name: "運河開鑿", description: "開鑿運河連通水系。", baseCost: 59, effects: [] },
          { order: 3, name: "拖曳纖道", description: "沿岸設纖道拖曳船隻。", baseCost: 78, effects: [{ target: "techPoints", value: 2 }] },
          { order: 4, name: "內河港埠", description: "建內河港埠轉運貨物。", baseCost: 98, effects: [] },
        ],
      },
    ],
  },
  {
    eraSlug: "industrial",
    lines: [
      {
        lineKey: "factory",
        lineLabel: "工廠體系",
        lineKind: "main",
        nodes: [
          { order: 1, name: "蒸汽廠機", description: "以蒸汽驅動廠房機組。", baseCost: 76, effects: [] },
          { order: 2, name: "機械織廠", description: "建機械織廠量產布匹。", baseCost: 101, effects: [] },
          { order: 3, name: "煉鋼轉爐", description: "以轉爐大量煉鋼。", baseCost: 126, effects: [] },
          { order: 4, name: "鍛壓機床", description: "以鍛壓機床成型鋼件。", baseCost: 151, effects: [] },
          { order: 5, name: "傳送皮帶", description: "以皮帶傳輸動力至機。", baseCost: 176, effects: [] },
          {
            order: 6,
            name: "工業化",
            description: "全面機械化大生產，產能空前躍升。",
            baseCost: 252,
            keySlug: "industrialization",
            effects: [{ target: "productivity", value: 15 }],
          },
          { order: 7, name: "鑄鐵樑架", description: "以鑄鐵樑架建廠房。", baseCost: 227, effects: [] },
          { order: 8, name: "機器製機", description: "以機器製造機器。", baseCost: 252, effects: [] },
          { order: 9, name: "工廠聚落", description: "工廠聚集成工業區。", baseCost: 277, effects: [] },
          { order: 10, name: "生產調度", description: "統籌生產排程調度。", baseCost: 302, effects: [] },
        ],
      },
      {
        lineKey: "railway",
        lineLabel: "鐵路運輸",
        lineKind: "main",
        nodes: [
          { order: 1, name: "鐵軌鋪設", description: "鋪設鐵軌承載重運。", baseCost: 76, effects: [] },
          { order: 2, name: "蒸汽機車", description: "以蒸汽機車牽引列車。", baseCost: 101, effects: [] },
          { order: 3, name: "車廂聯結", description: "聯結車廂編組列車。", baseCost: 126, effects: [] },
          { order: 4, name: "鐵橋跨谷", description: "架鐵橋跨越溝谷。", baseCost: 151, effects: [] },
          { order: 5, name: "隧道穿山", description: "開鑿隧道貫通山嶺。", baseCost: 176, effects: [] },
          { order: 6, name: "號誌調度", description: "以號誌調度列車運行。", baseCost: 202, effects: [] },
          { order: 7, name: "車站樞紐", description: "建車站作運輸樞紐。", baseCost: 227, effects: [] },
          { order: 8, name: "貨運編組", description: "編組貨運列車運料。", baseCost: 252, effects: [] },
          { order: 9, name: "時刻編排", description: "編排列車時刻表。", baseCost: 277, effects: [] },
          { order: 10, name: "鐵路網絡", description: "構建鐵路運輸網絡。", baseCost: 302, effects: [] },
        ],
      },
      {
        lineKey: "coal_gas",
        lineLabel: "煤氣照明",
        lineKind: "branch",
        branchFrom: { lineKey: "factory", order: 5 },
        nodes: [
          { order: 1, name: "煤氣製取", description: "乾餾煤炭製取燃氣。", baseCost: 60, effects: [{ target: "productivity", value: 2 }] },
          { order: 2, name: "燃氣街燈", description: "以燃氣點亮街燈。", baseCost: 91, effects: [] },
          { order: 3, name: "管線輸氣", description: "以管線輸送燃氣。", baseCost: 121, effects: [{ target: "techPoints", value: 2 }] },
          { order: 4, name: "焦炭煉製", description: "煉製焦炭供高爐用。", baseCost: 151, effects: [] },
        ],
      },
    ],
  },
  {
    eraSlug: "ww1",
    lines: [
      {
        lineKey: "electric_power",
        lineLabel: "電力應用",
        lineKind: "main",
        nodes: [
          { order: 1, name: "發電機組", description: "以發電機產生電流。", baseCost: 78, effects: [] },
          { order: 2, name: "直流輸電", description: "以直流輸配電力。", baseCost: 104, effects: [] },
          { order: 3, name: "交流電網", description: "建交流電網遠距輸電。", baseCost: 130, effects: [] },
          { order: 4, name: "電動馬達", description: "以電動馬達驅動機械。", baseCost: 156, effects: [] },
          { order: 5, name: "白熾燈泡", description: "以白熾燈泡照明。", baseCost: 182, effects: [] },
          { order: 6, name: "變壓調電", description: "以變壓器調節電壓。", baseCost: 208, effects: [] },
          { order: 7, name: "電解精煉", description: "以電解法精煉金屬。", baseCost: 234, effects: [] },
          { order: 8, name: "電話通訊", description: "以電話傳遞語音。", baseCost: 260, effects: [] },
          { order: 9, name: "電報網路", description: "以電報快速傳訊。", baseCost: 286, effects: [] },
          { order: 10, name: "電力調度", description: "統籌電力供需調度。", baseCost: 312, effects: [] },
        ],
      },
      {
        lineKey: "chemical_industry",
        lineLabel: "化學工業",
        lineKind: "main",
        nodes: [
          { order: 1, name: "合成染料", description: "合成人造染料量產。", baseCost: 78, effects: [] },
          { order: 2, name: "硫酸製程", description: "以接觸法製硫酸。", baseCost: 104, effects: [] },
          { order: 3, name: "合成氨氣", description: "以合成法固氮製氨。", baseCost: 130, effects: [] },
          { order: 4, name: "化肥量產", description: "量產化肥增益糧產。", baseCost: 156, effects: [] },
          { order: 5, name: "炸藥製造", description: "製造工業炸藥供工程。", baseCost: 182, effects: [] },
          { order: 6, name: "石油分餾", description: "分餾石油取多種產物。", baseCost: 208, effects: [] },
          { order: 7, name: "橡膠硫化", description: "硫化橡膠製耐用件。", baseCost: 234, effects: [] },
          { order: 8, name: "塑料初創", description: "合成早期塑膠材料。", baseCost: 260, effects: [] },
          { order: 9, name: "電石乙炔", description: "以電石製乙炔氣。", baseCost: 286, effects: [] },
          { order: 10, name: "化工廠制", description: "建化工廠連續生產。", baseCost: 312, effects: [] },
        ],
      },
      {
        lineKey: "automobile",
        lineLabel: "汽車運輸",
        lineKind: "branch",
        branchFrom: { lineKey: "chemical_industry", order: 5 },
        nodes: [
          { order: 1, name: "內燃引擎", description: "以內燃引擎驅動車輛。", baseCost: 62, effects: [{ target: "productivity", value: 2 }] },
          { order: 2, name: "汽車量產", description: "以流水線量產汽車。", baseCost: 94, effects: [{ target: "techPoints", value: 1 }] },
          { order: 3, name: "橡膠輪胎", description: "以充氣輪胎行駛平穩。", baseCost: 125, effects: [] },
          { order: 4, name: "公路鋪面", description: "鋪設瀝青公路路面。", baseCost: 156, effects: [{ target: "productivity", value: 1 }] },
        ],
      },
    ],
  },
  {
    eraSlug: "ww2",
    lines: [
      {
        lineKey: "electrification_line",
        lineLabel: "全面電氣化",
        lineKind: "main",
        nodes: [
          { order: 1, name: "電網擴張", description: "擴張電網覆蓋城鄉。", baseCost: 95, effects: [] },
          { order: 2, name: "水力發電", description: "以水壩發電供能。", baseCost: 126, effects: [] },
          { order: 3, name: "火力電廠", description: "建火力電廠大量發電。", baseCost: 158, effects: [] },
          { order: 4, name: "高壓輸電", description: "以高壓長線輸電。", baseCost: 189, effects: [] },
          { order: 5, name: "電機標準", description: "訂立電機規格標準。", baseCost: 221, effects: [] },
          {
            order: 6,
            name: "電氣化",
            description: "生產與生活全面電氣化，效率與研究並進。",
            baseCost: 315,
            keySlug: "electrification",
            effects: [
              { target: "productivity", value: 10 },
              { target: "techPoints", value: 8 },
            ],
          },
          { order: 7, name: "感應電機", description: "以感應電機驅動產線。", baseCost: 284, effects: [] },
          { order: 8, name: "電氣照明", description: "廠房全面電氣照明。", baseCost: 315, effects: [] },
          { order: 9, name: "配電變所", description: "建變電所配送電力。", baseCost: 347, effects: [] },
          { order: 10, name: "電力管理", description: "集中管理電力調度。", baseCost: 378, effects: [] },
        ],
      },
      {
        lineKey: "massproduction",
        lineLabel: "大量生產",
        lineKind: "main",
        nodes: [
          { order: 1, name: "流水裝配", description: "以流水線裝配整機。", baseCost: 95, effects: [] },
          { order: 2, name: "沖壓成型", description: "以沖壓機成型鈑金。", baseCost: 126, effects: [] },
          { order: 3, name: "焊接組裝", description: "以電焊組裝結構。", baseCost: 158, effects: [] },
          { order: 4, name: "精密公差", description: "控制精密公差配合。", baseCost: 189, effects: [] },
          { order: 5, name: "機床自動", description: "以自動機床連續加工。", baseCost: 221, effects: [] },
          { order: 6, name: "品管抽檢", description: "以統計抽檢管控品質。", baseCost: 252, effects: [] },
          { order: 7, name: "模具量產", description: "以模具大量翻製件。", baseCost: 284, effects: [] },
          { order: 8, name: "輸送機構", description: "以輸送機構串接工序。", baseCost: 315, effects: [] },
          { order: 9, name: "工時研究", description: "研究工時優化效率。", baseCost: 347, effects: [] },
          { order: 10, name: "產能擴充", description: "擴充產線提升產能。", baseCost: 378, effects: [] },
        ],
      },
      {
        lineKey: "aviation_industry",
        lineLabel: "航空製造",
        lineKind: "branch",
        branchFrom: { lineKey: "massproduction", order: 5 },
        nodes: [
          { order: 1, name: "鋁合金材", description: "以輕鋁合金製機體。", baseCost: 76, effects: [{ target: "productivity", value: 2 }] },
          { order: 2, name: "活塞航發", description: "以活塞發動機推進飛機。", baseCost: 113, effects: [] },
          { order: 3, name: "機翼氣動", description: "優化機翼氣動外型。", baseCost: 151, effects: [{ target: "techPoints", value: 2 }] },
          { order: 4, name: "量產機廠", description: "建量產飛機的航空廠。", baseCost: 189, effects: [] },
        ],
      },
    ],
  },
  {
    eraSlug: "cold_war",
    lines: [
      {
        lineKey: "nuclear",
        lineLabel: "核能發展",
        lineKind: "main",
        nodes: [
          { order: 1, name: "核分裂鏈", description: "掌握核分裂鏈式反應。", baseCost: 168, effects: [] },
          { order: 2, name: "反應爐芯", description: "建核反應爐堆芯。", baseCost: 224, effects: [] },
          { order: 3, name: "濃縮鈾料", description: "濃縮鈾料供反應爐。", baseCost: 280, effects: [] },
          { order: 4, name: "冷卻迴路", description: "設冷卻迴路導出堆熱。", baseCost: 336, effects: [] },
          { order: 5, name: "核能發電", description: "以核能發電大量供能。", baseCost: 392, effects: [] },
          { order: 6, name: "控制棒調", description: "以控制棒調節反應。", baseCost: 448, effects: [] },
          { order: 7, name: "廢料處理", description: "處理封存核廢料。", baseCost: 504, effects: [] },
          { order: 8, name: "安全圍阻", description: "建圍阻體確保安全。", baseCost: 560, effects: [] },
          { order: 9, name: "增殖反應", description: "以增殖爐再生燃料。", baseCost: 616, effects: [] },
          { order: 10, name: "核電併網", description: "核電併入國家電網。", baseCost: 672, effects: [] },
        ],
      },
      {
        lineKey: "computing",
        lineLabel: "計算機技",
        lineKind: "main",
        nodes: [
          { order: 1, name: "電子管機", description: "以電子管建計算機。", baseCost: 168, effects: [] },
          { order: 2, name: "電晶體件", description: "以電晶體取代電子管。", baseCost: 224, effects: [] },
          { order: 3, name: "磁芯記憶", description: "以磁芯儲存資料。", baseCost: 280, effects: [] },
          { order: 4, name: "積體電路", description: "將電路集成於晶片。", baseCost: 336, effects: [] },
          { order: 5, name: "程式語言", description: "以高階語言編寫程式。", baseCost: 392, effects: [] },
          { order: 6, name: "磁帶儲存", description: "以磁帶儲存大量資料。", baseCost: 448, effects: [] },
          { order: 7, name: "分時系統", description: "以分時系統多工運算。", baseCost: 504, effects: [] },
          { order: 8, name: "數值控制", description: "以數控機床自動加工。", baseCost: 560, effects: [] },
          { order: 9, name: "主機運算", description: "以大型主機集中運算。", baseCost: 616, effects: [] },
          { order: 10, name: "網路互聯", description: "建早期網路互聯電腦。", baseCost: 672, effects: [] },
        ],
      },
      {
        lineKey: "aerospace",
        lineLabel: "航太運輸",
        lineKind: "branch",
        branchFrom: { lineKey: "computing", order: 5 },
        nodes: [
          { order: 1, name: "噴射引擎", description: "以噴射引擎推進航機。", baseCost: 134, effects: [{ target: "productivity", value: 2 }] },
          { order: 2, name: "火箭推進", description: "以火箭推進脫離大氣。", baseCost: 202, effects: [{ target: "techPoints", value: 2 }] },
          { order: 3, name: "貨櫃運輸", description: "以標準貨櫃聯運貨物。", baseCost: 269, effects: [{ target: "productivity", value: 1 }] },
          { order: 4, name: "高速公路", description: "建高速公路網通行。", baseCost: 336, effects: [] },
        ],
      },
    ],
  },
  {
    eraSlug: "modern",
    lines: [
      {
        lineKey: "digital",
        lineLabel: "數位資訊",
        lineKind: "main",
        nodes: [
          { order: 1, name: "微處理器", description: "以微處理器驅動裝置。", baseCost: 375, effects: [] },
          { order: 2, name: "個人電腦", description: "普及個人電腦運算。", baseCost: 500, effects: [] },
          { order: 3, name: "區域網路", description: "以區域網路連結電腦。", baseCost: 625, effects: [] },
          { order: 4, name: "全球網際", description: "建全球網際網路。", baseCost: 750, effects: [] },
          { order: 5, name: "光纖通訊", description: "以光纖高速傳輸資料。", baseCost: 875, effects: [] },
          { order: 6, name: "行動通訊", description: "以行動網路隨處連線。", baseCost: 1000, effects: [] },
          { order: 7, name: "雲端運算", description: "以雲端集中運算資源。", baseCost: 1125, effects: [] },
          { order: 8, name: "大數據析", description: "以大數據分析決策。", baseCost: 1250, effects: [] },
          { order: 9, name: "資料中心", description: "建資料中心承載服務。", baseCost: 1375, effects: [] },
          { order: 10, name: "數位平台", description: "建數位平台整合服務。", baseCost: 1500, effects: [] },
        ],
      },
      {
        lineKey: "automation",
        lineLabel: "智慧製造",
        lineKind: "main",
        nodes: [
          { order: 1, name: "工業機械臂", description: "以機械臂自動作業。", baseCost: 375, effects: [] },
          { order: 2, name: "數控加工", description: "以數控中心精密加工。", baseCost: 500, effects: [] },
          { order: 3, name: "產線機器人", description: "以機器人組裝產線。", baseCost: 625, effects: [] },
          { order: 4, name: "感測回饋", description: "以感測器回饋控制。", baseCost: 750, effects: [] },
          { order: 5, name: "精實生產", description: "以精實方法減少浪費。", baseCost: 875, effects: [] },
          { order: 6, name: "供應鏈整合", description: "整合供應鏈即時協作。", baseCost: 1000, effects: [] },
          { order: 7, name: "積層製造", description: "以積層列印製造零件。", baseCost: 1125, effects: [] },
          { order: 8, name: "數位孿生", description: "以數位孿生模擬產線。", baseCost: 1250, effects: [] },
          { order: 9, name: "智慧工廠", description: "建智慧工廠自動運行。", baseCost: 1375, effects: [] },
          { order: 10, name: "彈性製造", description: "以彈性系統快速換產。", baseCost: 1500, effects: [] },
        ],
      },
      {
        lineKey: "renewables",
        lineLabel: "再生能源",
        lineKind: "branch",
        branchFrom: { lineKey: "automation", order: 5 },
        nodes: [
          { order: 1, name: "太陽光電", description: "以光電板轉換陽光。", baseCost: 300, effects: [{ target: "productivity", value: 2 }] },
          { order: 2, name: "風力發電", description: "以風機發電供能。", baseCost: 450, effects: [{ target: "techPoints", value: 2 }] },
          { order: 3, name: "電池儲能", description: "以電池儲存電能。", baseCost: 600, effects: [{ target: "productivity", value: 1 }] },
          { order: 4, name: "智慧電網", description: "以智慧電網調度用電。", baseCost: 750, effects: [] },
        ],
      },
    ],
  },
  {
    eraSlug: "future",
    lines: [
      {
        lineKey: "fusion",
        lineLabel: "聚變能源",
        lineKind: "main",
        nodes: [
          { order: 1, name: "電漿約束", description: "以磁場約束高溫電漿。", baseCost: 986, effects: [] },
          { order: 2, name: "核聚變爐", description: "建核聚變反應爐。", baseCost: 1314, effects: [] },
          { order: 3, name: "超導磁體", description: "以超導磁體約束電漿。", baseCost: 1643, effects: [] },
          { order: 4, name: "氘氚燃料", description: "以氘氚為聚變燃料。", baseCost: 1971, effects: [] },
          { order: 5, name: "聚變點火", description: "達成聚變自持點火。", baseCost: 2300, effects: [] },
          { order: 6, name: "能量增益", description: "實現淨能量增益輸出。", baseCost: 2628, effects: [] },
          { order: 7, name: "直接發電", description: "由聚變直接轉為電能。", baseCost: 2957, effects: [] },
          { order: 8, name: "商轉聚變", description: "聚變電廠商業運轉。", baseCost: 3285, effects: [] },
          { order: 9, name: "反物質儲", description: "儲存微量反物質能源。", baseCost: 3614, effects: [] },
          { order: 10, name: "恆星能場", description: "構築恆星級能量場。", baseCost: 3942, effects: [] },
        ],
      },
      {
        lineKey: "ai_tech",
        lineLabel: "人工智慧",
        lineKind: "main",
        nodes: [
          { order: 1, name: "神經網路", description: "以神經網路學習模式。", baseCost: 986, effects: [] },
          { order: 2, name: "深度學習", description: "以深度學習辨識萬象。", baseCost: 1314, effects: [] },
          { order: 3, name: "通用智能", description: "邁向通用人工智慧。", baseCost: 1643, effects: [] },
          { order: 4, name: "量子運算", description: "以量子位元加速運算。", baseCost: 1971, effects: [] },
          { order: 5, name: "自主決策", description: "以自主系統自行決策。", baseCost: 2300, effects: [] },
          { order: 6, name: "全自動廠", description: "以全自動系統運行工廠。", baseCost: 2628, effects: [] },
          { order: 7, name: "分散智網", description: "建分散式智慧網路。", baseCost: 2957, effects: [] },
          { order: 8, name: "腦機介面", description: "以腦機介面直連運算。", baseCost: 3285, effects: [] },
          { order: 9, name: "群體智能", description: "以群體智能協同運作。", baseCost: 3614, effects: [] },
          { order: 10, name: "奇點運算", description: "逼近運算能力的奇點。", baseCost: 3942, effects: [] },
        ],
      },
      {
        lineKey: "nanotech",
        lineLabel: "奈米製造",
        lineKind: "branch",
        branchFrom: { lineKey: "ai_tech", order: 5 },
        nodes: [
          { order: 1, name: "奈米材料", description: "以奈米材料改性物質。", baseCost: 788, effects: [{ target: "productivity", value: 2 }] },
          { order: 2, name: "分子組裝", description: "以分子組裝精造結構。", baseCost: 1183, effects: [{ target: "techPoints", value: 2 }] },
          { order: 3, name: "自我修復", description: "以自修復材料延壽。", baseCost: 1577, effects: [{ target: "productivity", value: 1 }] },
          { order: 4, name: "原子製造", description: "以原子級精度製造。", baseCost: 1971, effects: [] },
        ],
      },
    ],
  },
];
