// Task #469 — 科技樹預設種子（social 領域，前半）

import type { SocialTechEffect } from "@workspace/db";
import type { TechTreeSeedEra } from "./types";

export const SOCIAL_ERAS_EARLY: TechTreeSeedEra<SocialTechEffect>[] = [
  {
    eraSlug: "classical",
    lines: [
      {
        lineKey: "gov",
        lineLabel: "治理與律法",
        lineKind: "main",
        nodes: [
          { order: 1, name: "部族議會", description: "部族長老共議部務，政事初具雛形。", baseCost: 6, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 2, name: "習慣法規", description: "將口耳相傳的慣例化為部族公認的規矩。", baseCost: 8, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 3, name: "城邦公民權", description: "界定城邦成員的權利與義務。", baseCost: 10, effects: [{ target: "populationGrowth", value: 1 }] },
          { order: 4, name: "長老會議", description: "由資深族老組成議事機構，仲裁紛爭。", baseCost: 12, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 5, name: "成文法典", description: "將律令刻於石柱公示，人人有法可循。", baseCost: 14, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 6, name: "政治哲學", description: "系統思辨理想政體，奠定治國之道；解鎖顧問席位。", baseCost: 20, effects: [{ target: "enableAdvisorSlot", value: 1 }, { target: "taxEfficiency", value: 1 }], keySlug: "political_philosophy" },
          { order: 7, name: "元老院制", description: "貴族共議國政，制衡首領權力。", baseCost: 18, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 8, name: "稅賦徵收", description: "建立定額徵稅，充實國庫。", baseCost: 20, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 9, name: "行政區劃", description: "依疆域劃分郡縣，便於統轄。", baseCost: 22, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 10, name: "公共財政", description: "統籌歲入歲出，支應城邦開支。", baseCost: 24, effects: [{ target: "taxEfficiency", value: 2 }] },
        ],
      },
      {
        lineKey: "thought",
        lineLabel: "思想與信仰",
        lineKind: "main",
        nodes: [
          { order: 1, name: "口傳史詩", description: "吟遊者傳誦先祖功業，凝聚族群記憶。", baseCost: 6, effects: [{ target: "techPoints", value: 1 }] },
          { order: 2, name: "神話崇拜", description: "敬奉自然神祇，安定人心。", baseCost: 8, effects: [{ target: "warWearinessGrowth", value: -5 }] },
          { order: 3, name: "祭司階層", description: "專司祭祀者形成，主持禮儀。", baseCost: 10, effects: [{ target: "warWearinessGrowth", value: -5 }] },
          { order: 4, name: "自然哲學", description: "探問萬物本源，思辨天地之理。", baseCost: 12, effects: [{ target: "techPoints", value: 1 }] },
          { order: 5, name: "修辭之術", description: "講究言辭說服，論辯蔚然成風。", baseCost: 14, effects: [{ target: "techPoints", value: 1 }] },
          { order: 6, name: "倫理學說", description: "論究德行善惡，教化人倫。", baseCost: 16, effects: [{ target: "warWearinessGrowth", value: -5 }] },
          { order: 7, name: "編年史學", description: "按年記事，留存邦國興衰。", baseCost: 18, effects: [{ target: "techPoints", value: 1 }] },
          { order: 8, name: "幾何原理", description: "以圖形推演度量，測地建物。", baseCost: 20, effects: [{ target: "techPoints", value: 1 }] },
          { order: 9, name: "悲喜戲劇", description: "於劇場搬演人生百態，寓教於樂。", baseCost: 22, effects: [{ target: "warWearinessGrowth", value: -5 }] },
          { order: 10, name: "圖書典藏", description: "蒐羅卷帙建立藏書，傳承學問。", baseCost: 24, effects: [{ target: "techPoints", value: 1 }] },
        ],
      },
      {
        lineKey: "edu",
        lineLabel: "學術萌芽",
        lineKind: "branch",
        branchFrom: { lineKey: "thought", order: 4 },
        nodes: [
          { order: 1, name: "私塾講學", description: "學者收徒授業，開啟私學風氣。", baseCost: 6, effects: [{ target: "techPoints", value: 1 }] },
          { order: 2, name: "辯論學園", description: "門徒群聚論道，切磋思辨。", baseCost: 8, effects: [{ target: "techPoints", value: 1 }] },
          { order: 3, name: "抄寫工坊", description: "雇人謄抄典籍，廣布知識。", baseCost: 10, effects: [{ target: "techPoints", value: 1 }] },
          { order: 4, name: "學者資助", description: "城邦供養賢士，鼓勵鑽研。", baseCost: 12, effects: [{ target: "techPoints", value: 2 }] },
        ],
      },
    ],
  },
  {
    eraSlug: "roman",
    lines: [
      {
        lineKey: "gov",
        lineLabel: "帝國治理",
        lineKind: "main",
        nodes: [
          { order: 1, name: "執政官制", description: "兩位執政官共掌大權，年年輪替。", baseCost: 10, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 2, name: "行省總督", description: "派任總督治理征服之地。", baseCost: 13, effects: [{ target: "taxEfficiency", value: 2 }] },
          { order: 3, name: "公民大會", description: "平民集會表決重大公務。", baseCost: 17, effects: [{ target: "populationGrowth", value: 1 }] },
          { order: 4, name: "護民官職", description: "設官維護平民權益，制衡貴族。", baseCost: 20, effects: [{ target: "warWearinessGrowth", value: -5 }] },
          { order: 5, name: "十二表法", description: "公布成文法版，明定民刑之律。", baseCost: 24, effects: [{ target: "taxEfficiency", value: 2 }] },
          { order: 6, name: "稅制改革", description: "整頓賦稅包收，穩定歲入。", baseCost: 27, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 7, name: "部落革新", description: "統合部族力量煥發生機，廣拓營造之能；解鎖建築槽。", baseCost: 38, effects: [{ target: "enableBuildingSlots", value: 5 }, { target: "taxEfficiency", value: 3 }], keySlug: "tribal_innovation" },
          { order: 8, name: "公路網絡", description: "修築帝國大道，政令暢達四方。", baseCost: 34, effects: [{ target: "taxEfficiency", value: 2 }] },
          { order: 9, name: "郵驛系統", description: "設驛站傳遞公文，通達邊陲。", baseCost: 37, effects: [{ target: "techPoints", value: 1 }] },
          { order: 10, name: "帝國官僚", description: "常設文官體系，統攝龐大版圖。", baseCost: 40, effects: [{ target: "taxEfficiency", value: 2 }] },
        ],
      },
      {
        lineKey: "faith",
        lineLabel: "信仰與文化",
        lineKind: "main",
        nodes: [
          { order: 1, name: "萬神殿宇", description: "廣納諸神共祀一殿，包容信仰。", baseCost: 10, effects: [{ target: "warWearinessGrowth", value: -5 }] },
          { order: 2, name: "祭祀曆法", description: "依節令行祭典，規範歲時。", baseCost: 13, effects: [{ target: "populationGrowth", value: 1 }] },
          { order: 3, name: "神諭問卜", description: "藉徵兆卜問吉凶，指引國事。", baseCost: 17, effects: [{ target: "warWearinessGrowth", value: -5 }] },
          { order: 4, name: "競技慶典", description: "舉辦競技娛民，凝聚人心。", baseCost: 20, effects: [{ target: "warWearinessGrowth", value: -10 }] },
          { order: 5, name: "拉丁文教", description: "通行拉丁文字，統一書面。", baseCost: 24, effects: [{ target: "techPoints", value: 1 }] },
          { order: 6, name: "世界宗教", description: "普世信仰橫掃帝國，教化萬民；啟用國家宗教與宗教滿意。", baseCost: 34, effects: [{ target: "enableNationalReligion", value: 1 }, { target: "enableReligionSatisfaction", value: 1 }, { target: "taxEfficiency", value: 2 }], keySlug: "world_religion" },
          { order: 7, name: "神學辯難", description: "教士辨析教義，確立正信。", baseCost: 30, effects: [{ target: "techPoints", value: 1 }] },
          { order: 8, name: "殉道傳記", description: "記述先賢殉道，激勵信眾。", baseCost: 34, effects: [{ target: "warWearinessGrowth", value: -5 }] },
          { order: 9, name: "教區組織", description: "依地劃分教區，牧養信徒。", baseCost: 37, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 10, name: "修院規章", description: "訂立清規戒律，安頓修行。", baseCost: 40, effects: [{ target: "techPoints", value: 1 }] },
        ],
      },
      {
        lineKey: "media",
        lineLabel: "傳抄之風",
        lineKind: "branch",
        branchFrom: { lineKey: "faith", order: 5 },
        nodes: [
          { order: 1, name: "抄經工房", description: "修士謄抄經卷，傳布信仰。", baseCost: 10, effects: [{ target: "techPoints", value: 1 }] },
          { order: 2, name: "圖籍編目", description: "整理卷冊分類，便於檢索。", baseCost: 13, effects: [{ target: "techPoints", value: 1 }] },
          { order: 3, name: "演說廣場", description: "於廣場公開演說，傳播思潮。", baseCost: 17, effects: [{ target: "warWearinessGrowth", value: -5 }] },
          { order: 4, name: "銘文石刻", description: "刻銘立碑，昭告功業與律令。", baseCost: 20, effects: [{ target: "buildingSlots", value: 1 }] },
        ],
      },
    ],
  },
  {
    eraSlug: "early_medieval",
    lines: [
      {
        lineKey: "gov",
        lineLabel: "封建秩序",
        lineKind: "main",
        nodes: [
          { order: 1, name: "采邑封授", description: "領主授地予封臣，換取效忠。", baseCost: 14, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 2, name: "莊園制度", description: "以莊園為單位組織農耕與治理。", baseCost: 18, effects: [{ target: "taxEfficiency", value: 2 }] },
          { order: 3, name: "封臣效忠", description: "封臣宣誓義務，構成封建網絡。", baseCost: 23, effects: [{ target: "warWearinessGrowth", value: -5 }] },
          { order: 4, name: "領主法庭", description: "領主主持審判，裁決封地糾紛。", baseCost: 27, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 5, name: "騎士誓約", description: "武士立誓效忠，維護封建道義。", baseCost: 32, effects: [{ target: "warWearinessGrowth", value: -5 }] },
          { order: 6, name: "采地繼承", description: "訂立世襲之法，穩固封建傳承。", baseCost: 36, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 7, name: "王室特許", description: "君王頒發特許狀，授予城鎮權利。", baseCost: 41, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 8, name: "巡迴審判", description: "派法官巡行各地，統一裁決。", baseCost: 45, effects: [{ target: "taxEfficiency", value: 2 }] },
          { order: 9, name: "王家議事", description: "貴族教士共議國政，輔弼君王。", baseCost: 50, effects: [{ target: "taxEfficiency", value: 2 }] },
          { order: 10, name: "常備稅捐", description: "徵收固定稅課，供養王廷。", baseCost: 54, effects: [{ target: "taxEfficiency", value: 3 }] },
        ],
      },
      {
        lineKey: "learn",
        lineLabel: "學術與信仰",
        lineKind: "main",
        nodes: [
          { order: 1, name: "修道院學", description: "修士於院中傳習經籍。", baseCost: 14, effects: [{ target: "techPoints", value: 1 }] },
          { order: 2, name: "抄本繕寫", description: "精心繕寫典籍，保存古學。", baseCost: 18, effects: [{ target: "techPoints", value: 1 }] },
          { order: 3, name: "教會拉丁", description: "以拉丁文為學術與禮拜之語。", baseCost: 23, effects: [{ target: "techPoints", value: 1 }] },
          { order: 4, name: "七藝課程", description: "教授文法修辭等自由七藝。", baseCost: 27, effects: [{ target: "techPoints", value: 2 }] },
          { order: 5, name: "主教座堂", description: "建立主教座堂，統轄教區學務。", baseCost: 32, effects: [{ target: "warWearinessGrowth", value: -5 }] },
          { order: 6, name: "大學制度", description: "學者行會設立大學，授予學位；擴增建築槽。", baseCost: 45, effects: [{ target: "buildingSlots", value: 5 }], keySlug: "university_system" },
          { order: 7, name: "經院哲學", description: "以理性辯證調和信仰與學問。", baseCost: 41, effects: [{ target: "techPoints", value: 2 }] },
          { order: 8, name: "神學總綱", description: "系統整理教義，集神學之大成。", baseCost: 45, effects: [{ target: "warWearinessGrowth", value: -5 }] },
          { order: 9, name: "教令彙編", description: "匯集教會法規，規範信眾。", baseCost: 50, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 10, name: "學位授予", description: "頒授學位資格，確立學術權威。", baseCost: 54, effects: [{ target: "techPoints", value: 2 }] },
        ],
      },
      {
        lineKey: "health",
        lineLabel: "濟貧與醫護",
        lineKind: "branch",
        branchFrom: { lineKey: "learn", order: 5 },
        nodes: [
          { order: 1, name: "修院診護", description: "修士照料病患，設院施藥。", baseCost: 14, effects: [{ target: "populationGrowth", value: 1 }] },
          { order: 2, name: "濟貧院所", description: "設立救濟之所，收容貧病。", baseCost: 18, effects: [{ target: "populationGrowth", value: 1 }] },
          { order: 3, name: "藥草園圃", description: "栽植藥草研製方劑。", baseCost: 23, effects: [{ target: "populationGrowth", value: 1 }] },
        ],
      },
    ],
  },
  {
    eraSlug: "high_medieval",
    lines: [
      {
        lineKey: "society",
        lineLabel: "社會制度",
        lineKind: "main",
        nodes: [
          { order: 1, name: "城市自治", description: "市民爭取自治特許，擺脫領主。", baseCost: 19, effects: [{ target: "taxEfficiency", value: 2 }] },
          { order: 2, name: "商人公會", description: "商賈結社互助，壟斷貿易。", baseCost: 26, effects: [{ target: "taxEfficiency", value: 2 }] },
          { order: 3, name: "手工行會", description: "匠人結會規範技藝與價格。", baseCost: 32, effects: [{ target: "taxEfficiency", value: 2 }] },
          { order: 4, name: "市集特權", description: "城鎮獲准設市，繁榮商貿。", baseCost: 38, effects: [{ target: "taxEfficiency", value: 3 }] },
          { order: 5, name: "學徒制度", description: "匠師收徒授藝，傳承手工。", baseCost: 45, effects: [{ target: "techPoints", value: 1 }] },
          { order: 6, name: "市政議會", description: "市民選任議事，管理城務。", baseCost: 51, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 7, name: "行會革新", description: "行會制度勃興壯大營造與稅收，並紓解厭戰；擴增建築槽。", baseCost: 72, effects: [{ target: "buildingSlots", value: 10 }, { target: "taxEfficiency", value: 5 }, { target: "warWearinessGrowth", value: -50 }], keySlug: "guild_innovation" },
          { order: 8, name: "城市法典", description: "訂立市民法規，保障工商。", baseCost: 64, effects: [{ target: "taxEfficiency", value: 2 }] },
          { order: 9, name: "匯兌票據", description: "以票據通匯，便利遠程貿易。", baseCost: 70, effects: [{ target: "taxEfficiency", value: 3 }] },
          { order: 10, name: "商法慣例", description: "商人習慣法通行各地市集。", baseCost: 77, effects: [{ target: "taxEfficiency", value: 3 }] },
        ],
      },
      {
        lineKey: "thought",
        lineLabel: "思想與信仰",
        lineKind: "main",
        nodes: [
          { order: 1, name: "托缽修會", description: "苦行修士遊方傳道，親近民眾。", baseCost: 19, effects: [{ target: "warWearinessGrowth", value: -5 }] },
          { order: 2, name: "十字精神", description: "宗教熱忱驅動遠征與朝聖。", baseCost: 26, effects: [{ target: "warWearinessGrowth", value: -5 }] },
          { order: 3, name: "聖徒崇敬", description: "敬奉聖徒遺物，寄託虔信。", baseCost: 32, effects: [{ target: "warWearinessGrowth", value: -5 }] },
          { order: 4, name: "煉獄教義", description: "闡發煉獄之說，勸人行善。", baseCost: 38, effects: [{ target: "warWearinessGrowth", value: -5 }] },
          { order: 5, name: "宗教裁判", description: "設立裁判所糾察異端。", baseCost: 45, effects: [{ target: "warWearinessGrowth", value: -10 }] },
          { order: 6, name: "亞里斯多德學", description: "重拾古典哲人之學，融入教義。", baseCost: 51, effects: [{ target: "techPoints", value: 1 }] },
          { order: 7, name: "大學論爭", description: "學派於大學激辯真理。", baseCost: 58, effects: [{ target: "techPoints", value: 2 }] },
          { order: 8, name: "神秘靈修", description: "追求與神合一的內在體驗。", baseCost: 64, effects: [{ target: "warWearinessGrowth", value: -5 }] },
          { order: 9, name: "教會音樂", description: "發展複音聖歌，莊嚴禮拜。", baseCost: 70, effects: [{ target: "warWearinessGrowth", value: -10 }] },
          { order: 10, name: "彩窗聖像", description: "以彩繪玻璃述說聖經故事。", baseCost: 77, effects: [{ target: "warWearinessGrowth", value: -10 }] },
        ],
      },
      {
        lineKey: "law",
        lineLabel: "王權律法",
        lineKind: "branch",
        branchFrom: { lineKey: "society", order: 6 },
        nodes: [
          { order: 1, name: "大憲章約", description: "貴族迫王立約，限制王權。", baseCost: 19, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 2, name: "議會雛形", description: "召集等級代表議事納稅。", baseCost: 26, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 3, name: "陪審制度", description: "由鄉鄰組成陪審，參與審判。", baseCost: 32, effects: [{ target: "warWearinessGrowth", value: -5 }] },
          { order: 4, name: "普通法系", description: "以判例累積成通行之法。", baseCost: 38, effects: [{ target: "taxEfficiency", value: 2 }] },
        ],
      },
    ],
  },
  {
    eraSlug: "renaissance",
    lines: [
      {
        lineKey: "gov",
        lineLabel: "君主與治理",
        lineKind: "main",
        nodes: [
          { order: 1, name: "君主集權", description: "君王收攏權柄，削弱封建。", baseCost: 23, effects: [{ target: "taxEfficiency", value: 3 }] },
          { order: 2, name: "常備官署", description: "設常設衙署，處理國政。", baseCost: 30, effects: [{ target: "taxEfficiency", value: 3 }] },
          { order: 3, name: "外交使節", description: "互派常駐使節，經營邦交。", baseCost: 38, effects: [{ target: "warWearinessGrowth", value: -10 }] },
          { order: 4, name: "財稅總署", description: "集中管理國家財政。", baseCost: 45, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 5, name: "城邦共和", description: "富商望族共治城邦。", baseCost: 53, effects: [{ target: "taxEfficiency", value: 3 }] },
          { order: 6, name: "君權神授", description: "君權受命於天不容置疑，廣得民心賦稅；啟用人權滿意。", baseCost: 75, effects: [{ target: "taxEfficiency", value: 10 }, { target: "populationGrowth", value: 5 }, { target: "enableRightsSatisfaction", value: 1 }], keySlug: "divine_right" },
          { order: 7, name: "宮廷禮制", description: "訂立繁複宮儀，彰顯王威。", baseCost: 68, effects: [{ target: "warWearinessGrowth", value: -10 }] },
          { order: 8, name: "郵政通訊", description: "開辦郵驛，傳遞政商訊息。", baseCost: 75, effects: [{ target: "techPoints", value: 2 }] },
          { order: 9, name: "常備衛隊", description: "供養親衛部隊，鞏固王權。", baseCost: 83, effects: [{ target: "warWearinessGrowth", value: -10 }] },
          { order: 10, name: "國家理性", description: "以國家利益為施政最高準則。", baseCost: 90, effects: [{ target: "taxEfficiency", value: 4 }] },
        ],
      },
      {
        lineKey: "culture",
        lineLabel: "人文與藝術",
        lineKind: "main",
        nodes: [
          { order: 1, name: "人文主義", description: "重拾古典，以人為本探索學問。", baseCost: 23, effects: [{ target: "techPoints", value: 2 }] },
          { order: 2, name: "古籍校勘", description: "校訂古典文本，辨其真偽。", baseCost: 30, effects: [{ target: "techPoints", value: 2 }] },
          { order: 3, name: "透視畫法", description: "依幾何透視作畫，栩栩如生。", baseCost: 38, effects: [{ target: "techPoints", value: 2 }] },
          { order: 4, name: "油畫技法", description: "以油彩層疊，畫作光影細膩。", baseCost: 45, effects: [{ target: "warWearinessGrowth", value: -10 }] },
          { order: 5, name: "建築復古", description: "仿古典比例營造宏偉建築。", baseCost: 53, effects: [{ target: "buildingSlots", value: 1 }] },
          { order: 6, name: "世俗文學", description: "以俗語寫作，貼近市井。", baseCost: 60, effects: [{ target: "techPoints", value: 1 }] },
          { order: 7, name: "音樂複調", description: "多聲部交織，樂音繁複華美。", baseCost: 68, effects: [{ target: "warWearinessGrowth", value: -10 }] },
          { order: 8, name: "解剖寫實", description: "研究人體結構，寫實入畫。", baseCost: 75, effects: [{ target: "techPoints", value: 2 }] },
          { order: 9, name: "藝術贊助", description: "富室資助藝匠，百藝競榮。", baseCost: 83, effects: [{ target: "warWearinessGrowth", value: -10 }] },
          { order: 10, name: "學院沙龍", description: "文人雅集論藝，切磋新知。", baseCost: 90, effects: [{ target: "techPoints", value: 3 }] },
        ],
      },
      {
        lineKey: "print",
        lineLabel: "印刷傳媒",
        lineKind: "branch",
        branchFrom: { lineKey: "culture", order: 6 },
        nodes: [
          { order: 1, name: "活字印刷", description: "以活字排版量產書冊。", baseCost: 23, effects: [{ target: "techPoints", value: 1 }] },
          { order: 2, name: "書坊出版", description: "書商大量刊行書籍。", baseCost: 30, effects: [{ target: "techPoints", value: 1 }] },
          { order: 3, name: "民間識字", description: "廉價印本助民識字。", baseCost: 38, effects: [{ target: "populationGrowth", value: 1 }] },
          { order: 4, name: "小冊流通", description: "時政小冊快速流傳。", baseCost: 45, effects: [{ target: "techPoints", value: 1 }] },
        ],
      },
    ],
  },
  {
    eraSlug: "discovery",
    lines: [
      {
        lineKey: "gov",
        lineLabel: "重商與殖民",
        lineKind: "main",
        nodes: [
          { order: 1, name: "特許公司", description: "授予商團專營與拓殖之權。", baseCost: 32, effects: [] },
          { order: 2, name: "重商政策", description: "積累金銀，獎勵出口。", baseCost: 42, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 3, name: "殖民總督", description: "派總督管轄海外領地。", baseCost: 53, effects: [] },
          { order: 4, name: "關稅壁壘", description: "課徵關稅保護本國工商。", baseCost: 63, effects: [] },
          { order: 5, name: "國家銀行", description: "設立銀行掌理國庫信用。", baseCost: 74, effects: [] },
          { order: 6, name: "公債發行", description: "發行公債籌措軍政開支。", baseCost: 84, effects: [] },
          { order: 7, name: "契約勞役", description: "以契約招募海外墾殖之人。", baseCost: 95, effects: [] },
          { order: 8, name: "郵路擴張", description: "拓展海陸郵路，聯繫殖民。", baseCost: 105, effects: [] },
          { order: 9, name: "統計調查", description: "清點人口物產，資政決策。", baseCost: 116, effects: [] },
          { order: 10, name: "內閣會議", description: "大臣共議政務，輔佐君王。", baseCost: 126, effects: [] },
        ],
      },
      {
        lineKey: "thought",
        lineLabel: "宗教改革",
        lineKind: "main",
        nodes: [
          { order: 1, name: "因信稱義", description: "主張信仰得救，撼動舊教。", baseCost: 32, effects: [] },
          { order: 2, name: "譯經母語", description: "將聖經譯為俗語，普及信眾。", baseCost: 42, effects: [{ target: "techPoints", value: 1 }] },
          { order: 3, name: "宗教改革", description: "抗議教會積弊，分立新教。", baseCost: 53, effects: [] },
          { order: 4, name: "新教倫理", description: "崇尚勤儉入世，蔚為風氣。", baseCost: 63, effects: [] },
          { order: 5, name: "反宗教改革", description: "舊教整飭自強，重振聲勢。", baseCost: 74, effects: [] },
          { order: 6, name: "教派寬容", description: "漸容異派並存，緩和衝突。", baseCost: 84, effects: [] },
          { order: 7, name: "傳教使團", description: "遠赴海外傳布信仰。", baseCost: 95, effects: [] },
          { order: 8, name: "教理問答", description: "以問答教授信理，統一信仰。", baseCost: 105, effects: [] },
          { order: 9, name: "主日學校", description: "於禮拜日教習經文與識字。", baseCost: 116, effects: [] },
          { order: 10, name: "慈善結社", description: "信眾結社行善濟世。", baseCost: 126, effects: [] },
        ],
      },
      {
        lineKey: "nav",
        lineLabel: "航海學識",
        lineKind: "branch",
        branchFrom: { lineKey: "gov", order: 3 },
        nodes: [
          { order: 1, name: "航海圖誌", description: "繪製海圖記錄航路。", baseCost: 32, effects: [{ target: "techPoints", value: 1 }] },
          { order: 2, name: "天文導航", description: "觀星定位，遠航不迷。", baseCost: 42, effects: [] },
          { order: 3, name: "遊記見聞", description: "記述異域見聞，增廣視野。", baseCost: 53, effects: [] },
          { order: 4, name: "博物蒐奇", description: "蒐羅海外奇珍，開博物之學。", baseCost: 63, effects: [] },
        ],
      },
    ],
  },
  {
    eraSlug: "scientific",
    lines: [
      {
        lineKey: "gov",
        lineLabel: "理性治理",
        lineKind: "main",
        nodes: [
          { order: 1, name: "官房學術", description: "以學理經營國家財政與行政。", baseCost: 38, effects: [] },
          { order: 2, name: "常備文官", description: "建立專業文官考選。", baseCost: 50, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 3, name: "統計國情", description: "以數據掌握國力民情。", baseCost: 63, effects: [] },
          { order: 4, name: "開明專制", description: "君主以理性推行改革。", baseCost: 75, effects: [] },
          { order: 5, name: "法典編纂", description: "系統編纂國家法典。", baseCost: 88, effects: [] },
          { order: 6, name: "財政預算", description: "編列年度預算，量入為出。", baseCost: 100, effects: [] },
          { order: 7, name: "郵政官營", description: "國家統管郵政通訊。", baseCost: 113, effects: [] },
          { order: 8, name: "警政治安", description: "設常備警力維持秩序。", baseCost: 125, effects: [] },
          { order: 9, name: "戶籍登錄", description: "建立戶籍冊，清查人口。", baseCost: 138, effects: [] },
          { order: 10, name: "行政程序", description: "規範公文流程，提升效率。", baseCost: 150, effects: [] },
        ],
      },
      {
        lineKey: "science",
        lineLabel: "科學方法",
        lineKind: "main",
        nodes: [
          { order: 1, name: "實驗方法", description: "以實驗檢證假說，求真知。", baseCost: 38, effects: [] },
          { order: 2, name: "科學社團", description: "學人結社交流實驗成果。", baseCost: 50, effects: [{ target: "techPoints", value: 1 }] },
          { order: 3, name: "天體力學", description: "以定律解釋星辰運行。", baseCost: 63, effects: [] },
          { order: 4, name: "顯微觀察", description: "藉顯微鏡窺見微觀世界。", baseCost: 75, effects: [] },
          { order: 5, name: "血液循環", description: "揭示血液周流之理。", baseCost: 88, effects: [] },
          { order: 6, name: "學術期刊", description: "定期刊行論文，傳播新知。", baseCost: 100, effects: [{ target: "techPoints", value: 1 }] },
          { order: 7, name: "分類體系", description: "為萬物立分類命名之法。", baseCost: 113, effects: [] },
          { order: 8, name: "化學元素", description: "辨識物質基本組成。", baseCost: 125, effects: [] },
          { order: 9, name: "氣壓真空", description: "研究氣壓與真空之性。", baseCost: 138, effects: [] },
          { order: 10, name: "微積分術", description: "創立微積分，析變化之理。", baseCost: 150, effects: [] },
        ],
      },
      {
        lineKey: "edu",
        lineLabel: "公共教育",
        lineKind: "branch",
        branchFrom: { lineKey: "science", order: 6 },
        nodes: [
          { order: 1, name: "百科全書", description: "匯編知識成巨帙，啟迪民智。", baseCost: 38, effects: [{ target: "techPoints", value: 1 }] },
          { order: 2, name: "公立學堂", description: "官設學堂普及教育。", baseCost: 50, effects: [{ target: "populationGrowth", value: 1 }] },
          { order: 3, name: "女子識字", description: "推廣女子讀書識字。", baseCost: 63, effects: [] },
          { order: 4, name: "沙龍論學", description: "沙龍中論辯科學新知。", baseCost: 75, effects: [] },
        ],
      },
    ],
  },
];
