// Task #469 — 科技樹預設種子（social 領域，後半）

import type { SocialTechEffect } from "@workspace/db";
import type { TechTreeSeedEra } from "./types";

export const SOCIAL_ERAS_LATE: TechTreeSeedEra<SocialTechEffect>[] = [
  {
    eraSlug: "enlightenment",
    lines: [
      {
        lineKey: "gov",
        lineLabel: "立憲政治",
        lineKind: "main",
        nodes: [
          { order: 1, name: "社會契約", description: "主張政權源於人民同意。", baseCost: 49, effects: [] },
          { order: 2, name: "天賦人權", description: "倡言人皆生而有權。", baseCost: 65, effects: [] },
          { order: 3, name: "主權在民", description: "政府權力出於民意。", baseCost: 82, effects: [] },
          { order: 4, name: "成文憲法", description: "以憲法規範國家權力。", baseCost: 98, effects: [] },
          { order: 5, name: "代議政制", description: "選舉代表議決國政。", baseCost: 114, effects: [] },
          { order: 6, name: "三權分立", description: "行政立法司法分立制衡，善治國家並廣拓建築。", baseCost: 163, effects: [{ target: "taxEfficiency", value: 10 }, { target: "buildingSlots", value: 10 }], keySlug: "separation_of_powers" },
          { order: 7, name: "司法獨立", description: "使審判超然於政治干預。", baseCost: 147, effects: [] },
          { order: 8, name: "公民權利", description: "明定公民自由與義務。", baseCost: 163, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 9, name: "地方自治", description: "賦予地方議事自理之權。", baseCost: 179, effects: [] },
          { order: 10, name: "文官考選", description: "以考試甄選賢能任官。", baseCost: 195, effects: [] },
        ],
      },
      {
        lineKey: "thought",
        lineLabel: "啟蒙思潮",
        lineKind: "main",
        nodes: [
          { order: 1, name: "理性至上", description: "崇尚理性破除迷信。", baseCost: 49, effects: [] },
          { order: 2, name: "政治經濟", description: "探究財富生成與分配之理。", baseCost: 65, effects: [] },
          { order: 3, name: "自由貿易", description: "主張撤除壁壘互通有無。", baseCost: 82, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 4, name: "寬容論說", description: "倡議信仰與言論寬容。", baseCost: 98, effects: [] },
          { order: 5, name: "進步史觀", description: "相信人類文明不斷進步。", baseCost: 114, effects: [] },
          { order: 6, name: "百科精神", description: "匯集知識以啟迪世人。", baseCost: 130, effects: [{ target: "techPoints", value: 1 }] },
          { order: 7, name: "自然神論", description: "以理性看待神與自然。", baseCost: 147, effects: [] },
          { order: 8, name: "公共輿論", description: "咖啡館與報刊形成輿論。", baseCost: 163, effects: [] },
          { order: 9, name: "教育啟蒙", description: "主張教育造就理性公民。", baseCost: 179, effects: [] },
          { order: 10, name: "女權倡議", description: "有識之士倡言提升女性地位。", baseCost: 195, effects: [] },
        ],
      },
      {
        lineKey: "media",
        lineLabel: "報刊輿論",
        lineKind: "branch",
        branchFrom: { lineKey: "thought", order: 8 },
        nodes: [
          { order: 1, name: "定期報紙", description: "定期刊行新聞，傳布時事。", baseCost: 49, effects: [{ target: "techPoints", value: 1 }] },
          { order: 2, name: "咖啡沙龍", description: "市民聚談議政論學。", baseCost: 65, effects: [] },
          { order: 3, name: "政論小冊", description: "抨擊時政的小冊廣為流傳。", baseCost: 82, effects: [] },
          { order: 4, name: "郵政報路", description: "郵路遞送報刊，四方共聞。", baseCost: 98, effects: [] },
        ],
      },
    ],
  },
  {
    eraSlug: "industrial",
    lines: [
      {
        lineKey: "society",
        lineLabel: "勞工與社會",
        lineKind: "main",
        nodes: [
          { order: 1, name: "工廠制度", description: "集中機器生產於工廠。", baseCost: 76, effects: [] },
          { order: 2, name: "都市化潮", description: "人口湧入城市謀生。", baseCost: 101, effects: [] },
          { order: 3, name: "濟貧新法", description: "改革救濟，設濟貧院。", baseCost: 126, effects: [] },
          { order: 4, name: "工會結社", description: "工人結社爭取權益。", baseCost: 151, effects: [] },
          { order: 5, name: "工廠法規", description: "立法限制工時與童工。", baseCost: 176, effects: [{ target: "warWearinessGrowth", value: -5 }] },
          { order: 6, name: "公共衛生", description: "整治供水排污，遏止疫病。", baseCost: 202, effects: [{ target: "populationGrowth", value: 1 }] },
          { order: 7, name: "社會主義", description: "倡議公有共享、階級平等的社會理想。", baseCost: 284, effects: [], keySlug: "socialism" },
          { order: 8, name: "合作社運", description: "勞動者合股互助經營。", baseCost: 252, effects: [] },
          { order: 9, name: "義務教育", description: "立法推行國民基礎教育。", baseCost: 277, effects: [] },
          { order: 10, name: "選舉改革", description: "擴大選舉權，革除舊弊。", baseCost: 302, effects: [] },
        ],
      },
      {
        lineKey: "thought",
        lineLabel: "思想與傳播",
        lineKind: "main",
        nodes: [
          { order: 1, name: "功利主義", description: "以最大幸福為行事準則。", baseCost: 76, effects: [] },
          { order: 2, name: "實證哲學", description: "主張知識源於實證觀察。", baseCost: 101, effects: [] },
          { order: 3, name: "政治經濟批判", description: "批判資本積累與剝削。", baseCost: 126, effects: [] },
          { order: 4, name: "民族主義", description: "以民族認同凝聚國家。", baseCost: 151, effects: [] },
          { order: 5, name: "進化學說", description: "提出物種演化之論。", baseCost: 176, effects: [{ target: "techPoints", value: 1 }] },
          { order: 6, name: "自由主義", description: "倡言個人自由與市場。", baseCost: 202, effects: [] },
          { order: 7, name: "電報通訊", description: "以電報瞬息傳遞訊息。", baseCost: 227, effects: [] },
          { order: 8, name: "大眾報業", description: "廉價報紙普及大眾。", baseCost: 252, effects: [{ target: "techPoints", value: 1 }] },
          { order: 9, name: "攝影紀實", description: "以照片記錄真實影像。", baseCost: 277, effects: [] },
          { order: 10, name: "公共圖書", description: "廣設公共圖書館啟民。", baseCost: 302, effects: [] },
        ],
      },
      {
        lineKey: "welfare",
        lineLabel: "公共福利",
        lineKind: "branch",
        branchFrom: { lineKey: "society", order: 6 },
        nodes: [
          { order: 1, name: "疾病保險", description: "為工人設立疾病互助保險。", baseCost: 76, effects: [{ target: "populationGrowth", value: 1 }] },
          { order: 2, name: "勞動保護", description: "制定職災補償與安全規範。", baseCost: 101, effects: [{ target: "warWearinessGrowth", value: -5 }] },
          { order: 3, name: "城市公園", description: "闢建公園供市民休憩。", baseCost: 126, effects: [] },
          { order: 4, name: "自來水網", description: "鋪設供水管網，改善衛生。", baseCost: 151, effects: [] },
        ],
      },
    ],
  },
  {
    eraSlug: "ww1",
    lines: [
      {
        lineKey: "gov",
        lineLabel: "總體戰政",
        lineKind: "main",
        nodes: [
          { order: 1, name: "總體動員", description: "全國人力物力投入戰爭。", baseCost: 78, effects: [] },
          { order: 2, name: "戰時經濟", description: "政府統制生產與分配。", baseCost: 104, effects: [] },
          { order: 3, name: "配給制度", description: "憑券配給民生物資。", baseCost: 130, effects: [{ target: "warWearinessGrowth", value: -5 }] },
          { order: 4, name: "宣傳機器", description: "以宣傳鼓舞民心士氣。", baseCost: 156, effects: [] },
          { order: 5, name: "婦女參政", description: "戰時婦女投入生產獲參政權。", baseCost: 182, effects: [] },
          { order: 6, name: "徵兵體系", description: "建立普遍徵兵制度。", baseCost: 208, effects: [] },
          { order: 7, name: "情報審查", description: "管制通訊審查消息。", baseCost: 234, effects: [] },
          { order: 8, name: "戰債募集", description: "發行戰爭公債籌款。", baseCost: 260, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 9, name: "官僚擴張", description: "政府機構急速膨脹。", baseCost: 286, effects: [] },
          { order: 10, name: "停戰談判", description: "交戰各方協商停火。", baseCost: 312, effects: [] },
        ],
      },
      {
        lineKey: "thought",
        lineLabel: "現代思潮",
        lineKind: "main",
        nodes: [
          { order: 1, name: "精神分析", description: "探究潛意識與心理。", baseCost: 78, effects: [] },
          { order: 2, name: "相對論說", description: "顛覆時空絕對之觀念。", baseCost: 104, effects: [{ target: "techPoints", value: 1 }] },
          { order: 3, name: "前衛藝術", description: "打破傳統的藝術實驗。", baseCost: 130, effects: [] },
          { order: 4, name: "大眾電影", description: "電影成為大眾娛樂。", baseCost: 156, effects: [] },
          { order: 5, name: "廣播萌芽", description: "無線廣播開始傳聲。", baseCost: 182, effects: [{ target: "techPoints", value: 1 }] },
          { order: 6, name: "社會調查", description: "以調查了解社會實況。", baseCost: 208, effects: [] },
          { order: 7, name: "公共衛生署", description: "設署統籌防疫保健。", baseCost: 234, effects: [{ target: "populationGrowth", value: 1 }] },
          { order: 8, name: "女性主義", description: "倡議兩性平權。", baseCost: 260, effects: [] },
          { order: 9, name: "和平主義", description: "反思戰禍倡導和平。", baseCost: 286, effects: [{ target: "warWearinessGrowth", value: -5 }] },
          { order: 10, name: "國際聯盟", description: "各國結盟以維和平。", baseCost: 312, effects: [] },
        ],
      },
      {
        lineKey: "media",
        lineLabel: "宣傳輿論",
        lineKind: "branch",
        branchFrom: { lineKey: "gov", order: 4 },
        nodes: [
          { order: 1, name: "海報宣傳", description: "以海報動員民心。", baseCost: 78, effects: [] },
          { order: 2, name: "新聞審查", description: "嚴管報導以利戰局。", baseCost: 104, effects: [] },
          { order: 3, name: "戰地攝影", description: "記錄前線影像震撼後方。", baseCost: 130, effects: [] },
          { order: 4, name: "電影新聞", description: "於戲院放映時事影片。", baseCost: 156, effects: [] },
        ],
      },
    ],
  },
  {
    eraSlug: "ww2",
    lines: [
      {
        lineKey: "gov",
        lineLabel: "戰時體制",
        lineKind: "main",
        nodes: [
          { order: 1, name: "極權統制", description: "國家全面控制社會。", baseCost: 95, effects: [] },
          { order: 2, name: "計畫經濟", description: "依計畫統籌生產。", baseCost: 126, effects: [] },
          { order: 3, name: "戰時配給", description: "嚴格配給稀缺物資。", baseCost: 158, effects: [{ target: "warWearinessGrowth", value: -5 }] },
          { order: 4, name: "軍工複合", description: "軍需工業與政府結合。", baseCost: 189, effects: [] },
          { order: 5, name: "情報機構", description: "設立專責情報偵防機關。", baseCost: 221, effects: [] },
          { order: 6, name: "密碼破譯", description: "破解敵方通訊密碼。", baseCost: 252, effects: [{ target: "techPoints", value: 1 }] },
          { order: 7, name: "大後方生產", description: "動員後方全力增產。", baseCost: 284, effects: [] },
          { order: 8, name: "徵稅擴大", description: "提高戰時稅率充國庫。", baseCost: 315, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 9, name: "難民安置", description: "收容安置流離民眾。", baseCost: 347, effects: [] },
          { order: 10, name: "戰後重建", description: "規劃戰後復興藍圖。", baseCost: 378, effects: [] },
        ],
      },
      {
        lineKey: "society",
        lineLabel: "社會與人權",
        lineKind: "main",
        nodes: [
          { order: 1, name: "福利國家", description: "政府保障國民基本生活。", baseCost: 95, effects: [] },
          { order: 2, name: "全民保險", description: "推行涵蓋全民的社會保險。", baseCost: 126, effects: [{ target: "populationGrowth", value: 1 }] },
          { order: 3, name: "勞資協商", description: "建立勞資談判機制。", baseCost: 158, effects: [] },
          { order: 4, name: "婦女就業", description: "婦女大量投入工廠生產。", baseCost: 189, effects: [] },
          { order: 5, name: "種族反思", description: "反省種族迫害之禍。", baseCost: 221, effects: [] },
          { order: 6, name: "世界人權", description: "宣示普世人權原則。", baseCost: 252, effects: [] },
          { order: 7, name: "難民公約", description: "訂立保護難民的國際規範。", baseCost: 284, effects: [] },
          { order: 8, name: "抗生素普及", description: "抗生素挽救無數生命。", baseCost: 315, effects: [{ target: "populationGrowth", value: 1 }] },
          { order: 9, name: "大眾教育", description: "擴大中等教育普及率。", baseCost: 347, effects: [] },
          { order: 10, name: "聯合國創", description: "成立聯合國維護和平。", baseCost: 378, effects: [] },
        ],
      },
      {
        lineKey: "media",
        lineLabel: "廣播宣傳",
        lineKind: "branch",
        branchFrom: { lineKey: "gov", order: 4 },
        nodes: [
          { order: 1, name: "國家廣播", description: "以廣播統一宣傳口徑。", baseCost: 95, effects: [{ target: "techPoints", value: 1 }] },
          { order: 2, name: "電影動員", description: "以劇情片鼓舞民心。", baseCost: 126, effects: [] },
          { order: 3, name: "心理作戰", description: "對敵散布心理攻勢。", baseCost: 158, effects: [] },
          { order: 4, name: "新聞管制", description: "全面管控戰時消息。", baseCost: 189, effects: [] },
        ],
      },
    ],
  },
  {
    eraSlug: "cold_war",
    lines: [
      {
        lineKey: "gov",
        lineLabel: "冷戰政治",
        lineKind: "main",
        nodes: [
          { order: 1, name: "兩極格局", description: "世界分裂為兩大陣營。", baseCost: 168, effects: [] },
          { order: 2, name: "圍堵政策", description: "遏制對立陣營擴張。", baseCost: 224, effects: [] },
          { order: 3, name: "意識形態戰", description: "以思想輿論相互較勁。", baseCost: 280, effects: [] },
          { order: 4, name: "情報冷戰", description: "諜報機構暗中角力。", baseCost: 336, effects: [] },
          { order: 5, name: "太空競賽", description: "兩強競逐太空成就。", baseCost: 392, effects: [{ target: "techPoints", value: 1 }] },
          { order: 6, name: "軍備管制", description: "談判限制核武擴張。", baseCost: 448, effects: [] },
          { order: 7, name: "不結盟運動", description: "新興國家拒選邊站。", baseCost: 504, effects: [] },
          { order: 8, name: "福利擴張", description: "擴大社會福利安撫民心。", baseCost: 560, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 9, name: "民權運動", description: "群眾爭取平等公民權。", baseCost: 616, effects: [{ target: "warWearinessGrowth", value: -5 }] },
          { order: 10, name: "緩和外交", description: "兩陣營尋求局勢緩和。", baseCost: 672, effects: [] },
        ],
      },
      {
        lineKey: "society",
        lineLabel: "社會與資訊",
        lineKind: "main",
        nodes: [
          { order: 1, name: "電視普及", description: "電視進入千家萬戶。", baseCost: 168, effects: [{ target: "techPoints", value: 1 }] },
          { order: 2, name: "消費社會", description: "大眾消費蔚為風潮。", baseCost: 224, effects: [] },
          { order: 3, name: "青年文化", description: "年輕世代形成次文化。", baseCost: 280, effects: [] },
          { order: 4, name: "女權再興", description: "第二波女權運動興起。", baseCost: 336, effects: [] },
          { order: 5, name: "環保意識", description: "覺醒關注環境污染。", baseCost: 392, effects: [] },
          { order: 6, name: "大眾傳播", description: "媒體塑造公共議題。", baseCost: 448, effects: [] },
          { order: 7, name: "電腦初興", description: "大型電腦步入應用。", baseCost: 504, effects: [] },
          { order: 8, name: "全民健保", description: "推行普及醫療保障。", baseCost: 560, effects: [{ target: "populationGrowth", value: 1 }] },
          { order: 9, name: "高等教育普及", description: "大學教育向大眾開放。", baseCost: 616, effects: [] },
          { order: 10, name: "資訊網路雛形", description: "分封網路連結電腦。", baseCost: 672, effects: [] },
        ],
      },
      {
        lineKey: "media",
        lineLabel: "大眾媒體",
        lineKind: "branch",
        branchFrom: { lineKey: "society", order: 6 },
        nodes: [
          { order: 1, name: "衛星轉播", description: "以衛星即時傳送影像。", baseCost: 168, effects: [{ target: "techPoints", value: 1 }] },
          { order: 2, name: "廣告行銷", description: "商業廣告主導傳播。", baseCost: 224, effects: [] },
          { order: 3, name: "民意調查", description: "以抽樣民調探知輿情。", baseCost: 280, effects: [] },
          { order: 4, name: "有線電視", description: "多頻道有線電視興起。", baseCost: 336, effects: [] },
        ],
      },
    ],
  },
  {
    eraSlug: "modern",
    lines: [
      {
        lineKey: "gov",
        lineLabel: "全球治理",
        lineKind: "main",
        nodes: [
          { order: 1, name: "全球化潮", description: "資本與商品跨越國界流動。", baseCost: 375, effects: [] },
          { order: 2, name: "區域整合", description: "國家結盟形成經濟共同體。", baseCost: 500, effects: [] },
          { order: 3, name: "自由市場", description: "市場開放主導經濟。", baseCost: 625, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 4, name: "民主鞏固", description: "民主制度深化穩固。", baseCost: 750, effects: [] },
          { order: 5, name: "電子政府", description: "政務數位化便民高效。", baseCost: 875, effects: [] },
          { order: 6, name: "反恐體制", description: "建立反恐與安全機制。", baseCost: 1000, effects: [] },
          { order: 7, name: "移民政策", description: "規範跨國人口流動。", baseCost: 1125, effects: [] },
          { order: 8, name: "透明治理", description: "推動資訊公開與問責。", baseCost: 1250, effects: [] },
          { order: 9, name: "永續發展", description: "兼顧環境與發展目標。", baseCost: 1375, effects: [] },
          { order: 10, name: "全球峰會", description: "各國元首共商全球議題。", baseCost: 1500, effects: [] },
        ],
      },
      {
        lineKey: "info",
        lineLabel: "資訊社會",
        lineKind: "main",
        nodes: [
          { order: 1, name: "個人電腦", description: "電腦進入個人與家庭。", baseCost: 375, effects: [{ target: "techPoints", value: 1 }] },
          { order: 2, name: "網際網路", description: "全球網路互聯互通。", baseCost: 500, effects: [{ target: "techPoints", value: 1 }] },
          { order: 3, name: "行動通訊", description: "手機讓人隨時聯繫。", baseCost: 625, effects: [] },
          { order: 4, name: "社群媒體", description: "社群平台重塑輿論。", baseCost: 750, effects: [] },
          { order: 5, name: "搜尋引擎", description: "資訊隨手可得。", baseCost: 875, effects: [] },
          { order: 6, name: "電子商務", description: "線上交易蓬勃發展。", baseCost: 1000, effects: [] },
          { order: 7, name: "開放資料", description: "公開資料驅動創新。", baseCost: 1125, effects: [] },
          { order: 8, name: "遠距工作", description: "網路支持異地協作。", baseCost: 1250, effects: [] },
          { order: 9, name: "數位素養", description: "培養公民資訊能力。", baseCost: 1375, effects: [{ target: "populationGrowth", value: 1 }] },
          { order: 10, name: "雲端運算", description: "運算資源隨需取用。", baseCost: 1500, effects: [] },
        ],
      },
      {
        lineKey: "health",
        lineLabel: "現代醫療",
        lineKind: "branch",
        branchFrom: { lineKey: "info", order: 5 },
        nodes: [
          { order: 1, name: "基因醫學", description: "解讀基因防治疾病。", baseCost: 375, effects: [{ target: "populationGrowth", value: 1 }] },
          { order: 2, name: "精準醫療", description: "依個體特徵量身治療。", baseCost: 500, effects: [] },
          { order: 3, name: "遠距醫療", description: "藉網路提供醫療諮詢。", baseCost: 625, effects: [] },
          { order: 4, name: "疫苗快製", description: "快速研製疫苗抗疫。", baseCost: 750, effects: [] },
        ],
      },
    ],
  },
  {
    eraSlug: "future",
    lines: [
      {
        lineKey: "gov",
        lineLabel: "未來治理",
        lineKind: "main",
        nodes: [
          { order: 1, name: "演算治理", description: "以演算法輔助公共決策。", baseCost: 986, effects: [] },
          { order: 2, name: "數位公民", description: "以數位身分行使權利。", baseCost: 1314, effects: [] },
          { order: 3, name: "全民基本收入", description: "保障人人基本所得。", baseCost: 1643, effects: [{ target: "taxEfficiency", value: 1 }] },
          { order: 4, name: "直接民主", description: "藉科技實現即時公投。", baseCost: 1971, effects: [] },
          { order: 5, name: "星際法制", description: "制定太空與星際規範。", baseCost: 2300, effects: [] },
          { order: 6, name: "人工智慧倫理", description: "規範智慧體之權責。", baseCost: 2628, effects: [] },
          { order: 7, name: "後稀缺經濟", description: "資源豐足重塑分配。", baseCost: 2957, effects: [] },
          { order: 8, name: "全球共治", description: "跨國協力治理地球。", baseCost: 3285, effects: [] },
          { order: 9, name: "意識上傳倫理", description: "討論心智數位化之界。", baseCost: 3614, effects: [] },
          { order: 10, name: "文明備援", description: "為文明存續建立備援。", baseCost: 3942, effects: [] },
        ],
      },
      {
        lineKey: "thought",
        lineLabel: "未來思潮",
        lineKind: "main",
        nodes: [
          { order: 1, name: "超人類主義", description: "藉科技超越人體極限。", baseCost: 986, effects: [] },
          { order: 2, name: "集體智能", description: "群體與機器共構智慧。", baseCost: 1314, effects: [{ target: "techPoints", value: 1 }] },
          { order: 3, name: "虛擬社會", description: "人們生活於虛擬世界。", baseCost: 1643, effects: [] },
          { order: 4, name: "腦機介面", description: "以意念直接操控機器。", baseCost: 1971, effects: [{ target: "techPoints", value: 1 }] },
          { order: 5, name: "通用人工智慧", description: "具備廣泛能力的智慧體。", baseCost: 2300, effects: [] },
          { order: 6, name: "記憶共享", description: "直接交換經驗與記憶。", baseCost: 2628, effects: [] },
          { order: 7, name: "情感演算", description: "機器理解並回應情感。", baseCost: 2957, effects: [] },
          { order: 8, name: "數位永生", description: "心智於數位中延續。", baseCost: 3285, effects: [] },
          { order: 9, name: "星際文化", description: "跨星球的多元文化。", baseCost: 3614, effects: [] },
          { order: 10, name: "宇宙哲思", description: "思索文明在宇宙的意義。", baseCost: 3942, effects: [] },
        ],
      },
      {
        lineKey: "welfare",
        lineLabel: "未來福祉",
        lineKind: "branch",
        branchFrom: { lineKey: "thought", order: 4 },
        nodes: [
          { order: 1, name: "長壽醫療", description: "大幅延長健康壽命。", baseCost: 986, effects: [{ target: "populationGrowth", value: 1 }] },
          { order: 2, name: "全自動生產", description: "機器承擔多數勞動。", baseCost: 1314, effects: [] },
          { order: 3, name: "環境再生", description: "科技修復受損生態。", baseCost: 1643, effects: [] },
          { order: 4, name: "太空移居", description: "人類向外太空拓殖。", baseCost: 1971, effects: [] },
        ],
      },
    ],
  },
];
